import assert from 'node:assert/strict';
import * as XLSX from 'xlsx';
export async function testCollaborationFixes({ok,call,state,original,clerk,sales,pass,preview}){
 const sh={I3:{v:'订单号',t:'s'},M3:{v:'订单数量',t:'s'},BF3:{v:'包装入仓数量',t:'s'}};
 for(let r=4;r<=6;r++)for(const [c,v] of Object.entries({A:['度昂','示例外厂甲','示例外厂乙'][r-4],B:'TINA',I:'FIX-'+r,J:'DNFIX',C:'测试客户甲',L:'C1',X:'红色花纹向外侧',H:'白片',M:3,AX:3,AY:46200,BD:0,BF:0}))sh[c+r]={v,t:typeof v==='number'?'n':'s'};
 sh['!ref']='A1:BI6';const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sh,'动态表');let j=await original(XLSX.write(book,{type:'buffer',bookType:'xlsx'}),'active','修复验收.xlsx');await ok('ledger-commit',{id:j.id,offset:0});
 let d=await state(),member=d.members.find(m=>m.email===clerk.email);await ok('member',{...member,role:'clerk',departments:['plastic','outsourcing'],orderScope:'all',active:true});let o=d.orders.find(o=>o.orderNo==='FIX-4'),external=d.orders.find(o=>o.orderNo==='FIX-5');
 const payload={lineId:o.id,version:o.version,process:'assembly',department:'plastic',input:3,wip:0,reportDate:'2026-09-17',reason:'没有损耗',token:crypto.randomUUID(),patch:{BD:'3',BE:'9/17'}};
 let res=await call('loss-record',payload,clerk);assert.equal(res.status,400);assert.match((await res.json()).error,/BE · 钉装完成日/);assert(!(await state()).losses.some(r=>r.lineId===o.id));
 res=await call('loss-record',{...payload,patch:{BD:'3',BE:'2026-02-30'}},clerk);assert.equal(res.status,400);assert.match((await res.json()).error,/BE · 钉装完成日/);
 const saved=await ok('loss-record',{...payload,patch:{BD:'3',BE:'２０２６年９月１７日'}},clerk);assert.equal(saved.item.loss,0);assert.equal(saved.item.good,3);o=(await state()).orders.find(x=>x.id===o.id);assert.equal(o.ledger.columns.BE,'2026-09-17');assert.equal(o.ledger.columns.AY,'46200');assert.equal(o.quantity,3);
 const retry=await ok('loss-record',{...payload,patch:{BD:'3',BE:'２０２６年９月１７日'}},clerk);assert(retry.repeated);pass('胶架文员：错误精确指向 BE；改为完整日期后 3-3-0 报工损耗原子保存，原序列日期不被重写，重试不重复记账');
 await ok('ledger-edit',{id:o.id,version:o.version,patch:{BE:'2026.9.16',AS:'2026 / 9 / 15',AU:' - '},reason:'兼容日期格式'},clerk);o=(await state()).orders.find(x=>x.id===o.id);assert.equal(o.ledger.columns.BE,'2026-09-16');assert.equal(o.ledger.columns.AS,'2026-09-15');assert.equal(o.ledger.columns.AU,'-');
 res=await call('loss-record',{...payload,version:o.version,reportDate:'9/17',previousId:saved.item.id,token:crypto.randomUUID(),patch:{}},clerk);assert.equal(res.status,400);assert.match((await res.json()).error,/损耗确认日期/);pass('日期兼容横线、斜线、点号、中文、全角及空格；缺年或不存在的日期仍被明确阻止');
 async function exported(action){const response=await call(action);assert.equal(response.status,200);const b=XLSX.read(await response.arrayBuffer());return XLSX.utils.sheet_to_json(b.Sheets[b.SheetNames[0]]);}
 const ext=await exported('ledger-export?production=external&mode=active');assert(ext.some(r=>r['订单号']==='FIX-5'));assert(ext.some(r=>r['订单号']==='FIX-6'));assert(!ext.some(r=>r['订单号']==='FIX-4'));for(const duplicate of ['A · 生产厂','B · 跟单员','C · 客户号','H · 镜片类型','I · 订单号','J · 图纸编号 / 款号','L · 色号','M · 订单数量','U · PMC排期','W · 产品类型','AB · 状态备注','BF · 包装入仓数量','BH · 结单日'])assert(!(duplicate in ext[0]),`PMC export duplicate column: ${duplicate}`);const jinbo=await exported('ledger-export?production=external&factory='+encodeURIComponent('示例外厂甲'));assert.equal(jinbo.length,1);assert.equal(jinbo[0]['生产厂'],'示例外厂甲');
 assert.equal((await call('ledger-edit',{id:external.id,version:external.version,patch:{BD:'3'},reason:'外厂不记内部工序'},clerk)).status,403);assert.equal((await call('loss-record',{...payload,lineId:external.id,version:external.version,token:crypto.randomUUID()},clerk)).status,403);await ok('pmc-save',{changes:[{id:external.id,version:external.version,col:'AB',value:'示例外厂甲回复9月20日交货'}]});external=(await state()).orders.find(x=>x.id===external.id);assert.equal(external.notes,'示例外厂甲回复9月20日交货');assert.equal((await call('pmc-save',{changes:[{id:external.id,version:external.version,col:'AC',value:'2026-09-17'}]})).status,403);pass('成品外发按生产厂分表、按厂导出；外厂排期备注可维护，内部工序和损耗不混记');
 const ir=await ok('pmc-round',{token:crypto.randomUUID(),lineIds:[o.id],scope:'厂内',productionScope:'internal'}),er=await ok('pmc-round',{token:crypto.randomUUID(),lineIds:[external.id],scope:'示例外厂甲',productionScope:'external'});assert((await ok('pmc-data?scope=internal')).rounds.some(r=>r.id===ir.round.id));assert((await ok('pmc-data?scope=external')).rounds.some(r=>r.id===er.round.id));await ok('pmc-review',{roundId:ir.round.id,lineId:o.id,version:o.version,status:'done'});await ok('pmc-review',{roundId:er.round.id,lineId:external.id,version:external.version,status:'done'});assert.equal((await call('pmc-round',{token:crypto.randomUUID(),lineIds:[external.id],scope:'错分',productionScope:'internal'})).status,409);pass('厂内与成品外发核对进度独立保存，跨表范围被阻止');
 const working=await call('export',{type:'working',filters:{q:'FIX-4'}}),wb=XLSX.read(await working.arrayBuffer()),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);assert.equal(rows.length,1);assert.equal(rows[0]['色号'],'C1');for(const duplicate of ['C · 客户号','H · 镜片类型','I · 订单号','J · 图纸编号 / 款号','L · 色号','M · 订单数量','T · 客原交货期','U · PMC排期','W · 产品类型','AB · 状态备注'])assert(!(duplicate in rows[0]),`working export duplicate column: ${duplicate}`);assert.equal(rows[0]['X · 圈色'],'红色花纹向外侧');let pj=await preview(rows);assert.equal(pj.rows[0].status,'skip');
 const legacy={...rows[0],'圈色':'C1','L · 色号':'C1'};delete legacy['色号'];pj=await preview([{...legacy,'内部跟进备注':'旧导出文件照常回传'}]);assert.equal(pj.rows[0].status,'update');await ok('commit-import',{id:pj.id,selected:[2]});assert.equal((await state()).orders.find(x=>x.id===o.id).ledger.columns.AB,'旧导出文件照常回传');pj=await preview([{...rows[0],'圈色':'C2'}]);assert.equal(pj.rows[0].status,'error');pass('导出仅保留一列色号，真实 X 圈色保留；新版零差异回传、旧版兼容、矛盾色号拦截');
 const bulk=Array.from({length:557},(_,i)=>({'订单号':'BULK-'+i,'客户':'测试客户甲','图纸编号':'DN-BULK','色号':'C1','镜片类型':'白片','订单数量':3}));j=await preview(bulk);assert.equal(j.rows.length,557);const selected=j.rows.map(r=>r.index);let p=await ok('commit-import',{id:j.id,selected,offset:0});assert.equal(p.offset,200);const before=(await state()).revision;let repeated=await ok('commit-import',{id:j.id,selected,offset:0});assert.equal(repeated.offset,200);assert.equal((await state()).revision,before);const resumed=await ok('job?id='+j.id);assert.equal(resumed.applied,200);assert.equal((await call('commit-import',{id:j.id,selected:selected.slice(1),offset:200})).status,409);p=await ok('commit-import',{id:j.id,selected,offset:200});assert.equal(p.offset,400);p=await ok('commit-import',{id:j.id,selected,offset:400});assert.equal(p.status,'已提交');assert.equal(p.count,557);assert.equal((await state()).orders.filter(o=>o.orderNo.startsWith('BULK-')).length,557);pass('557 行自动按 200/200/157 合并，中断恢复、请求重试不重复写入，已开始批次不能变更选择');
 const exp=await call('export',{type:'working',filters:{q:'BULK-'}}),ex=XLSX.read(await exp.arrayBuffer()),updates=XLSX.utils.sheet_to_json(ex.Sheets[ex.SheetNames[0]]).map(r=>({...r,'内部跟进备注':'批量更新'}));j=await preview(updates);const pick=j.rows.map(r=>r.index);await ok('commit-import',{id:j.id,selected:pick,offset:0});const conflict=(await state()).orders.find(o=>o.id===j.rows[220].after.id);await ok('edit-order',{id:conflict.id,version:conflict.version,patch:{notes:'同事刚更新'}});assert.equal((await call('commit-import',{id:j.id,selected:pick,offset:200})).status,409);assert.equal((await state()).orders.find(o=>o.id===conflict.id).notes,'同事刚更新');assert.equal((await ok('job?id='+j.id)).offset,200);pass('大批回传中途发生同事修改时停止当前批，已保存部分保留且不覆盖同事内容');
}
