import assert from 'node:assert/strict';
import * as XLSX from 'xlsx';
export async function testLosses({ok,call,state,original,admin,clerk,sales,pass}){
 const sheet={I3:{t:'s',v:'订单号'},M3:{t:'s',v:'订单数量'},BF3:{t:'s',v:'包装入仓数量'}};
 for(let r=4;r<=6;r++)for(const [c,v] of Object.entries({I:'LOSS-00'+(r-3),J:'DN-LOSS-'+r,C:r===6?'未授权客户':'测试客户甲',H:'白片',L:'C1',M:200,N:220,AV:220,AX:210,BD:r===5?'':204,BF:0}))sheet[c+r]={t:typeof v==='number'?'n':'s',v};
 sheet['!ref']='A1:BF6';const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'动态表');const j=await original(XLSX.write(book,{type:'buffer',bookType:'xlsx'}),'active','损耗测试.xlsx');await ok('ledger-commit',{id:j.id,offset:0});
 let member=(await state()).members.find(m=>m.email===clerk.email);await ok('member',{...member,departments:['plastic'],customers:[],active:true});
 let data=await state(),o=data.orders.find(o=>o.orderNo==='LOSS-001'),blank=data.orders.find(o=>o.orderNo==='LOSS-002'),hidden=data.orders.find(o=>o.orderNo==='LOSS-003');
 const base={lineId:o.id,version:o.version,process:'assembly',department:'plastic',input:210,wip:4,reportDate:'2026-08-31',reason:'核对钉装报废两副',token:crypto.randomUUID()},first=await ok('loss-record',base,clerk);
 assert.equal(first.item.loss,2);assert.equal(first.item.delta,2);assert.equal(first.item.good,204);assert.equal(first.item.orderQuantity,200);
 const rev=(await state()).revision;assert.equal((await ok('loss-record',base,clerk)).repeated,true);assert.equal((await state()).revision,rev);
 assert.equal((await call('loss-record',{...base,reason:'更换相同提交标识的内容'},clerk)).status,409);
 pass('投入 210、完成 204、仍在制 4，仅记损耗 2；同一提交重试不重复计数');
 let body={...base,wip:0,reportDate:'2026-09-01',previousId:first.item.id,token:crypto.randomUUID()},second=await ok('loss-record',body,clerk);assert.equal(second.item.loss,6);assert.equal(second.item.delta,4);
 assert.equal((await call('loss-record',{...body,previousId:first.item.id,token:crypto.randomUUID()},clerk)).status,409);
 const correction={...body,wip:1,previousId:second.item.id,token:crypto.randomUUID(),reason:'核对一副仍可返工'};
 assert.equal((await call('loss-record',correction,clerk)).status,400);const third=await ok('loss-record',{...correction,correction:true},clerk);assert.equal(third.item.delta,-1);
 const month=await call('loss-export?month=2026-09&department=plastic');assert.equal(month.status,200);const x=XLSX.read(await month.arrayBuffer()),summary=XLSX.utils.sheet_to_json(x.Sheets['部门月度汇总'],{range:5}),details=XLSX.utils.sheet_to_json(x.Sheets['损耗确认明细']);assert.equal(summary[0]['新增损耗'],4);assert.equal(summary[0]['冲减损耗'],1);assert.equal(summary[0]['当月净损耗'],3);assert.equal(summary[0]['涉及订单数量'],200);assert.equal(details.length,2);
 const aug=await call('loss-export?month=2026-08');const ax=XLSX.read(await aug.arrayBuffer());assert.equal(XLSX.utils.sheet_to_json(ax.Sheets['损耗确认明细'])[0]['本次损耗增减'],2);
 pass('跨月只记新增差额，冲减留痕：8 月 2、9 月新增 4 减 1；月报数量与明细一致');
 const mes={...body,source:'mes',input:null,wip:null,reportedLoss:5,sourceRef:'MES报废处理单 TEST-001',previousId:third.item.id,token:crypto.randomUUID(),reason:'MES确认累计报废五副'};
 assert.equal((await call('loss-record',{...mes,sourceRef:''},clerk)).status,400);const fourth=await ok('loss-record',mes,clerk);assert.equal(fourth.item.delta,0);assert.equal(fourth.item.loss,5);assert.equal(fourth.item.input,null);
 assert.equal((await call('loss-record',{...mes,reportedLoss:null,previousId:fourth.item.id,token:crypto.randomUUID()},clerk)).status,400);
 pass('MES 来源必须填已确认累计损耗和凭证；从公式切换到相同 MES 数量不会重复累计');
 for(const p of [{input:203,wip:0},{input:210.2},{reportDate:'2026-02-30'},{reportDate:'2026-08-30'},{reportDate:'2099-01-01'}])assert.equal((await call('loss-record',{...body,...p,previousId:fourth.item.id,token:crypto.randomUUID()},clerk)).status,400);
 assert.equal((await call('loss-record',{...base,lineId:blank.id,version:blank.version,token:crypto.randomUUID()},clerk)).status,400);
 for(const [user,extra] of [[sales,{}],[clerk,{process:'plating',department:'plating'}]])assert.equal((await call('loss-record',{...body,...extra,token:crypto.randomUUID()},user)).status,403);
 const before=await state();assert.equal((await call('loss-record',{...body,previousId:fourth.item.id,patch:{AG:'10'},token:crypto.randomUUID()},clerk)).status,403);assert.equal((await state()).revision,before.revision);
 pass('空白报工、负损耗、非法数量日期、跨部门与销售写入均被阻止，失败没有部分写入');
 const combined={...body,previousId:fourth.item.id,patch:{BD:'205'},input:212,wip:0,token:crypto.randomUUID(),reason:'本部门报工与实际损耗同时确认'};
 const combinedResult=await ok('loss-record',combined,clerk);o=(await state()).orders.find(x=>x.id===o.id);assert.equal(o.ledger.columns.BD,'205');assert.equal(o.quantity,200);assert.equal(o.ledger.columns.BF,'0');assert.equal(combinedResult.item.loss,7);assert.equal(combinedResult.item.orderVersion,o.version);
 assert.equal((await call('loss-record',{...body,previousId:combinedResult.item.id,token:crypto.randomUUID()},clerk)).status,409);
 const raceBase={...body,version:o.version,input:214,previousId:combinedResult.item.id,wip:0};const race=await Promise.all([call('loss-record',{...raceBase,token:crypto.randomUUID()},clerk),call('loss-record',{...raceBase,input:215,token:crypto.randomUUID()},clerk)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);
 pass('报工与损耗一次原子保存，保留订单及入仓数量；旧版本与并发重复记账被阻止');
 await ok('loss-record',{...base,lineId:hidden.id,version:hidden.version,wip:0,reportDate:'2026-09-01',token:crypto.randomUUID()},admin);
 const salesData=await ok('data',undefined,sales);assert(!salesData.losses.some(r=>r.lineId===hidden.id));const salesExport=await call('loss-export?month=2026-09',undefined,sales);assert.equal(salesExport.status,200);const sx=XLSX.read(await salesExport.arrayBuffer());assert(!XLSX.utils.sheet_to_json(sx.Sheets['损耗确认明细']).some(r=>r['订单号']==='LOSS-003'));
 await ok('ledger-lifecycle',{id:o.id,version:o.version,mode:'archived',reason:'损耗测试归档保留记录',closedDate:'2026-09-01'});assert.equal((await call('loss-record',{...raceBase,token:crypto.randomUUID()},clerk)).status,403);assert((await state()).losses.some(r=>r.lineId===o.id));
 const archived=await call('loss-export?month=2026-09');const ar=XLSX.read(await archived.arrayBuffer());assert(XLSX.utils.sheet_to_json(ar.Sheets['损耗确认明细']).some(r=>r['订单号']==='LOSS-001'));
 pass('查询和导出执行客户权限，结单后损耗仍保留在原月份且不可追加');
}
