import assert from 'node:assert/strict';
import {purchaseFixture} from './purchase-fixture.mjs';
import * as XLSX from 'xlsx';
export async function testPurchases({ok,call,sales,pass}){
 const fixture=purchaseFixture(),{bytes}=fixture;
 const preview=async(data=bytes,date='2026-09-17')=>{const f=new FormData();f.set('file',new File([data],'合成采购测试.xlsx'));f.set('sourceAsOf',date);return ok('purchase-preview',f);};
 let job=await preview();assert.equal(job.summary.sourceRows,fixture.count);assert.equal(job.summary.orders,fixture.orders);assert.equal(job.summary.suppliers,fixture.suppliers);while(job.status!=='已完成')job=await ok('purchase-commit',{id:job.id,offset:job.offset});
 const list=async()=>(await ok('purchase-data')).rows;let rows=await list();assert.equal(rows.length,fixture.count);assert.equal(rows.filter(p=>p.closeStatus==='手动关闭').length,fixture.closed);assert.equal(rows.filter(p=>p.auditStatus==='未审核').length,fixture.unapproved);assert(rows.every(p=>!p.balanceKnown));assert.equal(rows[0].sourceRow,4);assert.equal(rows.at(-1).sourceRow,fixture.count+3);assert.equal(rows.filter(p=>p.unit==='公斤').reduce((n,p)=>n+p.quantity,0).toFixed(4),fixture.kilograms);
 assert.equal((await preview()).id,job.id);assert.equal((await list()).length,fixture.count);pass('合成金蝶表完整保留；单位小数、关闭未审核状态及重复源行无损且重传不重复');
 assert.equal((await ok('purchase-data',undefined,sales)).rows.length,0);assert.equal((await call('purchase-save',{changes:[]},sales)).status,403);assert.equal((await call('purchase-history?id='+rows[0].id,undefined,sales)).status,403);pass('采购查询、历史、编辑均在服务端限制成员范围');
 let p=rows.find(r=>r.quantity>=100&&r.auditStatus==='已审核'&&r.closeStatus==='未关闭'),initial={...p};const get=async()=>p=(await list()).find(r=>r.id===p.id);
 const cell=(field,value,version=p.version)=>({changes:[{id:p.id,version,field,value}]});await ok('purchase-save',cell('promisedDate','2026-09-30'));await ok('purchase-save',cell('followupNote','采购电话核对'));await get();assert.equal(p.promisedDate,'2026-09-30');assert.equal(p.followupNote,'采购电话核对');assert.equal((await call('purchase-save',cell('followupNote','旧输入',initial.version))).status,409);assert.equal((await call('purchase-save',cell('promisedDate','2026-02-30'))).status,400);pass('采购单元格异字段合并、同字段冲突拦截，非法日期拒绝');
 const event=(type,quantity,extra={})=>({id:p.id,version:p.version,type,quantity,returnPending:0,date:'2026-09-17',reference:'单据-'+crypto.randomUUID(),note:'测试实收核对依据',token:crypto.randomUUID(),...extra});
 assert.equal((await call('purchase-receipt',event('receipt',1))).status,400);assert.equal((await call('purchase-archive',{items:[{id:p.id,version:p.version}],date:'2026-09-17',note:'不能未核对齐货'})).status,400);
 await ok('purchase-receipt',event('opening',40));await get();assert.equal(p.received,40);const receipt=event('receipt',20);await ok('purchase-receipt',receipt);await ok('purchase-receipt',receipt);await get();assert.equal(p.received,60);assert.equal((await call('purchase-receipt',{...event('receipt',20),reference:receipt.reference})).status,409);pass('先核对再收货；凭证去重与网络重试不重复消数，未齐不能存档');
 await ok('purchase-receipt',event('return',6));await get();assert.equal(p.received,54);assert.equal(p.returnPending,6);assert.equal((await call('purchase-receipt',event('replacement',7))).status,400);
 await ok('purchase-receipt',event('replacement',4));await get();assert.equal(p.received,58);assert.equal(p.returnPending,2);assert.equal((await call('purchase-receipt',event('receipt',p.quantity-p.received))).status,400);pass('退货减已收、补回减待补，剩余包含待补，普通收货不能冲掉待补');
 await ok('purchase-receipt',event('replacement',2));await get();await ok('purchase-receipt',event('receipt',p.quantity-p.received));await get();assert.equal(p.received,p.quantity);assert.equal(p.returnPending,0);
 await ok('purchase-archive',{items:[{id:p.id,version:p.version}],date:'2026-09-17',note:'已核对全部齐货'});await get();assert.equal(p.lifecycle,'archived');assert.equal((await call('purchase-save',cell('followupNote','不得修改档案'))).status,409);
 const exportRes=await call('purchase-export?'+new URLSearchParams({mode:'archived',supplier:p.supplier})),wb=XLSX.read(await exportRes.arrayBuffer());const data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);assert.equal(data.length,1);assert.equal(data[0]['供应商'],p.supplier);assert.equal(data[0]['已收数量（净合格）'],p.quantity);assert(wb.Sheets[wb.SheetNames[0]]['!autofilter']);
 await ok('purchase-receipt',event('return',3));await get();assert.equal(p.lifecycle,'active');assert.equal(p.returnPending,3);assert.equal(p.received,p.quantity-3);const history=await ok('purchase-history?id='+p.id);assert(history.edits.some(e=>e.action==='确认已齐货并存档'));pass('齐货后移入供应商档案、筛选导出保留数量，存档退货自动恢复跟进且留痕');
 const beforeRace=p.version,race=await Promise.all([call('purchase-receipt',event('return',1)),call('purchase-receipt',event('return',1))]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);await get();assert.equal(p.version,beforeRace+1);pass('两人同时登记同一采购明细，只有一笔原子写入成功');
 const book=XLSX.read(bytes);book.Sheets.sheet1.L4={t:'s',v:'第二版源备注'};const nextBytes=XLSX.write(book,{type:'buffer',bookType:'xlsx'});let update=await preview(nextBytes,'2026-09-18');assert.equal(update.summary.heldRows,fixture.ambiguousRows);assert.equal(update.summary.updateRows,fixture.uniqueRows);while(update.status!=='已完成')update=await ok('purchase-commit',{id:update.id,offset:update.offset});await get();assert.equal(p.followupNote,'采购电话核对');assert.equal(p.returnPending,4);assert.equal((await list()).length,fixture.count);pass('更新导出表保留网页复期与收退基数，多行歧义暂缓，未消失或重复新增');
 const sourceClosed=(await list()).find(r=>r.closeStatus==='手动关闭');assert.equal((await call('purchase-receipt',{...event('opening',0),id:sourceClosed.id,version:sourceClosed.version})).status,400);const unapproved=(await list()).find(r=>r.auditStatus==='未审核'&&r.closeStatus==='未关闭');assert.equal((await call('purchase-receipt',{...event('opening',0),id:unapproved.id,version:unapproved.version})).status,400);pass('金蝶手动关闭或未审核行保留查询，不能当成正常采购收货齐货');
}
