'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,Download,FileSpreadsheet,RefreshCw,UploadCloud,UsersRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input,Choice,Empty,type Act} from './ui';
import type {Data} from './workspace';
import {productTypeOf,readsAllOrders,type CustomerAccount,type Order} from '@/lib/domain';

type Side='sales'|'service'|'pmc';
const statusClass=(s:string)=>s.includes('退回')?'red':s.includes('待')?'amber':s.includes('已')||s==='生产中'?'green':'blue';
async function upload(action:string,file:File):Promise<{error?:string;count?:number;item?:unknown}>{const form=new FormData();form.set('file',file);const res=await fetch('/api/workspace/'+action,{method:'POST',body:form}),body=await res.json() as {error?:string;count?:number;item?:unknown};if(!res.ok)throw new Error(body.error||'上传失败');return body;}
function download(url:string){const a=document.createElement('a');a.href=url;a.click();}
const owns=(a:CustomerAccount|undefined,name:string,side:Side)=>!a||(side==='sales'?a.salesName:side==='service'?a.serviceName:a.pmcName).toLowerCase()===name.toLowerCase();

export function CollaborationPanel({side,data,act,busy,openOrder}:{side:Side;data:Data;act:Act;busy:boolean;openOrder:(o:Order)=>void}){
 const [q,setQ]=useState(''),[status,setStatus]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),accounts=data.customerAccounts||[],map=useMemo(()=>new Map(accounts.map(a=>[a.customer.toLowerCase(),a])),[accounts]),me=data.me;
 const rows=useMemo(()=>data.orders.filter(o=>{const a=map.get(o.customer.toLowerCase());return (readsAllOrders(me)||owns(a,me.name,side))&&(!q||[o.orderNo,o.customer,o.customerPO,o.drawing,productTypeOf(o)].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!status||(o.workflowStatus||'业务待提交')===status)}),[data.orders,map,q,status,me,side]);
 // eslint-disable-next-line prefer-const,@typescript-eslint/no-explicit-any
 const run=async(o:Order,action:string)=>{let note=action==='return-business'?prompt('请填写退回业务的原因：')||'':'';if(action==='return-business'&&!note)return;const body:any={id:o.id,version:o.version,action,note};if(action==='save-pmc'){body.productionStartDate=prompt('计划投产日（YYYY-MM-DD）：',o.productionStartDate||'')||'';body.productionFinishDate=prompt('计划完成日（YYYY-MM-DD）：',o.productionFinishDate||'')||'';body.materialStatus=prompt('物料齐套状态：',o.materialStatus||'待核对')||'';body.scheduleStatus=prompt('排期状态：',o.scheduleStatus||'已排期')||'';body.exceptionReason=prompt('异常原因（无异常可留空）：',o.exceptionReason||'')||'';body.promisedDate=prompt('可回复客户交期（YYYY-MM-DD）：',o.promisedDate||'')||'';}setSaving(true);try{await act('workflow',body);setNotice('交接状态已更新。');}finally{setSaving(false);}};
 const counts={all:rows.length,pending:rows.filter(o=>(o.workflowStatus||'').includes('待')).length,returned:rows.filter(o=>(o.workflowStatus||'').includes('退回')).length,scheduled:rows.filter(o=>o.workflowStatus==='PMC已排期').length};
 return <div className="collab-workspace"><section className={'collab-hero '+side}><div><span className="section-kicker">{side==='sales'?'SALES INTAKE':side==='service'?'CUSTOMER SERVICE REVIEW':'PMC HANDOFF'}</span><h2>{side==='sales'?'业务订单工作台':side==='service'?'客户服务工作台':'PMC 交接工作台'}</h2><p>{side==='sales'?'上传客户订单，补齐资料后交接给客服。':side==='service'?'审核订单和生产资料，齐套后提交 Candy / Tina 排期。':'Candy / Tina 接单后回填投产、完成、物料、异常和可回复交期。'}</p></div><div className="collab-flow"><span>{side==='sales'?'业务':side==='service'?'客服':'PMC'}</span><ArrowRight/><span>{side==='sales'?'客服':side==='service'?'PMC':'生产'}</span></div></section>
 {notice&&<div className="success mt-4">{notice}</div>}
 <section className="collab-metrics"><div><b>{counts.all}</b><span>可见订单</span></div><div><b>{counts.pending}</b><span>待处理</span></div><div><b>{counts.returned}</b><span>退回补充</span></div><div><b>{counts.scheduled}</b><span>PMC 已排期</span></div></section>
 <section className="panel section-pad mb-5"><div className="panel-title"><div><h3>工作入口</h3><p className="subtitle">Excel 导入后使用同一条订单记录交接，不重复建表。</p></div></div><div className="collab-actions">{side==='sales'&&<><Button onClick={()=>document.getElementById('business-order-file')?.click()}><UploadCloud/>上传订单 Excel</Button><input id="business-order-file" type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={()=>{setNotice('请在“上传与更新”中完成列映射和预览，系统会自动识别业务负责的客户。');}}/><Button variant="outline" onClick={()=>download('/imports')}><FileSpreadsheet/>进入导入页</Button></>}<Button variant="outline" onClick={()=>location.reload()}><RefreshCw/>刷新</Button></div></section>
 <section className="panel"><div className="panel-tools"><b>{side==='sales'?'业务订单':side==='service'?'客服审核队列':'PMC 交接队列'} <span className="muted">{rows.length} 条</span></b><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索客户、订单、PO、图号或产品类型"/><Choice label="状态" value={status} onChange={setStatus} options={[{value:'',label:'全部状态'},...['业务待提交','客服待审核','退回业务补充','PMC待接单','PMC已接单','PMC已排期'].map(v=>({value:v,label:v}))]}/></div><div className="order-table"><table><thead><tr><th>订单 / 客户</th><th>产品类型</th><th>图号·色号·镜片</th><th>数量</th><th>客户交期</th><th>责任链</th><th>当前状态</th><th>操作</th></tr></thead><tbody>{rows.length?rows.map(o=>{const a=map.get(o.customer.toLowerCase()),s=o.workflowStatus||'业务待提交';return <tr key={o.id}><td><button className="text-link" onClick={()=>openOrder(o)}><b>{o.orderNo}</b><span className="subline">{o.customer} · {o.customerPO||'无 PO'}</span></button></td><td><b>{productTypeOf(o)||'未填写'}</b></td><td>{o.drawing}<span className="subline">{o.color} · {o.lens}</span></td><td><b>{o.quantity.toLocaleString()}</b></td><td>{o.requestedDate||'待确认'}</td><td>{a?<><span>{a.salesName}</span><span className="subline">{a.serviceName} → {a.pmcName}</span></>:'未配置客户责任'}</td><td><span className={'pill '+statusClass(s)}>{s}</span></td><td><div className="row-actions"><Button size="sm" variant="outline" onClick={()=>openOrder(o)}>详情</Button>{side==='sales'&&['业务待提交','退回业务补充'].includes(s)&&<Button size="sm" disabled={busy||saving||!a} onClick={()=>run(o,'submit-service')}>提交客服</Button>}{side==='service'&&s==='客服待审核'&&<><Button size="sm" variant="outline" disabled={busy||saving} onClick={()=>run(o,'return-business')}>退回</Button><Button size="sm" disabled={busy||saving} onClick={()=>run(o,'submit-pmc')}>提交 PMC</Button></>}{side==='pmc'&&s==='PMC待接单'&&<Button size="sm" disabled={busy||saving} onClick={()=>run(o,'accept-pmc')}>接单</Button>}{side==='pmc'&&['PMC已接单','PMC已排期'].includes(s)&&<Button size="sm" disabled={busy||saving} onClick={()=>run(o,'save-pmc')}>回填排期</Button>}</div></td></tr>}):<tr><td colSpan={8}><Empty title="当前没有待处理订单" detail="请检查客户责任清单或导入新订单。"/></td></tr>}</tbody></table></div></section></div>;
}

export function CustomerMasterPanel({data,act,busy}:{data:Data;act:Act;busy:boolean}){
 const [file,setFile]=useState<File|null>(null),[kingdee,setKingdee]=useState<File|null>(null),[notice,setNotice]=useState(''),[edit,setEdit]=useState<Partial<CustomerAccount>>({active:true});const rows=data.customerAccounts||[],can=['admin','pmc'].includes(data.me.role);
 const save=async()=>{await act('customer-save',{id:edit.id,customer:edit.customer||'',customerCode:edit.customerCode||'',salesName:edit.salesName||'',serviceName:edit.serviceName||'',pmcName:edit.pmcName||'',notes:edit.notes||'',active:edit.active!==false});setEdit({active:true});};
 return <div className="collab-workspace"><section className="collab-hero master"><div><span className="section-kicker">CUSTOMER OWNERSHIP</span><h2>客户责任清单</h2><p>定义每个客户的业务、客服和 PMC 跟进人，驱动订单可见范围和交接权限。责任人变更仅管理员确认并操作；其他资料按原权限维护。</p></div><UsersRound size={52}/></section>{notice&&<div className="success mt-4">{notice}</div>}<section className="panel section-pad mb-5"><div className="collab-upload-grid"><div><h3>客户清单</h3><p className="subtitle">必须包含：客户、业务员、客服、PMC。非管理员导入时责任人必须与现有清单一致。</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="row-actions mt-3"><Button variant="outline" onClick={()=>download('/api/workspace/customer-template')}><Download/>下载模板</Button><Button disabled={!file||!can||busy} onClick={async()=>{if(!file)return;const r=await upload('customer-import',file);setNotice(`已导入 ${r.count} 个客户。`);location.reload();}}><UploadCloud/>上传并保存</Button></div></div><div><h3>金蝶订单模板</h3><p className="subtitle">上传你的标准模板后，PMC 已排期订单可生成导入表。</p><input type="file" accept=".xlsx,.xls" onChange={e=>setKingdee(e.target.files?.[0]||null)}/><div className="row-actions mt-3"><Button disabled={!kingdee||!can||busy} onClick={async()=>{if(!kingdee)return;await upload('kingdee-template',kingdee);setNotice('金蝶模板已保存。');location.reload();}}><UploadCloud/>保存金蝶模板</Button><Button variant="outline" disabled={!data.collaborationTemplates?.some(t=>t.templateType==='kingdee')} onClick={()=>download('/api/workspace/kingdee-export')}><FileSpreadsheet/>生成金蝶导入表</Button></div></div></div></section>
 <section className="panel section-pad mb-5"><h3 className="section-title">{edit.id?'修改客户责任':'新增客户'}</h3><div className="customer-form">{(['customer','customerCode','salesName','serviceName','pmcName','notes'] as const).map(k=><Input key={k} disabled={!can||(data.me.role!=='admin'&&['salesName','serviceName','pmcName'].includes(k))} value={String(edit[k]||'')} onChange={e=>setEdit(v=>({...v,[k]:e.target.value}))} placeholder={{customer:'客户名称',customerCode:'客户编码',salesName:'业务员（Jessie / Alice）',serviceName:'客服（Ivy / Nina）',pmcName:'PMC（Candy / Tina）',notes:'备注'}[k]}/>)}<Button disabled={!can||busy} onClick={save}><CheckCircle2/>保存</Button></div></section>
 <section className="panel"><div className="panel-tools"><b>客户分工 <span className="muted">{rows.length} 个客户</span></b></div><div className="order-table"><table><thead><tr><th>客户</th><th>客户编码</th><th>业务员</th><th>客服</th><th>PMC</th><th>备注</th><th></th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><b>{a.customer}</b></td><td>{a.customerCode||'—'}</td><td>{a.salesName}</td><td>{a.serviceName}</td><td>{a.pmcName}</td><td>{a.notes||'—'}</td><td><Button size="sm" variant="outline" disabled={!can} onClick={()=>setEdit(a)}>修改</Button></td></tr>)}</tbody></table></div></section></div>;
}
