'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,FileText,Languages,Plus,Printer,RefreshCw,Save,UploadCloud} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {clientId} from '@/lib/client-id';
import {Empty,dateTime} from './ui';
import type {Data} from './workspace';
import './customer-quotes.css';

type QuoteLine={id:string;model:string;descriptionZh:string;descriptionEn:string;quantity:number|string;unitPrice:number|string;toolingFee:number|string;sourceFormula?:string};
type QuoteTerm={id:string;labelZh:string;labelEn:string;zh:string;en:string;needsReview:boolean;reviewNote?:string};
type QuoteHistory={id:string;version:number;action:string;updatedAt:string;updatedBy:string;sourceFilename?:string;sourceHash?:string};
type QuoteCustomer={id:string;customer:string;customerCode:string};
type Quote={id?:string;version?:number;companyEn:string;companyZh:string;collectionEn?:string;collectionZh?:string;customerCode:string;customerName:string;customerAccountId:string|null;quoteNo:string;quoteDate:string;validUntil:string;currency:string;lines:QuoteLine[];terms:QuoteTerm[];reviewNotes:string[];canEdit?:boolean;sourceFilename?:string;sourceHash?:string;hasSource?:boolean;history?:QuoteHistory[];updatedAt?:string;updatedBy?:string};
type View='zh'|'en'|'both'|'edit';
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const newKey=()=>clientId();
const newLine=():QuoteLine=>({id:newKey(),model:'',descriptionZh:'',descriptionEn:'',quantity:'',unitPrice:'',toolingFee:''});
const termLabels=[['价格基础','Price basis'],['有效期','Validity'],['规格说明','Specification'],['模具费用','Tooling'],['其他数量','Other quantities'],['订单条款','Order terms']];
const newQuote=():Quote=>({companyEn:'',companyZh:'',collectionEn:'',collectionZh:'',customerCode:'',customerName:'',customerAccountId:null,quoteNo:'',quoteDate:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),validUntil:'',currency:'USD',lines:[newLine()],terms:termLabels.map(([labelZh,labelEn])=>({id:newKey(),labelZh,labelEn,zh:'',en:'',needsReview:true,reviewNote:''})),reviewNotes:[],canEdit:true});
const money=(value:number|string)=>value!==''&&Number.isFinite(Number(value))?Number(value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
function savePayload(q:Quote){return {id:q.id,version:q.version,companyEn:q.companyEn,companyZh:q.companyZh,collectionEn:q.collectionEn||'',collectionZh:q.collectionZh||'',customerCode:q.customerCode,customerName:q.customerName,customerAccountId:q.customerAccountId||null,quoteNo:q.quoteNo,quoteDate:q.quoteDate,validUntil:q.validUntil,currency:q.currency,lines:q.lines.map(l=>({...l,quantity:Number(l.quantity),unitPrice:Number(l.unitPrice),toolingFee:Number(l.toolingFee)})),terms:q.terms,reviewNotes:q.reviewNotes};}
class QuoteRequestError extends Error{constructor(message:string,readonly status:number){super(message);}}
async function quoteRequest(action:string,body?:unknown){
 let response:Response;try{response=await fetch('/api/workspace/'+action,{method:body===undefined?'GET':'POST',headers:body instanceof FormData||body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),cache:'no-store'});}catch{throw new Error('连接公司主机失败，输入已保留。请检查网络后重试。');}
 let result:any;try{result=await response.json();}catch{if([401,403].includes(response.status))throw new QuoteRequestError('登录状态或报价权限已失效。',response.status);throw new Error('服务器未返回完整结果，输入已保留。请稍后重试。');}
 if(!response.ok)throw new QuoteRequestError(response.status===409?'此报价已被其他同事更新。你的输入仍保留，请先记录修改，再点击“读取服务器版本”核对；不会覆盖他人的版本。':result.error||'操作未完成，请稍后重试。',response.status);return result;
}
function validate(q:Quote){
 if(!q.customerCode.trim()||!q.customerName.trim()||!q.quoteNo.trim())return '请填写客户编号、客户名称和报价单号。';
 if(!q.companyZh.trim()||!q.companyEn.trim())return '请填写中英文公司名称。';
 if(!/^\d{4}-\d{2}-\d{2}$/.test(q.quoteDate)||!/^\d{4}-\d{2}-\d{2}$/.test(q.validUntil)||q.validUntil<q.quoteDate)return '请填写正确的报价日期、有效期，且有效期不能早于报价日期。';
 if(!/^[A-Z]{3}$/.test(q.currency))return '币种请使用三个大写英文字母，例如 USD。';
 if(!q.lines.length)return '至少保留一项报价产品。';
 for(let i=0;i<q.lines.length;i++){const l=q.lines[i];if(!l.model.trim())return `第 ${i+1} 项需要填写型号。`;if(String(l.quantity).trim()===''||!Number.isSafeInteger(Number(l.quantity))||Number(l.quantity)<=0)return `第 ${i+1} 项订单数量必须为正整数。`;for(const key of ['unitPrice','toolingFee'] as const)if(String(l[key]).trim()===''||!Number.isFinite(Number(l[key]))||Number(l[key])<0)return `第 ${i+1} 项${key==='unitPrice'?'单价':'模具费'}必须为非负数字；免收请明确填写 0。`;}
 for(let i=0;i<q.terms.length;i++)if(!q.terms[i].labelZh.trim()||!q.terms[i].labelEn.trim())return `第 ${i+1} 项条款需要填写中英文标题。`;
 return '';
}

export function CustomerQuotePanel({data,onDirtyChange}:{data:Data;onDirtyChange?:(dirty:boolean)=>void}){
 const [quotes,setQuotes]=useState<Quote[]>([]),[customers,setCustomers]=useState<QuoteCustomer[]>([]),[draft,setDraft]=useState<Quote|null>(null),[baseline,setBaseline]=useState<Quote|null>(null),[canUse,setCanUse]=useState(false),[canCreate,setCanCreate]=useState(false),[allowUnbound,setAllowUnbound]=useState(false),[view,setView]=useState<View>('zh'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(baseline),editable=!!draft?.canEdit,changedBasis=!!draft&&!!baseline&&(draft.quoteDate!==baseline.quoteDate||draft.validUntil!==baseline.validUntil||draft.lines.some((l,i)=>String(l.quantity)!==String(baseline.lines[i]?.quantity)));
 const current=useRef({draft,dirty,busy});current.current={draft,dirty,busy};
 const alive=useRef(false),requestSequence=useRef(0),refreshRef=useRef<(discardDraft?:boolean,quiet?:boolean)=>Promise<void>>(async()=>{});
 const dirtyCallback=useRef(onDirtyChange);dirtyCallback.current=onDirtyChange;
 useEffect(()=>{dirtyCallback.current?.(dirty);},[dirty]);
 useEffect(()=>()=>dirtyCallback.current?.(false),[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{alive.current=true;requestSequence.current++;current.current={draft:null,dirty:false,busy:false};setDraft(null);setBaseline(null);setQuotes([]);setCustomers([]);setCanUse(false);setCanCreate(false);setAllowUnbound(false);setLoading(true);setBusy(false);setNotice('');setError('');void refreshRef.current(false,true);const timer=window.setInterval(()=>void refreshRef.current(false,true),30000),focus=()=>void refreshRef.current(false,true);window.addEventListener('focus',focus);return()=>{alive.current=false;requestSequence.current++;window.clearInterval(timer);window.removeEventListener('focus',focus);};},[data.me.id]);
 const put=(q:Quote|null)=>{current.current={...current.current,draft:q?copy(q):null,dirty:false};setDraft(q?copy(q):null);setBaseline(q?copy(q):null);};
 const clearScope=(message:string)=>{requestSequence.current++;setQuotes([]);setCustomers([]);setCanUse(false);setCanCreate(false);setAllowUnbound(false);put(null);setNotice('');setError(message);};
 const patch=(values:Partial<Quote>)=>{setDraft(q=>q?{...q,...values}:q);setNotice('');};
 const patchLine=(id:string,values:Partial<QuoteLine>)=>setDraft(q=>q?{...q,lines:q.lines.map(l=>l.id===id?{...l,...values}:l)}:q);
 const patchTerm=(id:string,values:Partial<QuoteTerm>)=>setDraft(q=>q?{...q,terms:q.terms.map(t=>t.id===id?{...t,...values}:t)}:q);
 const discard=()=>!dirty||window.confirm('当前报价有未保存修改。确定放弃这些修改吗？');
 const select=(q:Quote)=>{if(!discard())return;put(q);setError('');setNotice('');};
 const create=()=>{if(!canCreate||!discard())return;setBaseline(null);setDraft(newQuote());setView('edit');setError('');setNotice('新报价尚未保存。请先选择本人负责的客户，保存后仅该客户获授权的负责人可查看。');};
 const refresh=async(discardDraft=false,quiet=false)=>{if(quiet&&current.current.busy)return;if(discardDraft&&!discard())return;const sequence=++requestSequence.current;if(!quiet){setBusy(true);setError('');}try{const result=await quoteRequest('customer-quotes');if(!alive.current||sequence!==requestSequence.current)return;if(!result.canUse){clearScope('当前账号没有客户报价权限，页面中的报价内容已清除。');return;}const next:Quote[]=result.quotes||[],accounts:QuoteCustomer[]=result.customers||[];setQuotes(next);setCustomers(accounts);setCanUse(true);setCanCreate(!!result.canCreate);setAllowUnbound(!!result.canUseUnbound);const state=current.current,q=state.draft,found=q?.id?next.find(item=>item.id===q.id):undefined;const lostQuote=!!q?.id&&!found,lostCustomer=!!q?.customerAccountId&&!result.canUseUnbound&&!accounts.some(a=>a.id===q.customerAccountId),lostCreation=!!q&&!q.id&&!result.canCreate;if(lostQuote||lostCustomer||lostCreation){put(null);setNotice('');setError('客户责任或报价权限已变更，该报价及未保存的价格内容已从当前页面清除。');}else if(q?.id&&found){if(discardDraft||!state.dirty||!found.canEdit)put(found);if(!quiet)setNotice(state.dirty&&!discardDraft&&found.canEdit?'报价权限与列表已刷新，仍获授权的编辑内容保持不变。':'已读取当前授权范围内的服务器报价。');}else if(!q&&next[0])put(next[0]);else if(!quiet)setNotice('报价权限与本人负责的客户列表已刷新。');}catch(e){if(!alive.current||sequence!==requestSequence.current)return;if(e instanceof QuoteRequestError&&[401,403].includes(e.status))clearScope(e.message+' 页面中的报价内容已清除。');else setError((e as Error).message);}finally{if(alive.current){setLoading(false);if(!quiet)setBusy(false);}}};
 refreshRef.current=refresh;
 const acceptSaved=(q:Quote)=>{requestSequence.current++;put(q);setQuotes(old=>[q,...old.filter(item=>item.id!==q.id)]);};
 const actionError=(e:unknown)=>{if(e instanceof QuoteRequestError&&[401,403,404].includes(e.status)){clearScope(e.message+' 页面中的报价内容已清除，正在重新核对权限。');void refreshRef.current(false,false);}else setError((e as Error).message);};
 const beginAction=()=>{const sequence=++requestSequence.current;current.current.busy=true;setBusy(true);setError('');setNotice('');return sequence;};
 const finishAction=()=>{if(alive.current){current.current.busy=false;setBusy(false);}};
 const save=async()=>{if(!draft||!editable||!canUse)return;if(!allowUnbound&&!customers.some(a=>a.id===draft.customerAccountId)){setError('请从客户责任清单中选择本人负责的客户。');setView('edit');return;}const problem=validate(draft);if(problem){setError(problem);setView('edit');return;}const sequence=beginAction();try{const result=await quoteRequest('customer-quote-save',savePayload(draft));if(!alive.current||sequence!==requestSequence.current)return;acceptSaved(result.quote);setNotice(`已保存到协作中台 · 第 ${result.quote.version} 版。仍为待确认草稿，没有向客户发送。`);}catch(e){if(alive.current&&sequence===requestSequence.current)actionError(e);}finally{finishAction();}};
 const upload=async(file?:File)=>{if(!file||!draft?.id||!editable||!canUse)return;if(dirty){setError('请先保存当前草稿，再上传报价附件，避免版本相互覆盖。');return;}if(file.size>10*1024*1024){setError('附件不能超过 10 MB。');return;}const sequence=beginAction();try{const form=new FormData();form.set('quoteId',draft.id);form.set('version',String(draft.version));form.set('file',file);const result=await quoteRequest('customer-quote-upload',form);if(!alive.current||sequence!==requestSequence.current)return;acceptSaved(result.quote);setNotice('报价原文件已归档到本中台，并记录新版本。上传附件不会自动替换表格中的报价内容。');}catch(e){if(alive.current&&sequence===requestSequence.current)actionError(e);}finally{finishAction();}};
 const visible=quotes.filter(q=>[q.customerCode,q.customerName,q.quoteNo].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="customer-quote-panel">
  <section className="cq-intro cq-no-print"><div><span className="cq-eyebrow">CUSTOMER QUOTATIONS</span><h2>客户报价 · 同一份数据，双语呈现</h2><p>业务报价直接保存在现有协作中台。中文与英文共用型号、数量、单价和模具费，描述及条款逐项对照确认。</p></div><Languages aria-hidden="true" size={38}/></section>
  <div className="cq-draft-notice cq-no-print"><b>当前仅开放待确认草稿</b><span>不会自动发布或发送给客户；正式版本仍需负责人确认。原订单、生产记录和客户清单不受影响。</span></div>
  {error&&<div className="error cq-message cq-no-print" role="alert">{error}</div>}{notice&&<div className="success cq-message cq-no-print" role="status">{notice}</div>}
  <section className="panel cq-picker cq-no-print"><div className="cq-toolbar"><div><h3>客户报价档案 <span className="muted">{quotes.length} 份</span></h3><p>{allowUnbound?'管理员维护范围 · 未绑定报价不向普通员工开放':'按客户责任清单，仅查看和修改本人负责客户的报价'}</p></div><input className="cq-search" aria-label="搜索报价" placeholder="搜索客户编号、客户名称、报价单号" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outline" disabled={busy||loading} onClick={()=>void refresh()}><RefreshCw size={15}/>刷新列表</Button>{canCreate&&<Button disabled={busy||loading} onClick={create}><Plus size={16}/>新建报价草稿</Button>}</div>
   {loading?<p className="cq-placeholder">正在读取共享报价…</p>:visible.length?<div className="cq-list" aria-label="报价列表">{visible.map(q=><button key={q.id} className={'cq-list-item '+(draft?.id===q.id?'selected':'')} disabled={busy} onClick={()=>select(q)}><span><b>{q.customerCode} {q.customerName}</b><small>待确认 · 第 {q.version} 版</small></span><strong>{q.quoteNo}</strong><small>{q.quoteDate} · {q.lines.length} 款 · {q.currency}{q.canEdit?'':' · 只读'}</small></button>)}</div>:<p className="cq-placeholder">{search?'没有匹配的报价。':'暂无可查看的报价。获授权的业务同事可以新建草稿。'}</p>}
  </section>
  {draft?<>
   <div className="cq-actions cq-no-print"><div className="cq-tabs" role="tablist" aria-label="报价语言与编辑">{([['zh','中文版'],['en','English'],['both','中英对照'],['edit',editable?'编辑草稿':'查看详情']] as [View,string][]).map(([id,label])=><button type="button" role="tab" key={id} aria-selected={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div><div className="cq-action-buttons"><span className={'cq-save-state '+(dirty?'unsaved':'')}>{dirty?'有未保存修改':draft.id?`中台已存 · R${draft.version}`:'尚未保存'}</span>{draft.id&&<Button variant="outline" disabled={busy} onClick={()=>void refresh(true)}>读取服务器版本</Button>}<Button variant="outline" disabled={view==='edit'||busy} onClick={()=>window.print()}><Printer size={16}/>打印当前语言草稿</Button>{editable&&<Button disabled={busy||!dirty} onClick={()=>void save()}><Save size={16}/>{busy?'处理中…':'保存到中台'}</Button>}</div></div>
   {changedBasis&&<div className="cq-warning cq-no-print" role="status">数量或日期已修改，请同时核对对应的单价、有效期及报价条款。旧价格不会自动推算为其他数量的价格。</div>}
   {view==='edit'?<section className="panel cq-editor cq-no-print"><fieldset disabled={!editable||busy}><legend>报价基本资料</legend><div className="cq-form-grid">
    <Field label={allowUnbound?'关联客户清单（管理员可暂不关联）':'关联本人负责的客户（必选）'}><select disabled={!allowUnbound&&!!draft.id} value={draft.customerAccountId||''} onChange={e=>{const account=customers.find(a=>a.id===e.target.value);patch({customerAccountId:account?.id||null,...(account?{customerName:account.customer,customerCode:account.customerCode||''}:allowUnbound?{}:{customerName:'',customerCode:''})});}}><option value="" disabled={!allowUnbound}>{allowUnbound?'暂不关联 · 仅管理员维护':'请选择本人负责的客户'}</option>{customers.map(a=><option key={a.id} value={a.id}>{a.customerCode||'未设编号'} · {a.customer}</option>)}</select></Field>
    <Field label="客户编号"><input readOnly={!allowUnbound||!!draft.customerAccountId} value={draft.customerCode} onChange={e=>patch({customerCode:e.target.value})}/></Field>
    <Field label="客户名称"><input readOnly={!allowUnbound||!!draft.customerAccountId} value={draft.customerName} onChange={e=>patch({customerName:e.target.value})}/></Field>
    <Field label="报价单号"><input value={draft.quoteNo} onChange={e=>patch({quoteNo:e.target.value})}/></Field>
    <Field label="报价日期"><input type="date" value={draft.quoteDate} onChange={e=>patch({quoteDate:e.target.value})}/></Field>
    <Field label="有效期至"><input type="date" value={draft.validUntil} onChange={e=>patch({validUntil:e.target.value})}/></Field>
    <Field label="币种"><input value={draft.currency} maxLength={3} onChange={e=>patch({currency:e.target.value.toUpperCase()})}/></Field>
    <Field label="公司名称 · 中文"><input value={draft.companyZh} onChange={e=>patch({companyZh:e.target.value})}/></Field>
    <Field label="Company name · English"><input value={draft.companyEn} onChange={e=>patch({companyEn:e.target.value})}/></Field>
    <Field label="系列名称 · 中文"><input value={draft.collectionZh||''} onChange={e=>patch({collectionZh:e.target.value})}/></Field>
    <Field label="Collection · English"><input value={draft.collectionEn||''} onChange={e=>patch({collectionEn:e.target.value})}/></Field>
   </div><p className="cq-help">客户名称和编号随客户责任清单带入，不能手填其他客户来扩大查看范围。客户编号未设置时，请由管理员在客户责任清单补齐。</p><div className="cq-section-heading"><h3>产品与费用</h3><Button type="button" variant="outline" onClick={()=>patch({lines:[...draft.lines,newLine()]})}><Plus size={15}/>增加产品</Button></div><p className="cq-help">数量为每款订单数量，不等同于最低起订量。单价与模具费分列；金额为 0 时请明确填写 0。</p>
   {draft.lines.map((line,index)=><div className="cq-line-editor" key={line.id}><div className="cq-section-heading"><b>产品 {index+1}</b><Button type="button" size="sm" variant="ghost" disabled={draft.lines.length===1} onClick={()=>{if(window.confirm(`从当前草稿移除第 ${index+1} 项？保存后会形成新版本，历史版本仍保留。`))patch({lines:draft.lines.filter(l=>l.id!==line.id)});}}>移除此项</Button></div><div className="cq-line-numbers"><Field label={`型号 · 第 ${index+1} 项`}><input value={line.model} onChange={e=>patchLine(line.id,{model:e.target.value})}/></Field><Field label={`订单数量 · 第 ${index+1} 项`}><input type="number" min="1" step="1" value={line.quantity} onChange={e=>patchLine(line.id,{quantity:e.target.value})}/></Field><Field label={`单价 (${draft.currency}/件) · 第 ${index+1} 项`}><input type="number" min="0" step="0.01" value={line.unitPrice} onChange={e=>patchLine(line.id,{unitPrice:e.target.value})}/></Field><Field label={`模具费 (${draft.currency}/款) · 第 ${index+1} 项`}><input type="number" min="0" step="0.01" value={line.toolingFee} onChange={e=>patchLine(line.id,{toolingFee:e.target.value})}/></Field></div><div className="cq-paired"><Field label={`产品描述 · 中文 · 第 ${index+1} 项`}><textarea rows={3} value={line.descriptionZh} onChange={e=>patchLine(line.id,{descriptionZh:e.target.value})}/></Field><Field label={`Product description · English · 第 ${index+1} 项`}><textarea rows={3} value={line.descriptionEn} onChange={e=>patchLine(line.id,{descriptionEn:e.target.value})}/></Field></div>{line.sourceFormula&&<small className="cq-help">原文件模具费公式（溯源，不自动执行）：{line.sourceFormula}</small>}</div>)}
   <div className="cq-section-heading"><h3>双语条款</h3><Button type="button" variant="outline" onClick={()=>patch({terms:[...draft.terms,{id:newKey(),labelZh:'',labelEn:'',zh:'',en:'',needsReview:true,reviewNote:''}]})}><Plus size={15}/>增加条款</Button></div><p className="cq-help">中英文必须表达同一条件。系统不会自动补写付款方式、交期或折扣依据。</p>
   {draft.terms.map((term,index)=><div className="cq-term-editor" key={term.id}><div className="cq-paired"><Field label={`条款标题 · 中文 · 第 ${index+1} 项`}><input value={term.labelZh} onChange={e=>patchTerm(term.id,{labelZh:e.target.value})}/></Field><Field label={`Term title · English · 第 ${index+1} 项`}><input value={term.labelEn} onChange={e=>patchTerm(term.id,{labelEn:e.target.value})}/></Field><Field label={`条款内容 · 中文 · 第 ${index+1} 项`}><textarea rows={3} value={term.zh} onChange={e=>patchTerm(term.id,{zh:e.target.value})}/></Field><Field label={`Term text · English · 第 ${index+1} 项`}><textarea rows={3} value={term.en} onChange={e=>patchTerm(term.id,{en:e.target.value})}/></Field></div><div className="cq-term-review"><label><input type="checkbox" checked={term.needsReview} onChange={e=>patchTerm(term.id,{needsReview:e.target.checked})}/>该条款仍需确认</label><input aria-label={`条款内部核对说明 · 第 ${index+1} 项`} placeholder="内部核对说明（不打印）" value={term.reviewNote||''} onChange={e=>patchTerm(term.id,{reviewNote:e.target.value})}/><Button type="button" size="sm" variant="ghost" onClick={()=>{if(window.confirm('从当前草稿移除此条款？'))patch({terms:draft.terms.filter(t=>t.id!==term.id)});}}>移除条款</Button></div></div>)}
   <Field label="内部待确认事项（每行一项，不打印）"><textarea rows={3} value={draft.reviewNotes.join('\n')} onChange={e=>patch({reviewNotes:e.target.value.split('\n')})}/></Field>
   </fieldset><div className="cq-editor-footer"><p>保存只新增报价版本，不修改客户清单、订单或生产数据。数量、日期、价格变动后，请再次核对双语条款。</p>{editable&&<Button disabled={busy||!dirty} onClick={()=>void save()}><Save size={16}/>保存报价草稿</Button>}</div></section>:<QuoteDocument quote={draft} view={view}/>}
   <section className="panel cq-support cq-no-print"><div className="cq-section-heading"><div><h3><FileText size={17}/> 原始附件与修改记录</h3><p className="cq-help">所有附件和保存版本归档于此中台；不创建另一套工作台。</p></div>{draft.hasSource&&draft.id&&<Button variant="outline" asChild><a href={'/api/workspace/customer-quote-file?id='+encodeURIComponent(draft.id)}><Download size={16}/>下载报价原文件</a></Button>}</div>
    <div className="cq-source"><div><b>{draft.sourceFilename||'尚未上传报价原文件'}</b>{draft.sourceHash&&<code title={draft.sourceHash}>SHA-256 · {draft.sourceHash}</code>}<p>附件是归档原件，不会随在线字段修改而变化。当前支持双语网页打印，暂不提供修改后 Excel 自动生成。</p></div>{editable&&<label className={'cq-upload '+(!draft.id||busy||dirty?'disabled':'')}><UploadCloud size={17}/>{draft.hasSource?'上传新附件版本':'上传报价原文件'}<input type="file" accept=".xlsx,.xls,.pdf" disabled={!draft.id||busy||dirty} onChange={e=>{const file=e.target.files?.[0];e.target.value='';void upload(file);}}/></label>}</div>{editable&&(!draft.id||dirty)&&<p className="cq-help">请先保存草稿，再上传附件。新附件留存新版本，不会清除旧版本历史。</p>}
    {(draft.reviewNotes.some(Boolean)||draft.terms.some(t=>t.needsReview))&&<div className="cq-review"><b>内部待确认</b><ul>{draft.reviewNotes.filter(Boolean).map((text,i)=><li key={i}>{text}</li>)}{draft.terms.filter(t=>t.needsReview).map(t=><li key={t.id}>{t.labelZh||t.labelEn||'未命名条款'}：{t.reviewNote||'请核对中英文表述并确认。'}</li>)}</ul></div>}
    <details className="cq-history"><summary>查看保存记录 · {draft.history?.length||0} 条</summary>{draft.history?.length?<div className="cq-history-table"><table><thead><tr><th>版本</th><th>操作</th><th>操作人</th><th>时间</th><th>原文件</th></tr></thead><tbody>{draft.history.map(h=><tr key={h.id}><td>R{h.version}</td><td>{h.action}</td><td>{h.updatedBy}</td><td>{dateTime(h.updatedAt)}</td><td>{h.sourceFilename||'—'}</td></tr>)}</tbody></table></div>:<p className="cq-help">尚无历史记录，保存后自动留痕。</p>}</details>
   </section>
  </>:!loading&&<section className="panel cq-no-print"><Empty title={canUse?'选择或新建一份客户报价':'当前账号没有客户报价权限'} detail={canUse?'只有客户责任清单中本人负责的客户会出现在选择列表中。责任关系变更后，页面会重新核对权限。':'请联系管理员核对报价权限名单及客户责任清单；不会开放其他同事负责客户的报价。'}/></section>}
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="cq-field"><span>{label}</span>{children}</label>;}
function QuoteDocument({quote:q,view}:{quote:Quote;view:Exclude<View,'edit'>}){
 const en=view==='en',both=view==='both',text=(zh:string,english:string)=>both?<><span lang="zh-CN">{zh||'待填写'}</span><span className="cq-english" lang="en">{english||'To be completed'}</span></>:en?(english||'To be completed'):(zh||'待填写');
 return <article className={'cq-document cq-language-'+view} aria-label="报价单预览"><header className="cq-document-header"><div className="cq-logo">DOON<span>EYEWEAR</span></div><div className="cq-company"><h2>{text(q.companyZh,q.companyEn)}</h2>{(q.collectionZh||q.collectionEn)&&<p>{text(q.collectionZh||'',q.collectionEn||'')}</p>}</div><span className="cq-draft-stamp">DRAFT<br/>待确认草稿</span></header><div className="cq-document-title"><h3>{en?'QUOTATION':both?'报 价 单 / QUOTATION':'报 价 单'}</h3><b>{q.quoteNo||'—'}</b></div><dl className="cq-metadata"><div><dt>{en?'Customer':'客户编号 / Customer'}</dt><dd>{q.customerCode||'—'}{q.customerName&&<span className="cq-client-name">{q.customerName}</span>}</dd></div><div><dt>{en?'Date':'报价日期 / Date'}</dt><dd>{q.quoteDate||'—'}</dd></div><div><dt>{en?'Currency':'币种 / Currency'}</dt><dd>{q.currency||'—'}</dd></div><div><dt>{en?'Valid until':'有效期至 / Valid until'}</dt><dd>{q.validUntil||'—'}</dd></div></dl>
  <div className="cq-document-scroll"><table className="cq-products"><thead><tr><th>{text('序号','No.')}</th><th>{text('型号','Model No.')}</th><th>{text('产品描述','Product description')}</th><th>{text('订单数量（件/款）','Order quantity (pcs/model)')}</th><th>{text(`单价（${q.currency}/件）`,`Unit price (${q.currency}/pc)`)}</th><th>{text(`模具费（${q.currency}/款）`,`Tooling fee (${q.currency}/model)`)}</th></tr></thead><tbody>{q.lines.map((line,index)=><tr key={line.id}><td>{index+1}</td><td><b>{line.model||'—'}</b></td><td className="cq-description">{text(line.descriptionZh,line.descriptionEn)}</td><td>{String(line.quantity).trim()||'—'}</td><td>{money(line.unitPrice)}</td><td>{money(line.toolingFee)}</td></tr>)}</tbody></table></div>
  <section className="cq-terms"><h4>{en?'Notes & terms':both?'说明与条款 / Notes & terms':'说明与条款'}</h4>{q.terms.map(term=><div key={term.id} className={'cq-term '+(term.needsReview?'review':'')}><b>{text(term.labelZh,term.labelEn)}</b><p>{text(term.zh,term.en)}{term.needsReview&&<small className="cq-review-tag">{en?'Pending review':'待确认 / Pending review'}</small>}</p></div>)}</section><footer className="cq-document-footer"><span>{en?'DRAFT — Subject to final confirmation. Not an approved quotation.':'待确认草稿 — 须经最终确认，不作为正式报价。'}</span><span>{q.id?`R${q.version}`:'UNSAVED'}</span></footer>
 </article>;
}
