'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,FileText,RefreshCw,Search} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Data} from './workspace';
import './customer-price-archive.css';

type Ref={fileId:string;archiveId:string;filename:string;sheet?:string;cell?:string;page?:number;hasFile:boolean;canDownload:boolean};
type Price={id:string;scope:string;documentType:string;documentNo?:string;version?:string;documentDate?:string;currency?:string;unit?:string;configuration?:string;lensVariant?:string;invoiceKind?:string;quantity:number|null;quantityMin:number|null;quantityMax:number|null;quantityBasis?:string;unitPrice:number|null;toolingFee:number|null;otherCharges:unknown;terms?:string;reviewStatus:string;sentStatus:string;sourceRefs:Ref[];priceBasis?:string;conflict?:boolean;applicabilityUnknown?:boolean};
type Product={id:string;factoryModel?:string;customerModel?:string;productName?:string;productType?:string;sku?:string;frameColor?:string;lens?:string;material?:string;size?:string;specVersion?:string;activity?:string;sourceRefs:Ref[]};
type Row={id:string;customerAccountId:string;customer:string;customerCode:string;product:Product;basis:Price|null;bases:Price[];history:Price[];status:string;issues:string[]};
type Result={customers:{id:string;customer:string;customerCode:string}[];rows:Row[];summary:{products:number;skus:number;verified:number;needsReview:number;missingPrice:number};canSeeInternal:boolean};
const statuses:Record<string,string>={verified:'已核对',needs_review:'待核对',missing_price:'缺少销售价'};
const documents:Record<string,string>={invoice:'INVOICE 依据',quote:'报价历史',order:'订单价格',internal:'内部核价',charge:'费用记录'};
const value=(v:unknown)=>v==null||v===''?'—':String(v);
const condition=(p:Price)=>[p.quantity!=null?`原单数量 ${p.quantity}`:'',p.quantityMin!=null?`下限 ${p.quantityMin}`:'',p.quantityMax!=null?`上限 ${p.quantityMax}`:'',p.quantityBasis&&p.quantityBasis!=='unknown'?p.quantityBasis:'数量条件待核对'].filter(Boolean).join(' · ');
function Sources({refs}:{refs:Ref[]}){return <div className="cpa-sources">{refs.map((r,i)=><span key={r.archiveId+':'+r.fileId+':'+i}>{[r.filename,r.sheet,r.cell,r.page?`第 ${r.page} 页`:''].filter(Boolean).join(' · ')}{r.canDownload?<a href={'/api/workspace/customer-price-archive-file?archiveId='+encodeURIComponent(r.archiveId)+'&fileId='+encodeURIComponent(r.fileId)}>下载原件</a>:<small>{r.hasFile?'原件受限':'原件位置记录'}</small>}</span>)}</div>;}
function PriceDetail({price}:{price:Price}){return <div className="cpa-price-detail"><div><b>{price.priceBasis||documents[price.documentType]}</b><span className={'cpa-state '+price.reviewStatus}>{statuses[price.reviewStatus]}</span>{price.conflict&&<span className="cpa-state needs_review">同条件价格冲突</span>}</div><strong>{price.unitPrice==null?'价格待核对':`${price.currency||'币种待核对'} ${price.unitPrice} / ${price.unit||'单位待核对'}`}</strong><p>本条价格镜片：{value(price.lensVariant)}</p><p>{price.configuration&&'配置 '+price.configuration+' · '}{price.invoiceKind&&'单据类型 '+price.invoiceKind+' · '}{condition(price)} · {price.scope==='model'?'款级价，不能自动套用全部 SKU':'SKU 价格'}</p><p>{value(price.documentNo)} · {value(price.documentDate)} · 源版本 {value(price.version)}</p><p>模具费 {value(price.toolingFee)} · 其他费用 {price.otherCharges==null?'—':typeof price.otherCharges==='object'?JSON.stringify(price.otherCharges):String(price.otherCharges)}</p>{price.terms&&<p>适用条款：{price.terms}</p>}<p>发送事实：{price.sentStatus==='sent'?'有已发送标记':'未知'}{price.documentType==='invoice'?'；INVOICE 作为查询依据，不能据此认定报价已发送':''}</p><Sources refs={price.sourceRefs}/></div>;}
export function CustomerPriceArchivePanel({data}:{data:Data}){
 const [customerId,setCustomerId]=useState(()=>typeof window==='undefined'?'':new URLSearchParams(location.search).get('customerId')||''),[q,setQ]=useState(''),[state,setState]=useState('all'),[currency,setCurrency]=useState(''),[page,setPage]=useState(0),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const sequence=useRef(0);
 const params=new URLSearchParams({customerId,q,state,currency}).toString();
 useEffect(()=>{const seq=++sequence.current,controller=new AbortController();setLoading(true);setError('');setResult(null);setPage(0);const timer=setTimeout(async()=>{try{const response=await fetch('/api/workspace/customer-price-archive?'+params,{cache:'no-store',signal:controller.signal}),body=await response.json() as Result&{error?:string};if(!response.ok)throw new Error(body.error||'无法读取客户报价档案');if(sequence.current===seq)setResult(body);}catch(e){if(sequence.current===seq&&!controller.signal.aborted){setResult(null);setError((e as Error).message);}}finally{if(sequence.current===seq)setLoading(false);}},180);return()=>{clearTimeout(timer);controller.abort();};},[params,data.me.id,data.revision,refresh]);
 useEffect(()=>{const renew=()=>setRefresh(n=>n+1),timer=setInterval(renew,30000);addEventListener('focus',renew);return()=>{clearInterval(timer);removeEventListener('focus',renew);};},[]);
 if(!data.customerQuoteAccess)return <section className="panel section-pad"><h2>当前账号没有客户报价档案权限</h2><p>请由管理员核对独立报价授权和客户责任关系。</p></section>;
 const rows=result?.rows||[],totalPages=Math.max(1,Math.ceil(rows.length/25));
 return <div className="cpa"><section className="panel section-pad cpa-intro"><div><span className="eyebrow">CUSTOMER PRICE ARCHIVE</span><h2>款式 / SKU 历史报价档案</h2><p>匹配产品后优先采用 INVOICE 作为价格依据，仍保留全部报价历史。每条价格的镜片、原币、单位、数量条件及条款分别列出；未核对价格不会自动发布。</p></div><FileText size={38}/></section>
 <section className="panel section-pad"><div className="cpa-filters"><label>客户<select aria-label="报价档案客户" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">本人授权的全部客户</option>{result?.customers.map(c=><option key={c.id} value={c.id}>{c.customerCode||'未设编码'} · {c.customer}</option>)}</select></label><label><Search size={14}/> 款式 / SKU<input aria-label="报价档案搜索" value={q} onChange={e=>setQ(e.target.value)} placeholder="工厂款号、客款号、SKU、框色或镜片"/></label><label>资料状态<select aria-label="报价档案状态" value={state} onChange={e=>setState(e.target.value)}><option value="all">全部</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>原币<input aria-label="报价档案币种" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} placeholder="例如 USD" maxLength={3}/></label><Button variant="outline" onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={15}/>刷新</Button><Button variant="outline" disabled={loading||!rows.length} asChild><a href={'/api/workspace/customer-price-archive-export?'+params}><Download size={15}/>导出当前范围 Excel</a></Button></div>{error&&<div className="error" role="alert">{error}</div>}</section>
 {result&&<section className="cpa-metrics">{[['产品记录',result.summary.products],['明确 SKU',result.summary.skus],['已核对',result.summary.verified],['待核对',result.summary.needsReview],['缺销售价',result.summary.missingPrice]].map(([label,n])=><div key={label}><b>{n}</b><span>{label}</span></div>)}</section>}
 <section className="panel section-pad"><p className="cpa-help">数量不同的 INVOICE 与报价阶梯同时展示，不能把一个条件的价格当作通用售价。缺失 SKU、镜片或规格信息须复核；款级记录不代表全部 SKU 已有价格。发送事实与价格核对分开记录。</p>{loading?<p role="status">正在读取本人授权范围…</p>:!rows.length?<p>当前范围暂无历史档案。已有产品但缺价格的记录将单列为“缺少销售价”。</p>:<div className="cpa-rows">{rows.slice(page*25,(page+1)*25).map(row=><article className="cpa-row" key={row.id}><div className="cpa-row-head"><div><small>{row.customerCode} · {row.customer}</small><h3>{value(row.product.factoryModel)} <span>客款 {value(row.product.customerModel)}</span></h3><p><b>{row.product.sku||'尚未明确 SKU'}</b> · {value(row.product.productName)}</p><p>类别 {value(row.product.productType)} · 框色 {value(row.product.frameColor)} · 镜片 {value(row.product.lens)} · 材质 {value(row.product.material)} · 尺寸 {value(row.product.size)} · 规格 {value(row.product.specVersion)}</p></div><span className={'cpa-state '+row.status}>{statuses[row.status]}</span></div><div className="cpa-bases">{row.bases.length?row.bases.map(p=><PriceDetail key={p.id} price={p}/>):<p>缺少可追溯销售价，未填 0，也未用内部核价替代。</p>}</div>{row.issues.map((issue,i)=><p className="cpa-issue" key={i}>{issue}</p>)}<details><summary>价格历史与来源 · {row.history.length} 条</summary>{row.history.map(p=><PriceDetail key={p.id} price={p}/>)}<Sources refs={row.product.sourceRefs}/></details></article>)}</div>}<div className="cpa-pagination"><span>第 {page+1} / {totalPages} 页 · {rows.length} 条</span><Button variant="outline" size="sm" disabled={!page} onClick={()=>setPage(p=>p-1)}>上一页</Button><Button variant="outline" size="sm" disabled={page+1>=totalPages} onClick={()=>setPage(p=>p+1)}>下一页</Button></div></section></div>;
}
