'use client';
import {cloneElement,isValidElement,useEffect,useId,useRef,useState} from 'react';
import {Download,FileText,Languages,PencilLine,Plus,Printer,RefreshCw,Save,UploadCloud} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {CompanyLogo} from '@/components/company-logo';
import {clientId} from '@/lib/client-id';
import {Empty,dateTime} from './ui';
import type {Data} from './workspace';
import './customer-quotes.css';

type NumericDraft=number|string|null;
type QuoteLine={id:string;model:string;descriptionZh:string;descriptionEn:string;quantity:NumericDraft;quantityBasisZh?:string;quantityBasisEn?:string;unitPrice:NumericDraft;toolingFee:NumericDraft;sourceFormula?:string};
type QuoteCharge={id:string;labelZh:string;labelEn:string;amount:NumericDraft;basisZh:string;basisEn:string;conditional?:boolean;needsReview?:boolean};
type InternalCost={id:string;label:string;rmb:NumericDraft;notes:string};
type QuoteTerm={id:string;labelZh:string;labelEn:string;zh:string;en:string;needsReview:boolean;reviewNote?:string};
type QuoteHistory={id:string;version:number;action:string;updatedAt:string;updatedBy:string;sourceFilename?:string;sourceHash?:string};
type QuoteCustomer={id:string;customer:string;customerCode:string};
type Quote={id?:string;version?:number;status?:'draft'|'confirmed';companyEn:string;companyZh:string;collectionEn?:string;collectionZh?:string;customerCode:string;customerName:string;customerAccountId:string|null;contactName?:string;quoteNo:string;quoteDate:string;validUntil:string;currency:string;lines:QuoteLine[];customerCharges?:QuoteCharge[];internalNotesZh?:string;exchangeRateCnyPerUsd?:NumericDraft;internalCosts?:InternalCost[];terms:QuoteTerm[];reviewNotes:string[];canEdit?:boolean;canConfirm?:boolean;canRevise?:boolean;confirmedAt?:string;confirmedBy?:string;sourceFilename?:string;sourceHash?:string;hasSource?:boolean;history?:QuoteHistory[];updatedAt?:string;updatedBy?:string};
type CompletedQuote={id:string;quoteId:string;quoteVersion:number;quoteNo:string;customerCode:string;customerName:string;model:string;descriptionZh:string;unitPriceUsd:number;quantity:number;confirmedAt:string;quotedCustomer:''|'Y'};
type View='zh'|'en'|'both'|'edit';
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const newKey=()=>clientId();
const newLine=():QuoteLine=>({id:newKey(),model:'',descriptionZh:'',descriptionEn:'',quantity:'',unitPrice:'',toolingFee:''});
const termLabels=[['价格基础','Price basis'],['有效期','Validity'],['规格说明','Specification'],['模具费用','Tooling'],['其他数量','Other quantities'],['订单条款','Order terms']];
const newQuote=():Quote=>({companyEn:'',companyZh:'',collectionEn:'',collectionZh:'',customerCode:'',customerName:'',customerAccountId:null,quoteNo:'',quoteDate:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),validUntil:'',currency:'USD',lines:[newLine()],terms:termLabels.map(([labelZh,labelEn])=>({id:newKey(),labelZh,labelEn,zh:'',en:'',needsReview:true,reviewNote:''})),reviewNotes:[],canEdit:true});
const isBlank=(value:NumericDraft|undefined)=>value==null||String(value).trim()==='';
const numeric=(value:NumericDraft|undefined)=>isBlank(value)?null:Number(value);
const money=(value:NumericDraft|undefined)=>!isBlank(value)&&Number.isFinite(Number(value))?Number(value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
function savePayload(q:Quote){return {id:q.id,version:q.version,companyEn:q.companyEn,companyZh:q.companyZh,collectionEn:q.collectionEn||'',collectionZh:q.collectionZh||'',customerCode:q.customerCode,customerName:q.customerName,customerAccountId:q.customerAccountId||null,contactName:q.contactName||'',quoteNo:q.quoteNo,quoteDate:q.quoteDate,validUntil:q.validUntil,currency:q.currency,internalNotesZh:q.internalNotesZh||'',exchangeRateCnyPerUsd:numeric(q.exchangeRateCnyPerUsd),internalCosts:(q.internalCosts||[]).map(c=>({...c,rmb:numeric(c.rmb)})),customerCharges:(q.customerCharges||[]).map(c=>({...c,amount:numeric(c.amount)})),lines:q.lines.map(l=>({...l,quantity:numeric(l.quantity),unitPrice:numeric(l.unitPrice),toolingFee:numeric(l.toolingFee)})),terms:q.terms,reviewNotes:q.reviewNotes};}
class QuoteRequestError extends Error{constructor(message:string,readonly status:number){super(message);}}
async function quoteRequest(action:string,body?:unknown){
 let response:Response;try{response=await fetch('/api/workspace/'+action,{method:body===undefined?'GET':'POST',headers:body instanceof FormData||body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),cache:'no-store'});}catch{throw new Error('连接公司主机失败，输入已保留。请检查网络后重试。');}
 let result:any;try{result=await response.json();}catch{if([401,403].includes(response.status))throw new QuoteRequestError('登录状态或报价权限已失效。',response.status);throw new Error('服务器未返回完整结果，输入已保留。请稍后重试。');}
 if(!response.ok)throw new QuoteRequestError(response.status===409?'此报价已被其他同事更新。你的输入仍保留，请先记录修改，再点击“读取服务器版本”核对；不会覆盖他人的版本。':result.error||'操作未完成，请稍后重试。',response.status);return result;
}
function validate(q:Quote){
 if(!q.customerName.trim()||!q.quoteNo.trim())return '请填写客户名称和报价单号；新客户可暂不填写客户编号。';
 if(!q.companyZh.trim()||!q.companyEn.trim())return '请填写中英文公司名称。';
 if(!/^\d{4}-\d{2}-\d{2}$/.test(q.quoteDate)||(q.validUntil&&(!/^\d{4}-\d{2}-\d{2}$/.test(q.validUntil)||q.validUntil<q.quoteDate)))return '请填写正确的报价日期；有效期可暂留空，填写时不能早于报价日期。';
 if(!/^[A-Z]{3}$/.test(q.currency))return '币种请使用三个大写英文字母，例如 USD。';
 if(!q.lines.length)return '至少保留一项报价产品。';
 for(let i=0;i<q.lines.length;i++){const l=q.lines[i];if(!l.model.trim())return `第 ${i+1} 项需要填写型号或临时款名。`;if(!isBlank(l.quantity)&&(!Number.isSafeInteger(Number(l.quantity))||Number(l.quantity)<=0))return `第 ${i+1} 项数量应为正整数，未确认时请留空。`;for(const key of ['unitPrice','toolingFee'] as const)if(!isBlank(l[key])&&(!Number.isFinite(Number(l[key]))||Number(l[key])<0))return `第 ${i+1} 项${key==='unitPrice'?'单价':'模具费'}应为非负数字；免收请明确填写 0，待确认请留空。`;}
 if(!isBlank(q.exchangeRateCnyPerUsd)&&(!Number.isFinite(Number(q.exchangeRateCnyPerUsd))||Number(q.exchangeRateCnyPerUsd)<=0))return '参考汇率应为正数。';
 for(const c of q.customerCharges||[]){if(!c.labelZh.trim()||!c.labelEn.trim())return '附加费用需要中英文名称。';if(!isBlank(c.amount)&&(!Number.isFinite(Number(c.amount))||Number(c.amount)<0))return '附加费用应为非负数字或留空待确认。';}
 for(const c of q.internalCosts||[]){if(!c.label.trim()||isBlank(c.rmb)||!Number.isFinite(Number(c.rmb))||Number(c.rmb)<0)return '内部成本参考需要名称及明确的人民币金额。';}
 for(let i=0;i<q.terms.length;i++)if(!q.terms[i].labelZh.trim()||!q.terms[i].labelEn.trim())return `第 ${i+1} 项条款需要填写中英文标题。`;
 return '';
}

export function CustomerQuotePanel({data,onDirtyChange}:{data:Data;onDirtyChange?:(dirty:boolean)=>void}){
 const [completed,setCompleted]=useState<CompletedQuote[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[customers,setCustomers]=useState<QuoteCustomer[]>([]),[draft,setDraft]=useState<Quote|null>(null),[baseline,setBaseline]=useState<Quote|null>(null),[canUse,setCanUse]=useState(false),[canCreate,setCanCreate]=useState(false),[allowUnbound,setAllowUnbound]=useState(false),[view,setView]=useState<View>('zh'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const dirty=!!draft&&(!baseline||JSON.stringify(savePayload(draft))!==JSON.stringify(savePayload(baseline))),editable=!!draft?.canEdit,changedBasis=!!draft&&!!baseline&&(draft.quoteDate!==baseline.quoteDate||draft.validUntil!==baseline.validUntil||draft.lines.some((l,i)=>String(l.quantity)!==String(baseline.lines[i]?.quantity)));
 const editorRef=useRef<HTMLElement|null>(null);
 const openEditor=()=>{setView('edit');window.requestAnimationFrame(()=>{editorRef.current?.scrollIntoView({behavior:'smooth',block:'start'});editorRef.current?.focus({preventScroll:true});});};
 const current=useRef({draft,dirty,busy});current.current={draft,dirty,busy};
 const alive=useRef(false),requestSequence=useRef(0),refreshRef=useRef<(discardDraft?:boolean,quiet?:boolean)=>Promise<void>>(async()=>{});
 const dirtyCallback=useRef(onDirtyChange);dirtyCallback.current=onDirtyChange;
 useEffect(()=>{dirtyCallback.current?.(dirty);},[dirty]);
 useEffect(()=>()=>dirtyCallback.current?.(false),[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{alive.current=true;requestSequence.current++;current.current={draft:null,dirty:false,busy:false};setDraft(null);setBaseline(null);setQuotes([]);setCompleted([]);setCustomers([]);setCanUse(false);setCanCreate(false);setAllowUnbound(false);setLoading(true);setBusy(false);setNotice('');setError('');void refreshRef.current(false,true);const timer=window.setInterval(()=>void refreshRef.current(false,true),30000),focus=()=>void refreshRef.current(false,true);window.addEventListener('focus',focus);return()=>{alive.current=false;requestSequence.current++;window.clearInterval(timer);window.removeEventListener('focus',focus);};},[data.me.id]);
 const put=(q:Quote|null)=>{current.current={...current.current,draft:q?copy(q):null,dirty:false};setDraft(q?copy(q):null);setBaseline(q?copy(q):null);};
 const clearScope=(message:string)=>{requestSequence.current++;setQuotes([]);setCompleted([]);setCustomers([]);setCanUse(false);setCanCreate(false);setAllowUnbound(false);put(null);setNotice('');setError(message);};
 const patch=(values:Partial<Quote>)=>{setDraft(q=>q?{...q,...values}:q);setNotice('');};
 const patchLine=(id:string,values:Partial<QuoteLine>)=>setDraft(q=>q?{...q,lines:q.lines.map(l=>l.id===id?{...l,...values}:l)}:q);
 const patchTerm=(id:string,values:Partial<QuoteTerm>)=>setDraft(q=>q?{...q,terms:q.terms.map(t=>t.id===id?{...t,...values}:t)}:q);
 const discard=()=>!dirty||window.confirm('当前报价有未保存修改。确定放弃这些修改吗？');
 const select=(q:Quote)=>{if(!discard())return;put(q);setError('');setNotice('');};
 const create=()=>{if(!canCreate||!discard())return;setBaseline(null);setDraft(newQuote());setView('edit');setError('');setNotice('新报价尚未保存。请先选择本人负责的客户，保存后仅该客户获授权的负责人可查看。');};
 const refresh=async(discardDraft=false,quiet=false)=>{if(quiet&&current.current.busy)return;if(discardDraft&&!discard())return;const sequence=++requestSequence.current;if(!quiet){setBusy(true);setError('');}try{const [result,completedResult]=await Promise.all([quoteRequest('customer-quotes'),quoteRequest('customer-quote-completed')]);if(!alive.current||sequence!==requestSequence.current)return;if(!result.canUse){clearScope('当前账号没有客户报价权限，页面中的报价内容已清除。');return;}const next:Quote[]=result.quotes||[],accounts:QuoteCustomer[]=result.customers||[];setQuotes(next);setCompleted(completedResult.rows||[]);setCustomers(accounts);setCanUse(true);setCanCreate(!!result.canCreate);setAllowUnbound(!!result.canUseUnbound);const state=current.current,q=state.draft,found=q?.id?next.find(item=>item.id===q.id):undefined;const lostQuote=!!q?.id&&!found,lostCustomer=!!q?.customerAccountId&&!result.canUseUnbound&&!accounts.some(a=>a.id===q.customerAccountId),lostCreation=!!q&&!q.id&&!result.canCreate;if(lostQuote||lostCustomer||lostCreation){put(null);setNotice('');setError('客户责任或报价权限已变更，该报价及未保存的价格内容已从当前页面清除。');}else if(q?.id&&found){if(discardDraft||!state.dirty||!found.canEdit)put(found);if(!quiet)setNotice(state.dirty&&!discardDraft&&found.canEdit?'报价权限与列表已刷新，仍获授权的编辑内容保持不变。':'已读取当前授权范围内的服务器报价。');}else if(!q&&next[0])put(next[0]);else if(!quiet)setNotice('报价权限、客户范围与已完成清单已刷新。');}catch(e){if(!alive.current||sequence!==requestSequence.current)return;if(e instanceof QuoteRequestError&&[401,403].includes(e.status))clearScope(e.message+' 页面中的报价内容已清除。');else setError((e as Error).message);}finally{if(alive.current){setLoading(false);if(!quiet)setBusy(false);}}};
 refreshRef.current=refresh;
 const acceptSaved=(q:Quote)=>{requestSequence.current++;put(q);setQuotes(old=>[q,...old.filter(item=>item.id!==q.id)]);};
 const actionError=(e:unknown)=>{if(e instanceof QuoteRequestError&&[401,403,404].includes(e.status)){clearScope(e.message+' 页面中的报价内容已清除，正在重新核对权限。');void refreshRef.current(false,false);}else setError((e as Error).message);};
 const beginAction=()=>{const sequence=++requestSequence.current;current.current.busy=true;setBusy(true);setError('');setNotice('');return sequence;};
 const finishAction=()=>{if(alive.current){current.current.busy=false;setBusy(false);}};
 const downloadTable=async()=>{
  if(!draft||view==='edit'||busy||dirty)return;
  const sequence=beginAction();
  try{
   const X=await import('xlsx'),en=view==='en',both=view==='both',label=(zh:string,english:string)=>both?`${zh} / ${english}`:en?english:zh;
   const value=(n:NumericDraft|undefined)=>isBlank(n)?null:Number(n);
   const rows:(string|number|null)[][]=[
    ...(en?[]:[[draft.companyZh]]),[label('报价单','QUOTATION'),draft.quoteNo],
    [label('客户','Customer'),draft.customerName,draft.customerCode],[label('联系人','Contact'),draft.contactName||''],
    [label('报价日期','Date'),draft.quoteDate],[label('有效期至','Valid until'),draft.validUntil],[label('币种','Currency'),draft.currency],
    ...(draft.status==='confirmed'?[]:[[label('待确认草稿','DRAFT')]]),[],
    [label('型号','Model'),label('描述','Description'),label('数量','Quantity'),label('数量基准','Quantity basis'),label('单价','Unit price'),label('模具费','Tooling fee')],
    ...draft.lines.map(l=>[l.model,label(l.descriptionZh,l.descriptionEn),value(l.quantity),label(l.quantityBasisZh||'',l.quantityBasisEn||''),value(l.unitPrice),value(l.toolingFee)]),[],
    [label('附加费用','Additional charges'),label('金额','Amount'),label('计价说明','Charge basis'),label('条件性费用','Conditional charge'),label('待确认','Pending review')],
    ...(draft.customerCharges||[]).map(c=>[label(c.labelZh,c.labelEn),value(c.amount),label(c.basisZh,c.basisEn),c.conditional?label('是','Yes'):'',c.needsReview?label('是','Yes'):'']),[],
    [label('说明与条款','Notes & terms')],...draft.terms.map(t=>[label(t.labelZh,t.labelEn),label(t.zh,t.en),t.needsReview?label('待确认','Pending review'):''])
   ];
   if(!en)rows.push([],['内部备注',draft.internalNotesZh||''],['参考汇率',value(draft.exchangeRateCnyPerUsd)],['内部成本项目','人民币','内部说明'],...(draft.internalCosts||[]).map(c=>[c.label,value(c.rmb),c.notes]));
   const sheet=X.utils.aoa_to_sheet(rows);sheet['!cols']=[{wch:28},{wch:65},{wch:24},{wch:35},{wch:18},{wch:18}];
   const book=X.utils.book_new();X.utils.book_append_sheet(book,sheet,en?'Quotation':'报价单');
   if(!alive.current||sequence!==requestSequence.current)return;
   X.writeFile(book,`${(draft.quoteNo||'quotation').replace(/[\\/:*?"<>|]/g,'_')}_${view}_R${draft.version||1}.xlsx`);
   setNotice('已下载当前语言的 Excel 报价表。');
  }catch(e){if(alive.current)actionError(e);}finally{finishAction();}
 };
 const downloadPdf=()=>{if(view==='edit'||busy||dirty)return;setNotice('请在打印窗口选择“另存为 PDF”下载当前语言报价。');window.print();};
 const save=async()=>{if(!draft||!editable||!canUse||!dirty||current.current.busy)return;if(!allowUnbound&&!customers.some(a=>a.id===draft.customerAccountId)){setError('请从客户责任清单中选择本人负责的客户。');setView('edit');return;}const problem=validate(draft);if(problem){setError(problem);setView('edit');return;}const sequence=beginAction();try{const result=await quoteRequest('customer-quote-save',savePayload(draft));if(!alive.current||sequence!==requestSequence.current)return;acceptSaved(result.quote);setNotice(`已保存到协作中台 · 第 ${result.quote.version} 版。仍为待确认草稿，没有向客户发送。`);}catch(e){if(alive.current&&sequence===requestSequence.current)actionError(e);}finally{finishAction();}};
 const upload=async(file?:File)=>{if(!file||!draft?.id||!editable||!canUse)return;if(dirty){setError('请先保存当前草稿，再上传报价附件，避免版本相互覆盖。');return;}if(file.size>10*1024*1024){setError('附件不能超过 10 MB。');return;}const sequence=beginAction();try{const form=new FormData();form.set('quoteId',draft.id);form.set('version',String(draft.version));form.set('file',file);const result=await quoteRequest('customer-quote-upload',form);if(!alive.current||sequence!==requestSequence.current)return;acceptSaved(result.quote);setNotice('报价原文件已归档到本中台，并记录新版本。上传附件不会自动替换表格中的报价内容。');}catch(e){if(alive.current&&sequence===requestSequence.current)actionError(e);}finally{finishAction();}};
 const confirmEnglish=async()=>{if(!draft?.id||!draft.canConfirm||dirty||view!=='en'||busy)return;if(!window.confirm('请确认你已逐项审核当前英文报价的售价、数量基准、附加费用及条款。确认后此版本锁定并生成已完成报价清单；不会自动向客户发送，也不会自动标记“已报价客户”为 Y。确定确认此英文版本吗？'))return;const sequence=beginAction();try{const result=await quoteRequest('customer-quote-confirm',{id:draft.id,version:draft.version,acknowledgeEnglish:true});if(!alive.current||sequence!==requestSequence.current)return;acceptSaved(result.quote);setNotice('英文报价已确认并锁定，已完成清单已生成；尚未标记为已向客户报价。');const completedSequence=requestSequence.current;const next=await quoteRequest('customer-quote-completed');if(alive.current&&completedSequence===requestSequence.current&&current.current.draft?.id===result.quote.id)setCompleted(next.rows||[]);}catch(e){if(alive.current)actionError(e);}finally{finishAction();}};
 const revise=async()=>{if(!draft?.id||!draft.canRevise||busy)return;if(!window.confirm('从当前已确认版本创建新的修订草稿？已确认报价和已完成清单不会被覆盖。'))return;const sequence=beginAction();try{const result=await quoteRequest('customer-quote-revise',{id:draft.id,version:draft.version});if(!alive.current||sequence!==requestSequence.current)return;acceptSaved(result.quote);setView('edit');setNotice('已创建修订草稿。旧的已确认版本及其清单保持不变；修改后需要重新确认英文版本。');}catch(e){if(alive.current&&sequence===requestSequence.current)actionError(e);}finally{finishAction();}};
 const visible=quotes.filter(q=>[q.customerCode,q.customerName,q.quoteNo,...q.lines.map(l=>[l.model,l.descriptionZh,l.descriptionEn].join(' '))].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="customer-quote-panel">
  <section className="cq-intro cq-no-print"><div><span className="cq-eyebrow">CUSTOMER QUOTATIONS</span><h2>客户报价 · 同一份数据，双语呈现</h2><p>业务报价直接保存在现有协作中台。英文售价、描述及条款可独立编辑；中文版保留内部成本与备注，最终英文确认后生成已完成清单。</p></div><Languages aria-hidden="true" size={38}/></section>
  <div className="cq-draft-notice cq-no-print"><b>先草稿，后确认</b><span>保存不等于最终确认，也不等于已发送给客户。确认后的英文报价锁定并进入已完成清单；修改需新建修订草稿，旧版永久保留。</span></div>
  {error&&<div className="error cq-message cq-no-print" role="alert">{error}</div>}{notice&&<div className="success cq-message cq-no-print" role="status">{notice}</div>}
  <section className="panel cq-picker cq-no-print"><div className="cq-toolbar"><div><h3>客户报价档案 <span className="muted">{quotes.length} 份</span></h3><p>{allowUnbound?'管理员维护范围 · 未绑定报价不向普通员工开放':'按客户责任清单，仅查看和修改本人负责客户的报价'}</p></div><input className="cq-search" aria-label="搜索报价" placeholder="搜索客户、报价单号、款号或描述关键词" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outline" disabled={busy||loading} onClick={()=>void refresh()}><RefreshCw size={15}/>刷新列表</Button>{canCreate&&<Button disabled={busy||loading} onClick={create}><Plus size={16}/>新建报价草稿</Button>}</div>
   {loading?<p className="cq-placeholder">正在读取共享报价…</p>:visible.length?<div className="cq-list" aria-label="报价列表">{visible.map(q=><button key={q.id} className={'cq-list-item '+(draft?.id===q.id?'selected':'')} disabled={busy} onClick={()=>select(q)}><span><b>{q.customerCode} {q.customerName}</b><small>{q.status==='confirmed'?'已确认':'待确认'} · 第 {q.version} 版</small></span><strong>{q.quoteNo}</strong><small>{q.quoteDate} · {q.lines.length} 款 · {q.currency}{q.canEdit?'':' · 只读'}</small></button>)}</div>:<p className="cq-placeholder">{search?'没有匹配的报价。':'暂无可查看的报价。获授权的业务同事可以新建草稿。'}</p>}
  </section>
  {canUse&&<section className="panel cq-completed cq-no-print"><details><summary>已完成报价清单总表 · {completed.length} 条</summary><p className="cq-help">只有最终确认的英文版本进入此表，旧版本保留。确认不等于发送，“已报价客户”默认留空；本次测试不会自动填 Y。</p>{completed.length?<div className="cq-history-table"><table><thead><tr><th>客户编号</th><th>客户名称</th><th>款号</th><th>产品描述</th><th>单价（美元/副）</th><th>报价单号</th><th>报价版本</th><th>确认时间</th><th>已报价客户</th></tr></thead><tbody>{completed.filter(r=>[r.customerCode,r.customerName,r.quoteNo,r.model,r.descriptionZh].join(' ').toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.id}><td>{r.customerCode||'未设编号'}</td><td>{r.customerName}</td><td>{r.model}</td><td>{r.descriptionZh}</td><td>{money(r.unitPriceUsd)}</td><td>{r.quoteNo}</td><td>R{r.quoteVersion}</td><td>{dateTime(r.confirmedAt)}</td><td>{r.quotedCustomer==='Y'?'Y（是）':''}</td></tr>)}</tbody></table></div>:<p className="cq-placeholder">暂无已确认报价；保存测试草稿不会生成已完成记录。</p>}</details></section>}
  {draft?<>
   <div className="cq-actions cq-no-print"><div className="cq-tabs" role="tablist" aria-label="报价语言与编辑">{([['zh','中文内部版'],['en','English'],['both','中英对照（内部）'],['edit',editable?'编辑草稿':'查看详情']] as [View,string][]).map(([id,label])=><button type="button" role="tab" key={id} aria-selected={view===id} className={view===id?'active':''} onClick={()=>id==='edit'?openEditor():setView(id)}>{label}</button>)}</div><div className="cq-action-buttons"><span className={'cq-save-state '+(dirty?'unsaved':'')}>{dirty?'有未保存修改':draft.id?`中台已存 · R${draft.version}`:'尚未保存'}</span>{editable&&view!=='edit'&&<Button variant="outline" disabled={busy} onClick={openEditor}><PencilLine size={16}/>修改全部内容</Button>}{draft.id&&<Button variant="outline" disabled={busy} onClick={()=>void refresh(true)}>读取服务器版本</Button>}<Button variant="outline" disabled={view==='edit'||busy||dirty} title="在打印窗口选择另存为 PDF" onClick={downloadPdf}><Download size={16}/>下载 PDF</Button><Button variant="outline" disabled={view==='edit'||busy||dirty} onClick={()=>void downloadTable()}><Download size={16}/>下载 Excel</Button><Button variant="outline" disabled={view==='edit'||busy} onClick={()=>window.print()}><Printer size={16}/>{draft.status==='confirmed'?'打印当前语言报价':'打印当前语言草稿'}</Button>{editable&&<Button disabled={busy||!dirty} title="保存当前修改，仍保留为草稿；不会最终确认或发送给客户" onClick={()=>void save()}><Save size={16}/>确认保存</Button>}{draft.canConfirm&&<Button disabled={busy||dirty||view!=='en'||!draft.id} title={view!=='en'?'请切换 English 并逐项审核后确认':dirty?'请先保存全部修改':'确认当前英文版本并生成已完成清单'} onClick={()=>void confirmEnglish()}>确认英文报价</Button>}{draft.canRevise&&<Button disabled={busy} onClick={()=>void revise()}><Plus size={16}/>新建修订草稿</Button>}</div></div>
   {draft.status==='confirmed'&&<div className="cq-confirmed cq-no-print">此英文报价已确认并锁定 · {draft.confirmedBy||''} {draft.confirmedAt?dateTime(draft.confirmedAt):''}。需要修改时请创建修订草稿，历史版本不会被覆盖。</div>}
   {changedBasis&&<div className="cq-warning cq-no-print" role="status">数量或日期已修改，请同时核对对应的单价、有效期及报价条款。旧价格不会自动推算为其他数量的价格。</div>}
   {view==='edit'?<section ref={editorRef} tabIndex={-1} aria-label="报价内容编辑" className="panel cq-editor cq-no-print"><div className="cq-editor-footer"><div><b className={'cq-save-state '+(dirty?'unsaved':'')}>{busy?'正在保存，请稍候…':dirty?'有未保存修改，请确认保存':'当前内容已保存，无需重复保存'}</b><p>保存草稿，保留历史；不会定稿或发送客户。</p></div>{editable&&<Button disabled={busy||!dirty} onClick={()=>void save()}><Save size={16}/>确认保存全部修改</Button>}</div><div className="cq-editor-guide"><b>{editable?'修改报价全部内容':'查看报价内容'}</b><p>公司、客户、联系人、款号、中英文描述、数量、价格、费用、日期、条款和内部备注集中在此编辑。完成后点击“确认保存”，只保存草稿并保留旧版；需要正式定稿时，再审核并点击“确认英文报价”。</p>{!editable&&<p>此版本只读；已确认报价请先“新建修订草稿”，不能覆盖已确认的历史内容。</p>}</div><fieldset disabled={!editable||busy}><legend>报价基本资料</legend><div className="cq-form-grid">
    <Field label={allowUnbound?'关联客户清单（管理员可暂不关联）':'关联本人负责的客户（必选）'}><select disabled={!allowUnbound&&!!draft.id} value={draft.customerAccountId||''} onChange={e=>{const account=customers.find(a=>a.id===e.target.value);patch({customerAccountId:account?.id||null,...(account?{customerName:account.customer,customerCode:account.customerCode||''}:allowUnbound?{}:{customerName:'',customerCode:''})});}}><option value="" disabled={!allowUnbound}>{allowUnbound?'暂不关联 · 仅管理员维护':'请选择本人负责的客户'}</option>{customers.map(a=><option key={a.id} value={a.id}>{a.customerCode||'未设编号'} · {a.customer}</option>)}</select></Field>
    <Field label="客户编号（新客可留空）"><input readOnly={!allowUnbound||!!draft.customerAccountId} value={draft.customerCode} onChange={e=>patch({customerCode:e.target.value})}/></Field>
    <Field label="客户名称"><input readOnly={!allowUnbound||!!draft.customerAccountId} value={draft.customerName} onChange={e=>patch({customerName:e.target.value})}/></Field>
    <Field label="联系人"><input value={draft.contactName||''} onChange={e=>patch({contactName:e.target.value})}/></Field>
    <Field label="报价单号"><input value={draft.quoteNo} onChange={e=>patch({quoteNo:e.target.value})}/></Field>
    <Field label="报价日期"><input type="date" value={draft.quoteDate} onChange={e=>patch({quoteDate:e.target.value})}/></Field>
    <Field label="有效期至"><input type="date" value={draft.validUntil} onChange={e=>patch({validUntil:e.target.value})}/></Field>
    <Field label="币种"><input value={draft.currency} maxLength={3} onChange={e=>patch({currency:e.target.value.toUpperCase()})}/></Field>
    <Field label="公司名称 · 中文"><input value={draft.companyZh} onChange={e=>patch({companyZh:e.target.value})}/></Field>
    <Field label="Company name · English"><input value={draft.companyEn} onChange={e=>patch({companyEn:e.target.value})}/></Field>
    <Field label="系列名称 · 中文"><input value={draft.collectionZh||''} onChange={e=>patch({collectionZh:e.target.value})}/></Field>
    <Field label="Collection · English"><input value={draft.collectionEn||''} onChange={e=>patch({collectionEn:e.target.value})}/></Field>
   </div><p className="cq-help">已关联客户的名称、编号来自客户责任清单，不能在报价中直接改写；客户关联及责任人仍按原权限管理。未关联的新客草稿可由管理员修改客户名称，编号可留空。报价内容修改不会开放其他客户的访问权限。</p><div className="cq-section-heading"><h3>产品与费用</h3><Button type="button" variant="outline" onClick={()=>patch({lines:[...draft.lines,newLine()]})}><Plus size={15}/>增加产品</Button></div><p className="cq-help">数量为每款报价数量，不等同于最低起订量。未确认的数量、价格或费用请留空，不会转换成 0；明确免收时填 0。这里的单价为英文对客售价，人民币参考换算不会覆盖你的修改。</p>
   {draft.lines.map((line,index)=><div className="cq-line-editor" key={line.id}><div className="cq-section-heading"><b>产品 {index+1}</b><Button type="button" size="sm" variant="ghost" disabled={draft.lines.length===1} onClick={()=>{if(window.confirm(`从当前草稿移除第 ${index+1} 项？保存后会形成新版本，历史版本仍保留。`))patch({lines:draft.lines.filter(l=>l.id!==line.id)});}}>移除此项</Button></div><div className="cq-line-numbers"><Field label={`型号 · 第 ${index+1} 项`}><input value={line.model} onChange={e=>patchLine(line.id,{model:e.target.value})}/></Field><Field label={`报价基准数量（副） · 第 ${index+1} 项`}><input type="number" min="1" step="1" value={line.quantity??''} onChange={e=>patchLine(line.id,{quantity:e.target.value})}/></Field><Field label={`对客单价 (${draft.currency}/副) · 第 ${index+1} 项`}><input type="number" min="0" step="0.01" value={line.unitPrice??''} onChange={e=>patchLine(line.id,{unitPrice:e.target.value})}/></Field><Field label={`模具费 (${draft.currency}/款) · 第 ${index+1} 项`}><input type="number" min="0" step="0.01" value={line.toolingFee??''} onChange={e=>patchLine(line.id,{toolingFee:e.target.value})}/></Field></div><div className="cq-paired"><Field label={`数量基准 · 中文 · 第 ${index+1} 项`}><input placeholder="例如：每色／尺寸；留空表示本款数量" value={line.quantityBasisZh||''} onChange={e=>patchLine(line.id,{quantityBasisZh:e.target.value})}/></Field><Field label={`Quantity basis · English · 第 ${index+1} 项`}><input placeholder="e.g. per colour / size" value={line.quantityBasisEn||''} onChange={e=>patchLine(line.id,{quantityBasisEn:e.target.value})}/></Field></div><div className="cq-paired"><Field label={`产品描述 · 中文 · 第 ${index+1} 项`}><textarea rows={3} value={line.descriptionZh} onChange={e=>patchLine(line.id,{descriptionZh:e.target.value})}/></Field><Field label={`Product description · English · 第 ${index+1} 项`}><textarea rows={3} value={line.descriptionEn} onChange={e=>patchLine(line.id,{descriptionEn:e.target.value})}/></Field></div>{line.sourceFormula&&<small className="cq-help">原文件模具费公式（溯源，不自动执行）：{line.sourceFormula}</small>}</div>)}
   <div className="cq-section-heading"><h3>对客单列附加费用</h3><Button type="button" variant="outline" onClick={()=>patch({customerCharges:[...(draft.customerCharges||[]),{id:newKey(),labelZh:'',labelEn:'',amount:null,basisZh:'',basisEn:'',conditional:false,needsReview:true}]})}><Plus size={15}/>增加费用</Button></div><p className="cq-help">这些是对客收费，不是内部成本；不自动计入产品单价或订单总额。仅在特定数量条件下发生的费用，建议写在英文条款中，不能当成当前已发生费用。</p>
   {(draft.customerCharges||[]).map((charge,index)=><div className="cq-term-editor" key={charge.id}><div className="cq-paired"><Field label={`附加费用名称 · 中文 · 第 ${index+1} 项`}><input value={charge.labelZh} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,labelZh:e.target.value}:c)})}/></Field><Field label={`Additional charge · English · 第 ${index+1} 项`}><input value={charge.labelEn} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,labelEn:e.target.value}:c)})}/></Field><Field label={`附加费用 (${draft.currency}) · 第 ${index+1} 项`}><input type="number" min="0" step="0.01" value={charge.amount??''} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,amount:e.target.value}:c)})}/></Field><Field label={`费用计价说明 · 中文 · 第 ${index+1} 项`}><input value={charge.basisZh} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,basisZh:e.target.value}:c)})}/></Field><Field label={`Charge basis · English · 第 ${index+1} 项`}><input value={charge.basisEn} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,basisEn:e.target.value}:c)})}/></Field></div><div className="cq-term-review"><label><input type="checkbox" checked={!!charge.conditional} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,conditional:e.target.checked}:c)})}/>条件性费用（不是当前已发生金额）</label><label><input type="checkbox" checked={charge.needsReview!==false} onChange={e=>patch({customerCharges:(draft.customerCharges||[]).map(c=>c.id===charge.id?{...c,needsReview:e.target.checked}:c)})}/>此项费用仍需确认</label></div><Button type="button" size="sm" variant="ghost" onClick={()=>{if(window.confirm('移除当前草稿中的此项对客费用？'))patch({customerCharges:(draft.customerCharges||[]).filter(c=>c.id!==charge.id)});}}>移除此费用</Button></div>)}
   <div className="cq-section-heading"><h3>双语条款</h3><Button type="button" variant="outline" onClick={()=>patch({terms:[...draft.terms,{id:newKey(),labelZh:'',labelEn:'',zh:'',en:'',needsReview:true,reviewNote:''}]})}><Plus size={15}/>增加条款</Button></div><p className="cq-help">英文描述、条款与对客价格允许人工修改；请同时核对中文对应条件。内部供应商、成本及外发备注请放在下方“仅中文内部资料”，不要写入英文条款。</p>
   {draft.terms.map((term,index)=><div className="cq-term-editor" key={term.id}><div className="cq-paired"><Field label={`条款标题 · 中文 · 第 ${index+1} 项`}><input value={term.labelZh} onChange={e=>patchTerm(term.id,{labelZh:e.target.value})}/></Field><Field label={`Term title · English · 第 ${index+1} 项`}><input value={term.labelEn} onChange={e=>patchTerm(term.id,{labelEn:e.target.value})}/></Field><Field label={`条款内容 · 中文 · 第 ${index+1} 项`}><textarea rows={3} value={term.zh} onChange={e=>patchTerm(term.id,{zh:e.target.value})}/></Field><Field label={`Term text · English · 第 ${index+1} 项`}><textarea rows={3} value={term.en} onChange={e=>patchTerm(term.id,{en:e.target.value})}/></Field></div><div className="cq-term-review"><label><input type="checkbox" checked={term.needsReview} onChange={e=>patchTerm(term.id,{needsReview:e.target.checked})}/>该条款仍需确认</label><input aria-label={`条款内部核对说明 · 第 ${index+1} 项`} placeholder="内部核对说明（不打印）" value={term.reviewNote||''} onChange={e=>patchTerm(term.id,{reviewNote:e.target.value})}/><Button type="button" size="sm" variant="ghost" onClick={()=>{if(window.confirm('从当前草稿移除此条款？'))patch({terms:draft.terms.filter(t=>t.id!==term.id)});}}>移除条款</Button></div></div>)}
   <section className="cq-internal-editor"><div className="cq-section-heading"><h3>仅中文内部资料</h3></div><p className="cq-help">以下备注、供应商及成本参考只出现在中文内部版或内部编辑区域，不进入英文预览及英文打印。修改汇率只改变参考换算，不会修改已填写的英文售价。</p><Field label="中文内部备注（不进入英文版）"><textarea rows={3} value={draft.internalNotesZh||''} onChange={e=>patch({internalNotesZh:e.target.value})}/></Field><Field label="内部参考汇率 · 1 美元等于多少人民币"><input type="number" min="0.0001" step="0.0001" value={draft.exchangeRateCnyPerUsd??''} onChange={e=>patch({exchangeRateCnyPerUsd:e.target.value})}/></Field><div className="cq-section-heading"><h3>人民币成本参考（不自动填写对客价格）</h3><Button type="button" variant="outline" onClick={()=>patch({internalCosts:[...(draft.internalCosts||[]),{id:newKey(),label:'',rmb:'',notes:''}]})}>增加成本参考</Button></div>{(draft.internalCosts||[]).map((cost,index)=><div key={cost.id} className="cq-cost-editor"><Field label={`成本参考名称 · 第 ${index+1} 项`}><input value={cost.label} onChange={e=>patch({internalCosts:(draft.internalCosts||[]).map(c=>c.id===cost.id?{...c,label:e.target.value}:c)})}/></Field><Field label={`人民币金额 · 第 ${index+1} 项`}><input type="number" min="0" step="0.01" value={cost.rmb??''} onChange={e=>patch({internalCosts:(draft.internalCosts||[]).map(c=>c.id===cost.id?{...c,rmb:e.target.value}:c)})}/></Field><Field label={`内部计价说明 · 第 ${index+1} 项`}><input value={cost.notes} onChange={e=>patch({internalCosts:(draft.internalCosts||[]).map(c=>c.id===cost.id?{...c,notes:e.target.value}:c)})}/></Field><p className="cq-help">参考折合 USD：{!isBlank(cost.rmb)&&Number(draft.exchangeRateCnyPerUsd)>0?money(Number(cost.rmb)/Number(draft.exchangeRateCnyPerUsd)):'待确认'}</p><Button type="button" variant="ghost" size="sm" onClick={()=>patch({internalCosts:(draft.internalCosts||[]).filter(c=>c.id!==cost.id)})}>移除参考</Button></div>)}</section>
   <Field label="内部待确认事项（每行一项，不打印）"><textarea rows={3} value={draft.reviewNotes.join('\n')} onChange={e=>patch({reviewNotes:e.target.value.split('\n')})}/></Field>
   </fieldset></section>:<QuoteDocument quote={draft} view={view}/>}
   {view!=='en'&&<section className="panel cq-support cq-no-print"><div className="cq-section-heading"><div><h3><FileText size={17}/> 原始附件与修改记录</h3><p className="cq-help">所有附件和保存版本归档于此中台；不创建另一套工作台。</p></div>{draft.hasSource&&draft.id&&<Button variant="outline" asChild><a href={'/api/workspace/customer-quote-file?id='+encodeURIComponent(draft.id)}><Download size={16}/>下载报价原文件</a></Button>}</div>
    <div className="cq-source"><div><b>{draft.sourceFilename||'尚未上传报价原文件'}</b>{draft.sourceHash&&<code title={draft.sourceHash}>SHA-256 · {draft.sourceHash}</code>}<p>附件支持 Excel、PDF、PNG/JPEG 客户参考图片；原件归档，不会随在线字段修改而变化。支持下载当前语言的 Excel 报价表，并通过打印窗口另存为 PDF。</p></div>{editable&&<label className={'cq-upload '+(!draft.id||busy||dirty?'disabled':'')}><UploadCloud size={17}/>{draft.hasSource?'上传新附件版本':'上传报价原文件'}<input type="file" accept=".xlsx,.xls,.pdf,.png,.jpg,.jpeg" disabled={!draft.id||busy||dirty} onChange={e=>{const file=e.target.files?.[0];e.target.value='';void upload(file);}}/></label>}</div>{editable&&(!draft.id||dirty)&&<p className="cq-help">请先保存草稿，再上传附件。新附件留存新版本，不会清除旧版本历史。</p>}
    {(draft.reviewNotes.some(Boolean)||draft.terms.some(t=>t.needsReview))&&<div className="cq-review"><b>内部待确认</b><ul>{draft.reviewNotes.filter(Boolean).map((text,i)=><li key={i}>{text}</li>)}{draft.terms.filter(t=>t.needsReview).map(t=><li key={t.id}>{t.labelZh||t.labelEn||'未命名条款'}：{t.reviewNote||'请核对中英文表述并确认。'}</li>)}</ul></div>}
    <details className="cq-history"><summary>查看保存记录 · {draft.history?.length||0} 条</summary>{draft.history?.length?<div className="cq-history-table"><table><thead><tr><th>版本</th><th>操作</th><th>操作人</th><th>时间</th><th>原文件</th></tr></thead><tbody>{draft.history.map(h=><tr key={h.id}><td>R{h.version}</td><td>{h.action}</td><td>{h.updatedBy}</td><td>{dateTime(h.updatedAt)}</td><td>{h.sourceFilename||'—'}</td></tr>)}</tbody></table></div>:<p className="cq-help">尚无历史记录，保存后自动留痕。</p>}</details>
   </section>}
  </>:!loading&&<section className="panel cq-no-print"><Empty title={canUse?'选择或新建一份客户报价':'当前账号没有客户报价权限'} detail={canUse?'只有客户责任清单中本人负责的客户会出现在选择列表中。责任关系变更后，页面会重新核对权限。':'请联系管理员核对报价权限名单及客户责任清单；不会开放其他同事负责客户的报价。'}/></section>}
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){const labelId=useId();return <label className="cq-field"><span id={labelId}>{label}</span>{isValidElement<{'aria-labelledby'?:string}>(children)?cloneElement(children,{'aria-labelledby':children.props['aria-labelledby']||labelId}):children}</label>;}
function QuoteDocument({quote:q,view}:{quote:Quote;view:Exclude<View,'edit'>}){
 const documentRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{
  const media=window.matchMedia('print');
  const reset=()=>documentRef.current?.style.removeProperty('--cq-print-scale');
  const fit=()=>{
   const doc=documentRef.current;if(!doc)return;
   reset();
   // A4 portrait minus 10 mm margins, with a small rounding allowance.
   const availableHeight=275*96/25.4;
   const height=doc.getBoundingClientRect().height;
   doc.style.setProperty('--cq-print-scale',String(Math.min(1,availableHeight/Math.max(height,1))));
  };
  const changed=()=>media.matches?fit():reset();
  window.addEventListener('beforeprint',fit);window.addEventListener('afterprint',reset);media.addEventListener('change',changed);
  return()=>{window.removeEventListener('beforeprint',fit);window.removeEventListener('afterprint',reset);media.removeEventListener('change',changed);reset();};
 },[q,view]);
 const en=view==='en',both=view==='both',confirmed=q.status==='confirmed',pending=en?'To be confirmed':'待确认',text=(zh:string,english:string)=>both?<><span lang="zh-CN">{zh||'待填写'}</span><span className="cq-english" lang="en">{english||'To be completed'}</span></>:en?(english||'To be completed'):(zh||'待填写');
 const showTooling=q.lines.some(l=>!isBlank(l.toolingFee)&&Number(l.toolingFee)!==0)||!(q.customerCharges||[]).length;
 return <article ref={documentRef} className={'cq-document cq-language-'+view} aria-label="报价单预览"><header className="cq-document-header"><CompanyLogo className="cq-logo"/><div className="cq-company">{!en&&<h2>{q.companyZh||'待填写'}</h2>}{(q.collectionZh||q.collectionEn)&&<p>{text(q.collectionZh||'',q.collectionEn||'')}</p>}</div></header><div className="cq-document-title"><h3>{en?'QUOTATION':both?'内部中英对照 / QUOTATION':'报 价 单 · 中文内部版'}</h3><b>{q.quoteNo||'—'}</b></div><dl className="cq-metadata"><div><dt>{en?'Customer':'客户'}</dt><dd>{q.customerName||pending}{q.customerCode&&<span className="cq-client-name">{q.customerCode}</span>}</dd></div><div><dt>{en?'Contact':'联系人'}</dt><dd>{q.contactName||'—'}</dd></div><div><dt>{en?'Date':'报价日期'}</dt><dd>{q.quoteDate||pending}</dd></div><div><dt>{en?'Currency':'币种'}</dt><dd>{q.currency||pending}</dd></div><div><dt>{en?'Valid until':'有效期至'}</dt><dd>{q.validUntil||pending}</dd></div></dl>
  <div className="cq-document-scroll"><table className={'cq-products'+(showTooling?' cq-with-tooling':'')}><thead><tr><th>{text('序号','No.')}</th><th>{text('型号','Model No.')}</th><th>{text('产品描述','Product description')}</th><th>{text('报价基准数量（副）','Quotation basis (pairs)')}</th><th>{text(`对客单价（${q.currency}/副）`,`Unit price (${q.currency}/pair)`)}</th>{showTooling&&<th>{text(`模具费（${q.currency}/款）`,`Tooling fee (${q.currency}/model)`)}</th>}</tr></thead><tbody>{q.lines.map((line,index)=><tr key={line.id}><td>{index+1}</td><td><b>{line.model||'—'}</b></td><td className="cq-description">{text(line.descriptionZh,line.descriptionEn)}</td><td>{isBlank(line.quantity)?pending:line.quantity}{(line.quantityBasisZh||line.quantityBasisEn)&&<small className="cq-quantity-basis">{text(line.quantityBasisZh||'',line.quantityBasisEn||'')}</small>}</td><td>{isBlank(line.unitPrice)?pending:money(line.unitPrice)}</td>{showTooling&&<td>{isBlank(line.toolingFee)?pending:money(line.toolingFee)}</td>}</tr>)}</tbody></table></div>
  {!!q.customerCharges?.length&&<section className="cq-terms cq-charges"><h4>{en?'Additional charges':both?'附加费用 / Additional charges':'对客附加费用'}</h4><table><thead><tr><th>{text('费用项目','Charge')}</th><th>{text(`金额（${q.currency}）`,`Amount (${q.currency})`)}</th><th>{text('计价说明','Charge basis')}</th></tr></thead><tbody>{q.customerCharges.map(c=><tr key={c.id}><td>{text(c.labelZh,c.labelEn)}{c.conditional&&<small className="cq-review-tag">{en?'Conditional charge':'条件性费用'}</small>}{c.needsReview&&<small className="cq-review-tag">{en?'Pending review':'待确认'}</small>}</td><td>{isBlank(c.amount)?pending:money(c.amount)}</td><td>{text(c.basisZh,c.basisEn)}</td></tr>)}</tbody></table></section>}
  <section className="cq-terms"><h4>{en?'Notes & terms':both?'说明与条款 / Notes & terms':'说明与条款'}</h4>{q.terms.map(term=><div key={term.id} className={'cq-term '+(term.needsReview?'review':'')}><b>{text(term.labelZh,term.labelEn)}</b><p>{text(term.zh,term.en)}{term.needsReview&&<small className="cq-review-tag">{en?'Pending review':'待确认 / Pending review'}</small>}</p></div>)}</section>
  {!en&&(q.internalNotesZh||q.internalCosts?.length||!isBlank(q.exchangeRateCnyPerUsd))&&<section className="cq-internal-document"><h4>内部资料 · 不进入英文对客版</h4>{q.internalNotesZh&&<p className="cq-internal-note">{q.internalNotesZh}</p>}{!isBlank(q.exchangeRateCnyPerUsd)&&<p>参考汇率：1 美元 = {q.exchangeRateCnyPerUsd} 元人民币。以下仅为成本换算参考，不是英文对客售价。</p>}{!!q.internalCosts?.length&&<table><thead><tr><th>内部参考项目</th><th>人民币</th><th>参考美元</th><th>内部说明</th></tr></thead><tbody>{q.internalCosts.map(c=><tr key={c.id}><td>{c.label}</td><td>{money(c.rmb)}</td><td>{!isBlank(c.rmb)&&Number(q.exchangeRateCnyPerUsd)>0?money(Number(c.rmb)/Number(q.exchangeRateCnyPerUsd)):'待确认'}</td><td>{c.notes}</td></tr>)}</tbody></table>}</section>}
  <footer className="cq-document-footer"><span>{confirmed?(en?'Confirmed quotation. Sending is recorded separately.':'已确认报价 · 发送记录另行登记。'):(en?'DRAFT — Subject to final confirmation. Not an approved quotation.':'待确认草稿 — 须经最终确认，不作为正式报价。')}</span><span>{q.id?`R${q.version}`:'UNSAVED'}</span></footer>
 </article>;
}
