'use client';

import {useEffect,useRef,useState} from 'react';
import {Download,FileText,ImageIcon,UploadCloud,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {clientId} from '@/lib/client-id';
import {dateTime} from './ui';
import type {QuoteTemplateBinding} from './customer-quote-template-panel';

export type QuoteMedia={id:string;quoteId:string;quoteVersion:number;lineId?:string;category:'image'|'drawing'|'sent_quote'|'evidence';filename:string;contentType:'image/png'|'image/jpeg'|'application/pdf'|'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';size:number;uploadedAt:string;uploadedBy:string;supplement:boolean;url:string};
export type QuoteSentRecord={id:string;sentDate:string;recipient:string;channel:'email'|'whatsapp'|'wechat'|'other';mediaIds?:string[];media?:QuoteMedia[];createdAt?:string;createdBy?:string};
type QuoteUnit='piece'|'pair'|'set'|'unknown';
export type CompletedQuote={id:string;quoteId:string;quoteVersion:number;lineId:string;quoteNo:string;customerCode:string;customerName:string;model:string;descriptionZh:string;descriptionEn?:string;unitPriceUsd?:number|null;unitPrice?:number|null;currency?:string;unit?:QuoteUnit;quantity:number|null;brand?:string;businessType?:string;quoteMode?:'order'|'price_list';factoryModel?:string;customerModel?:string;materialNumber?:string;component?:string;templateBinding?:QuoteTemplateBinding;confirmedAt:string;quotedCustomer:''|'Y';media?:QuoteMedia[];sentHistory?:QuoteSentRecord[];canRegisterSent?:boolean;canSupplementArchive?:boolean};
type ArchiveQuote={id:string;version:number;status:string;quoteNo:string;customerName:string;customerCode:string;contactName?:string;quoteDate:string;validUntil:string;currency:string;quoteMode?:'order'|'price_list';brand?:string;businessType?:string;templateBinding?:QuoteTemplateBinding;confirmedAt?:string;canRegisterSent?:boolean;canSupplementArchive?:boolean;canRevise?:boolean;lines:{id:string;model:string;factoryModel?:string;customerModel?:string;materialNumber?:string;component?:string;side?:'left'|'right'|'none';supplyStage?:'raw'|'semi_finished'|'finished'|'unknown';scopeNotesZh?:string;scopeNotesEn?:string;descriptionZh:string;descriptionEn:string;unitPrice:number|null;toolingFee?:number|null;quantity:number|null;unit?:QuoteUnit;quantityBasisZh?:string;quantityBasisEn?:string}[];customerCharges?:{id:string;labelEn:string;amount:number|null;basisEn:string;conditional?:boolean}[];terms?:{id:string;labelEn:string;en:string}[]};
type ArchiveVersion={quote:ArchiveQuote;media:QuoteMedia[];sentHistory:QuoteSentRecord[]};
type Request=(action:string,body?:unknown)=>Promise<any>;
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
const amount=(value:number|null|undefined)=>value==null?'待确认':Number(value).toFixed(2);
const fileHref=(media:QuoteMedia,download=false)=>'/api/workspace/customer-quote-media-file?id='+encodeURIComponent(media.id)+(download?'&download=1':'');
const isImage=(media:QuoteMedia)=>media.contentType==='image/png'||media.contentType==='image/jpeg';
const isXlsx=(media:QuoteMedia)=>media.contentType==='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const unitLabel=(unit:QuoteUnit|undefined)=>({piece:'件',pair:'副',set:'套',unknown:'单位待确认'}[unit||'pair']);
const channelLabels={email:'邮件',whatsapp:'WhatsApp',wechat:'微信',other:'其他'};
const latestSentDate=(history:QuoteSentRecord[]|undefined)=>(history||[]).map(record=>record.sentDate).filter(date=>/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Date.parse(date+'T00:00:00Z'))&&new Date(date+'T00:00:00Z').toISOString().slice(0,10)===date).reduce((latest,date)=>date>latest?date:latest,'');

export function QuoteMediaGallery({media,compact=false,emptyLabel='暂无款式图片／图纸'}:{media:QuoteMedia[];compact?:boolean;emptyLabel?:string}){
 const [preview,setPreview]=useState<QuoteMedia|null>(null),dialogRef=useRef<HTMLDialogElement|null>(null);
 useEffect(()=>{const dialog=dialogRef.current;if(preview&&!dialog?.open)dialog?.showModal();else if(!preview&&dialog?.open)dialog.close();},[preview]);
 useEffect(()=>{if(preview&&!media.some(item=>item.id===preview.id))setPreview(null);},[media,preview]);
 if(!media.length)return <span className="cq-media-empty">{emptyLabel}</span>;
 return <><div className={'cq-media-gallery '+(compact?'compact':'')}>{media.map(item=><div className="cq-media-card" key={item.id}>
  {isImage(item)?<button type="button" className="cq-media-thumbnail" aria-label={'查看图片 '+item.filename} onClick={()=>setPreview(item)}><img src={fileHref(item)} alt={item.filename} loading="lazy"/></button>:isXlsx(item)?<a className="cq-media-file" href={fileHref(item,true)} aria-label={'下载 Excel '+item.filename}><Download size={24}/><span>下载 Excel</span></a>:<a className="cq-media-file" href={fileHref(item)} target="_blank" rel="noreferrer"><FileText size={24}/><span>打开 PDF</span></a>}
  <div className="cq-media-caption"><b title={item.filename}>{item.filename}</b>{item.supplement&&<small>确认后补充归档</small>}<a href={fileHref(item,true)}><Download size={12}/>下载</a>{!compact&&<small>{dateTime(item.uploadedAt)} · {item.uploadedBy}</small>}</div>
 </div>)}</div>{preview&&<dialog ref={dialogRef} className="cq-image-dialog cq-no-print" onCancel={()=>setPreview(null)} onClick={e=>{if(e.target===e.currentTarget)setPreview(null);}}><div><header><b>{preview.filename}</b><Button variant="ghost" size="icon" aria-label="关闭图片预览" onClick={()=>setPreview(null)}><X size={19}/></Button></header><img src={fileHref(preview)} alt={preview.filename}/><footer><a href={fileHref(preview,true)}>下载原图</a>{preview.supplement&&<span>确认后补充归档 · 不代表发送时已包含此文件</span>}</footer></div></dialog>}</>;
}

export function QuoteLineMedia({lines,media,disabled,canUpload,onUpload}:{lines:{id:string;model:string}[];media:QuoteMedia[];disabled:boolean;canUpload:boolean;onUpload:(lineId:string,category:'image'|'drawing',file:File)=>void}){
 return <div className="cq-line-media">{lines.map((line,index)=><section className="cq-line-media-item" key={line.id}><div className="cq-section-heading"><h4>第 {index+1} 款 · {line.model||'未填款号'}</h4>{canUpload&&<div className="cq-media-upload-actions"><MediaUpload label="添加款式图片" category="image" disabled={disabled} onUpload={file=>onUpload(line.id,'image',file)}/><MediaUpload label="添加图纸" category="drawing" disabled={disabled} onUpload={file=>onUpload(line.id,'drawing',file)}/></div>}</div><QuoteMediaGallery media={media.filter(item=>item.lineId===line.id&&(item.category==='image'||item.category==='drawing'))}/></section>)}</div>;
}

function MediaUpload({label,category,disabled,onUpload,allowXlsx=false}:{label:string;category:QuoteMedia['category'];disabled:boolean;onUpload:(file:File)=>void;allowXlsx?:boolean}){
 return <label className={'cq-upload '+(disabled?'disabled':'')}><UploadCloud size={15}/>{label}<input aria-label={label} type="file" accept={category==='image'?'.png,.jpg,.jpeg':category==='sent_quote'&&allowXlsx?'.xlsx,.pdf,.png,.jpg,.jpeg':'.pdf,.png,.jpg,.jpeg'} disabled={disabled} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)onUpload(file);}}/></label>;
}

export function CustomerQuoteArchive({rows,search,scopeKey,request,onChanged,onPermissionError,onDirtyChange,disabled=false}:{rows:CompletedQuote[];search:string;scopeKey:string;request:Request;onChanged:()=>Promise<void>;onPermissionError:(error:unknown)=>void;onDirtyChange?:(dirty:boolean)=>void;disabled?:boolean}){
 const [filter,setFilter]=useState<'all'|'sent'|'unsent'>('all'),[query,setQuery]=useState(''),[archive,setArchive]=useState<ArchiveVersion|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[sentDate,setSentDate]=useState(today),[recipient,setRecipient]=useState(''),[channel,setChannel]=useState<QuoteSentRecord['channel']>('email'),[evidenceIds,setEvidenceIds]=useState<string[]>([]),[recording,setRecording]=useState(false),[formDirty,setFormDirty]=useState(false),[sentAcknowledged,setSentAcknowledged]=useState(false);
 const sequence=useRef(0),alive=useRef(false),archiveRef=useRef<HTMLElement|null>(null),idempotencyKey=useRef(clientId()),busyRef=useRef(false),callbacks=useRef({onChanged,onPermissionError,onDirtyChange});callbacks.current={onChanged,onPermissionError,onDirtyChange};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;sequence.current++;};},[]);
 useEffect(()=>{sequence.current++;setArchive(null);setError('');setNotice('');setRecording(false);setFormDirty(false);setSentAcknowledged(false);setBusy(false);busyRef.current=false;},[scopeKey]);
 useEffect(()=>{callbacks.current.onDirtyChange?.(formDirty);return()=>callbacks.current.onDirtyChange?.(false);},[formDirty]);
 useEffect(()=>{if(archive&&!rows.some(row=>row.quoteId===archive.quote.id&&row.quoteVersion===archive.quote.version)){sequence.current++;setArchive(null);setRecording(false);setFormDirty(false);setSentAcknowledged(false);setError('该报价版本当前不可访问，已清除其档案内容。');}},[rows,archive]);
 const text=[search,query].map(value=>value.trim().toLowerCase()).filter(Boolean);
 const visible=rows.filter(row=>{if(filter==='sent'&&row.quotedCustomer!=='Y'||filter==='unsent'&&row.quotedCustomer==='Y')return false;const haystack=[row.customerCode,row.customerName,row.quoteNo,row.model,row.factoryModel,row.customerModel,row.materialNumber,row.component,row.brand,row.businessType,row.descriptionZh,row.descriptionEn,...(row.media||[]).map(item=>item.filename)].join(' ').toLowerCase();return text.every(term=>haystack.includes(term));});
 const sent=rows.filter(row=>row.quotedCustomer==='Y').length;
 const safeError=(problem:unknown)=>{setError(problem instanceof Error?problem.message:'操作未完成，请重试。');const status=(problem as {status?:number})?.status;if(status&&[401,403,404].includes(status)){setArchive(null);setRecording(false);setFormDirty(false);setSentAcknowledged(false);callbacks.current.onPermissionError(problem);}};
 const begin=()=>{busyRef.current=true;setBusy(true);setError('');setNotice('');return ++sequence.current;};
 const finish=()=>{if(alive.current){busyRef.current=false;setBusy(false);}};
 const loadVersion=(quoteId:string,quoteVersion:number)=>request('customer-quote-version?quoteId='+encodeURIComponent(quoteId)+'&quoteVersion='+quoteVersion) as Promise<ArchiveVersion>;
 const openVersion=async(row:CompletedQuote,startRecording=false)=>{if(busyRef.current||disabled)return;if(formDirty&&!window.confirm('发送登记尚未提交。确定放弃本次输入并切换报价版本吗？'))return;const token=begin();try{const result=await loadVersion(row.quoteId,row.quoteVersion);if(!alive.current||token!==sequence.current)return;setArchive(result);setSentDate(today());setRecipient(result.quote.contactName||'');setChannel('email');setEvidenceIds([]);setRecording(startRecording);setFormDirty(false);setSentAcknowledged(false);idempotencyKey.current=clientId();window.requestAnimationFrame(()=>archiveRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}catch(problem){if(alive.current&&token===sequence.current)safeError(problem);}finally{finish();}};
 const closeArchive=()=>{if(busyRef.current||formDirty&&!window.confirm('发送登记尚未提交。确定放弃本次输入吗？'))return;sequence.current++;setArchive(null);setRecording(false);setFormDirty(false);setSentAcknowledged(false);setError('');setNotice('');};
 const upload=async(category:QuoteMedia['category'],file:File,lineId?:string)=>{if(!archive||busyRef.current||disabled)return;if(file.size>10*1024*1024||!file.size){setError('请上传大于 0 且不超过 10 MB 的附件。');return;}setSentAcknowledged(false);const token=begin(),{quote}=archive;try{const form=new FormData();form.set('quoteId',quote.id);form.set('quoteVersion',String(quote.version));form.set('category',category);if(lineId)form.set('lineId',lineId);form.set('file',file);await request('customer-quote-media-upload',form);const latest=await loadVersion(quote.id,quote.version);if(!alive.current||token!==sequence.current)return;setArchive(latest);setNotice('附件已补充归档到此历史版本；原报价内容及其他版本均未修改。请核实哪些文件实际随本次报价发送。');await callbacks.current.onChanged();}catch(problem){if(alive.current&&token===sequence.current)safeError(problem);}finally{finish();}};
 const recordSent=async()=>{if(!archive||busyRef.current||disabled||!sentAcknowledged)return;if(!sentDate||!recipient.trim()||!channel.trim()){setError('请填写实际发送日期、收件人及发送渠道。');return;}const token=begin();try{await request('customer-quote-record-sent',{quoteId:archive.quote.id,quoteVersion:archive.quote.version,sentDate,recipient:recipient.trim(),channel,mediaIds:evidenceIds,idempotencyKey:idempotencyKey.current});if(!alive.current||token!==sequence.current)return;setFormDirty(false);setSentAcknowledged(false);const latest=await loadVersion(archive.quote.id,archive.quote.version);if(!alive.current||token!==sequence.current)return;setArchive(latest);setRecording(false);setEvidenceIds([]);idempotencyKey.current=clientId();setNotice('已登记实际发送，总表“已报价客户”已标记为 Y（是）。没有向客户再次发送任何内容。');await callbacks.current.onChanged();}catch(problem){if(alive.current&&token===sequence.current)safeError(problem);}finally{finish();}};
 const touch=()=>{setFormDirty(true);setSentAcknowledged(false);setNotice('');};
 return <section className="panel cq-completed cq-no-print"><details open><summary>已完成报价清单总表 · {rows.length} 条</summary><p className="cq-help">已确认版本自动入表；真正发给客户后，请选择实际发送的版本“登记已发送”。图片／图纸按款、按版本归档；旧报价和旧附件不会被新文件覆盖。</p><div className="cq-archive-toolbar"><label>发送状态 <select value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="all">全部已确认</option><option value="unsent">已确认待发送</option><option value="sent">已发送客户</option></select></label><input aria-label="搜索已完成报价附件" value={query} onChange={event=>setQuery(event.target.value)} placeholder="客户／厂款／客款／材料号／部件／附件文件名"/><span>{sent} 条已发送 · {rows.length-sent} 条待登记</span><Button variant="outline" disabled={busy||disabled||!rows.length} asChild><a href="/api/workspace/customer-quote-completed-export" onClick={event=>{if(busy||disabled||!rows.length)event.preventDefault();}}><Download size={15}/>导出已完成报价总表</a></Button></div>
 {visible.length?<div className="cq-history-table"><table><thead><tr><th>客户编号</th><th>客户名称</th><th>品牌／业务类型</th><th>厂款／客款</th><th>材料号／部件</th><th>款式图片／图纸</th><th>产品描述</th><th>对客单价</th><th>报价类型／数量</th><th>报价单号</th><th>报价版本</th><th>确认时间</th><th>已报价客户</th><th>客户格式</th><th>档案与发送</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td>{row.customerCode||'未设编号'}</td><td>{row.customerName}</td><td>{[row.brand,row.businessType].filter(Boolean).join(' / ')||'—'}</td><td>{[row.factoryModel,row.customerModel].filter(Boolean).join(' / ')||row.model}</td><td>{[row.materialNumber,row.component].filter(Boolean).join(' / ')||'—'}</td><td className="cq-archive-media-cell"><QuoteMediaGallery compact media={(row.media||[]).filter(item=>item.lineId===row.lineId&&(item.category==='image'||item.category==='drawing'))}/></td><td className="cq-archive-description">{row.descriptionZh}</td><td>{row.currency||'USD'} {amount(row.unitPrice??((row.currency||'USD')==='USD'?row.unitPriceUsd:null))} / {unitLabel(row.unit)}</td><td>{row.quoteMode==='price_list'?'价目表':'订单报价'} · {row.quantity==null?'数量未指定':row.quantity}</td><td>{row.quoteNo}</td><td>R{row.quoteVersion}</td><td>{dateTime(row.confirmedAt)}</td><td>{row.quotedCustomer==='Y'?<span className="cq-sent-label">Y（是）</span>:<span className="cq-unsent-label">未登记发送</span>}{latestSentDate(row.sentHistory)&&<small className="cq-archive-last-sent">最近发送：{latestSentDate(row.sentHistory)}</small>}</td><td>{row.templateBinding?<a href={'/api/workspace/customer-quote-template-export?quoteId='+encodeURIComponent(row.quoteId)+'&quoteVersion='+row.quoteVersion}>下载 R{row.quoteVersion}</a>:'—'}</td><td><div className="cq-archive-row-actions"><Button size="sm" variant="outline" disabled={busy||disabled} onClick={()=>void openVersion(row)}>查看此版本</Button><Button size="sm" variant="outline" disabled={busy||disabled||row.canRegisterSent===false} onClick={()=>void openVersion(row,true)}>{row.quotedCustomer==='Y'?'查看／追加发送记录':'登记已发送'}</Button></div></td></tr>)}</tbody></table></div>:<p className="cq-placeholder">{rows.length?'没有符合筛选条件的已确认报价。':'暂无已确认报价。保存草稿不会生成已完成记录，也不会自动标记为已发送。'}</p>}
 {error&&<p className="error cq-message" role="alert">{error}</p>}{notice&&<p className="success cq-message" role="status">{notice}</p>}
 {archive&&<section ref={archiveRef} className="cq-version-archive" aria-label="报价版本档案"><div className="cq-section-heading"><div><h3><FileText size={17}/>{archive.quote.quoteNo} · R{archive.quote.version} · 已确认历史档案</h3><p className="cq-help">{archive.quote.customerName} · 报价日期 {archive.quote.quoteDate} · 有效期至 {archive.quote.validUntil||'未填写'} · 币种 {archive.quote.currency} · 此处不是当前修订草稿</p></div><Button variant="ghost" size="sm" disabled={busy} onClick={closeArchive}><X size={15}/>关闭档案</Button></div><p className="cq-archive-warning">以下为当时已确认的报价版本。新补传的附件会标注“确认后补充归档”，不代表原始报价或客户当时已经收到。</p>{archive.quote.quoteMode==='price_list'&&<p className="cq-price-list-note">价目表 · 数量可未指定，适用条件保留在各行及条款中；不计算订单总额。</p>}<div className="cq-history-table"><table><thead><tr><th>款号</th><th>英文描述</th><th>数量基准</th><th>对客单价（{archive.quote.currency}）</th><th>模具费（{archive.quote.currency}）</th></tr></thead><tbody>{archive.quote.lines.map(line=><tr key={line.id}><td>{line.model}{line.factoryModel&&<small className="cq-quantity-basis">厂款：{line.factoryModel}</small>}{line.customerModel&&<small className="cq-quantity-basis">客款：{line.customerModel}</small>}{line.materialNumber&&<small className="cq-quantity-basis">材料号：{line.materialNumber}</small>}</td><td className="cq-archive-description">{line.descriptionEn}{line.scopeNotesEn&&<small className="cq-scope-note">{line.scopeNotesEn}</small>}</td><td>{line.quantity==null?(archive.quote.quoteMode==='price_list'?'未指定':'待确认'):`${line.quantity} ${unitLabel(line.unit)}`}{line.quantityBasisEn&&<small className="cq-quantity-basis">{line.quantityBasisEn}</small>}</td><td>{archive.quote.currency} {amount(line.unitPrice)} / {unitLabel(line.unit)}</td><td>{line.toolingFee==null?'未单列':amount(line.toolingFee)}</td></tr>)}</tbody></table></div>{!!archive.quote.customerCharges?.length&&<section className="cq-archive-charges"><h4>此版本对客附加费用</h4><div className="cq-history-table"><table><thead><tr><th>费用项目</th><th>金额（{archive.quote.currency}）</th><th>计价说明</th></tr></thead><tbody>{archive.quote.customerCharges.map(charge=><tr key={charge.id}><td>{charge.labelEn}{charge.conditional&&<small className="cq-review-tag">Conditional charge · 条件性费用</small>}</td><td>{amount(charge.amount)}</td><td className="cq-archive-description">{charge.basisEn}</td></tr>)}</tbody></table></div></section>}<details className="cq-archive-terms"><summary>查看此版本英文条款</summary>{archive.quote.terms?.map(term=><p key={term.id}><b>{term.labelEn}</b> {term.en}</p>)}</details>
 <p className="cq-help">款式图片和图纸可供本客户的获授权同事查看。请勿上传供应商报价、内部成本截图或其他客户的资料。</p><QuoteLineMedia lines={archive.quote.lines} media={archive.media||[]} disabled={busy||disabled} canUpload={archive.quote.canSupplementArchive??!!archive.quote.canRevise} onUpload={(lineId,category,file)=>void upload(category,file,lineId)}/>
 <div className="cq-section-heading"><h3><ImageIcon size={17}/>实际发送文件与凭证</h3>{(archive.quote.canSupplementArchive??archive.quote.canRevise)&&<div className="cq-media-upload-actions"><MediaUpload label="上传已发报价文件" category="sent_quote" allowXlsx={!!archive.quote.templateBinding} disabled={busy||disabled} onUpload={file=>void upload('sent_quote',file)}/><MediaUpload label="上传邮件／聊天凭证" category="evidence" disabled={busy||disabled} onUpload={file=>void upload('evidence',file)}/></div>}</div><p className="cq-help">{archive.quote.templateBinding?'已绑定模板的此确认版本可上传客户 XLSX、PDF 或图片。XLSX 会与本版本的价格、物料和条款核对；价格变化需先修订并重新确认。':'此版本支持 PDF 或图片凭证，客户 XLSX 需要绑定模板并完成确认。'} 不上传包含其他客户、内部成本或无关个人信息的材料。附件保存不会自动登记发送。</p><QuoteMediaGallery emptyLabel="尚未上传实际发送的报价文件或凭证" media={(archive.media||[]).filter(item=>item.category==='sent_quote'||item.category==='evidence')}/>
 <div className="cq-section-heading"><h3>发送记录 · {archive.sentHistory?.length||0} 次</h3>{!recording&&(archive.quote.canRegisterSent??archive.quote.canRevise)&&<Button disabled={busy||disabled} onClick={()=>{setRecording(true);setFormDirty(false);setSentAcknowledged(false);}}>登记已发送</Button>}</div>{archive.sentHistory?.length?<div className="cq-history-table"><table><thead><tr><th>实际发送日期</th><th>收件人</th><th>渠道</th><th>登记信息</th><th>关联凭证</th></tr></thead><tbody>{archive.sentHistory.map(record=><tr key={record.id}><td>{record.sentDate}</td><td>{record.recipient}</td><td>{channelLabels[record.channel]||record.channel}</td><td>{record.createdBy||'—'}<br/>{record.createdAt?dateTime(record.createdAt):''}</td><td><div className="cq-record-file-links">{(record.mediaIds||[]).map(id=>{const media=archive.media.find(item=>item.id===id);return media?<a href={fileHref(media,isXlsx(media))} target="_blank" rel="noreferrer" key={id}>{media.filename}</a>:null;})}{!record.mediaIds?.length&&'未附凭证'}</div></td></tr>)}</tbody></table></div>:<p className="cq-help">暂无发送记录；确认英文报价不等于已发给客户。</p>}
 {recording&&(archive.quote.canRegisterSent??archive.quote.canRevise)&&<form className="cq-sent-form" onSubmit={event=>{event.preventDefault();void recordSent();}}><fieldset disabled={busy||disabled}><legend>登记实际已发送的报价 · R{archive.quote.version}</legend><p>请核对上述版本与实际发给客户的内容一致。这只是登记存档，不会重新发送。</p><div className="cq-form-grid"><label className="cq-field"><span>实际发送日期</span><input type="date" required value={sentDate} max={today()} onChange={event=>{setSentDate(event.target.value);touch();}}/></label><label className="cq-field"><span>收件人／邮箱</span><input required maxLength={240} value={recipient} onChange={event=>{setRecipient(event.target.value);touch();}}/></label><label className="cq-field"><span>发送渠道</span><select value={channel} onChange={event=>{setChannel(event.target.value as QuoteSentRecord['channel']);touch();}}>{Object.entries(channelLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><p className="cq-help">勾选上方已归档的“已发报价文件”或“邮件／聊天凭证”（可选）。只有勾选的凭证会关联到本次发送记录。</p><div className="cq-evidence-options">{archive.media.filter(media=>media.category==='sent_quote'||media.category==='evidence').map(media=><label key={media.id}><input type="checkbox" checked={evidenceIds.includes(media.id)} onChange={event=>{setEvidenceIds(ids=>event.target.checked?[...ids,media.id]:ids.filter(id=>id!==media.id));touch();}}/>{media.filename}<small>{media.supplement?'确认后补充归档':'报价版本附件'}</small></label>)}</div><div className="cq-evidence-options cq-archive-warning"><label><input type="checkbox" checked={sentAcknowledged} disabled={busy||disabled||!sentDate||!recipient.trim()} onChange={event=>{setSentAcknowledged(event.target.checked);setFormDirty(true);setNotice('');}}/><span>我确认报价单 <b>{archive.quote.quoteNo} · R{archive.quote.version}</b> 已于 <b>{sentDate||'未填写日期'}</b> 通过 <b>{channelLabels[channel]}</b> 发送给 <b>{recipient.trim()||'未填写收件人'}</b>，且所选凭证与本次实际发送一致。本操作<b>只登记存档，不会再次向客户发送</b>消息或文件。</span></label></div><div className="cq-media-upload-actions"><Button type="submit" disabled={busy||disabled||!sentAcknowledged}>确认登记已发送</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>{if(!formDirty||window.confirm('放弃本次尚未提交的发送登记？')){setRecording(false);setFormDirty(false);setSentAcknowledged(false);}}}>取消登记</Button></div></fieldset></form>}
 </section>}</details></section>;
}
