'use client';
import {LedgerEditor} from './ledger-panels';
import {departmentColumns} from '@/lib/departments';
import {warehouse,outstanding,currentStage,colLabels} from '@/lib/ledger';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Paperclip,Save,Plus} from 'lucide-react';
import {Choice,Field,Input,Grid,dateTime,type Act} from './ui';
import type {Data} from './workspace';
import {allowedFields,fields,fieldLabels,packed,progress,stages,type Order} from '@/lib/domain';
export function DetailPanel({order,data,onClose,onSelect,act,busy}:{order:Order;data:Data;onClose:()=>void;onSelect:(o:Order)=>void;act:Act;busy:boolean}){return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="dialog-scroll sm:max-w-[1000px]"><Detail key={order.id+':'+order.version} order={order} data={data} onClose={onClose} onSelect={onSelect} act={act} busy={busy}/></DialogContent></Dialog>;}
function Detail({order:o,data,onClose,onSelect,act,busy}:any){
 const [draft,setDraft]=useState<Order>({...o}),[error,setError]=useState(''),[text,setText]=useState(''),[due,setDue]=useState('');const permitted=allowedFields(data.me,o),canFollow=permitted.length>0||departmentColumns(data.me,o).length>0,reports=data.reports.filter((r:any)=>r.lineId===o.id),comments=data.comments.filter((c:any)=>c.lineId===o.id),audits=data.audits.filter((c:any)=>c.lineId===o.id),siblings=data.orders.filter((s:Order)=>s.orderNo===o.orderNo);
 async function save(){try{await act('edit-order',{id:o.id,version:o.version,patch:Object.fromEntries(permitted.filter(k=>JSON.stringify((draft as any)[k])!==JSON.stringify(o[k])).map(k=>[k,(draft as any)[k]]))});onClose();}catch(e){setError((e as Error).message);}}
 async function comment(){try{await act('comment',{lineId:o.id,text,dueDate:due});setText('');setDue('');setError('');}catch(e){setError((e as Error).message);}}
 return <><DialogHeader><DialogTitle>{o.orderNo} <span className="font-normal text-slate-500">/ {o.customer}</span></DialogTitle><DialogDescription>{o.drawing} · {o.color} · {o.lens} · {o.batch||'未分批'}　明细版本 {o.version}</DialogDescription></DialogHeader>
 {error&&<div className="error" role="alert">{error}</div>}
 {siblings.length>1&&<Choice label="同单其他明细" value={o.id} onChange={id=>onSelect(siblings.find((s:Order)=>s.id===id))} options={siblings.map((s:Order)=>({value:s.id,label:`${s.drawing} / ${s.color} / ${s.lens} / ${s.batch||'未分批'}`}))}/>}
 <div className="detail-summary"><div><span>订单数量</span><b>{o.quantity.toLocaleString()} 副</b></div><div><span>包装入仓</span><b>{(warehouse(o)??0).toLocaleString()} 副</b></div><div><span>当前进度</span><b>{o.ledger?currentStage(o):progress(o,reports)}</b></div></div>
 <Tabs defaultValue={o.ledger?'ledger':'follow'}><TabsList className="w-full justify-start">{o.ledger&&<TabsTrigger value="ledger">部门工序 / 归档</TabsTrigger>}<TabsTrigger value="follow">订单跟进</TabsTrigger><TabsTrigger value="production">包装报工</TabsTrigger><TabsTrigger value="history">修改历史</TabsTrigger><TabsTrigger value="extra">补充字段</TabsTrigger></TabsList>
 {o.ledger&&<TabsContent value="ledger"><LedgerEditor order={o} data={data} act={act} busy={busy} onClose={onClose}/></TabsContent>}<TabsContent value="follow"><div className="note mt-3">正式订单字段来源于金蝶 / PMC 导入：客户要求交期 {o.requestedDate||'待确认'}，客户 PO {o.customerPO||'—'}，来源状态 {o.sourceStatus}。如源单错误，请更正源单后重新导入。</div><div className="form-grid mt-5">{['ownerEmail','stage','plannedDate','shipDate','promisedDate','promiseConfirmed','customerNote','arrangement','notes'].map(k=><Field key={k} label={fieldLabels[k]} wide={['notes','arrangement','customerNote'].includes(k)}>{k==='ownerEmail'?<Choice label={fieldLabels[k]} value={draft.ownerEmail} onChange={v=>setDraft({...draft,ownerEmail:v})} disabled={!permitted.includes(k)} options={[{value:'',label:'待分配'},...data.members.filter((m:any)=>m.active).map((m:any)=>({value:m.email,label:m.name+' · '+m.email}))]}/>:k==='stage'?<Choice label={fieldLabels[k]} value={draft.stage} onChange={v=>setDraft({...draft,stage:v})} disabled={!permitted.includes(k)} options={stages.map(v=>({value:v,label:v}))}/>:k==='promiseConfirmed'?<label className="flex items-center gap-3 h-10"><Checkbox aria-label="确认回复交期" checked={draft.promiseConfirmed} onCheckedChange={v=>setDraft({...draft,promiseConfirmed:!!v})} disabled={!permitted.includes(k)}/><span>已确认可对客回复</span></label>:['notes','arrangement','customerNote'].includes(k)?<Textarea aria-label={fieldLabels[k]} value={(draft as any)[k]} disabled={!permitted.includes(k)} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>:<Input aria-label={fieldLabels[k]} type="date" value={(draft as any)[k]} onInput={e=>setDraft({...draft,[k]:e.currentTarget.value,...(k==="promisedDate"?{promiseConfirmed:false}:{})})} disabled={!permitted.includes(k)} onChange={e=>setDraft({...draft,[k]:e.target.value,...(k==='promisedDate'?{promiseConfirmed:false}:{})})}/>}</Field>)}</div>
 {permitted.length>0&&<div className="action-row"><Button disabled={busy} onClick={save}><Save/>保存跟进字段</Button></div>}
 <h3 className="section-title mt-7">跟进记录与待办</h3>{comments.map((c:any)=><div className="history-item" key={c.id}><div className="flex justify-between gap-3"><b className="wrap">{c.text}</b>{c.dueDate&&<label className="flex items-center gap-2 whitespace-nowrap"><Checkbox aria-label={'完成待办'+c.text} checked={c.done} disabled={!canFollow||busy} onCheckedChange={v=>act('task',{id:c.id,done:!!v}).catch((e:Error)=>setError(e.message))}/>{c.done?'已完成':c.dueDate+' 前跟进'}</label>}</div><p className="muted">{c.actor} · {dateTime(c.createdAt)}</p></div>)}
 {canFollow&&<div className="mt-4"><Textarea aria-label="新增跟进记录" placeholder="记录进度核对、问题和下一步安排…" value={text} onChange={e=>setText(e.target.value)}/><div className="toolbar"><Field label="下次跟进日期（选填）"><Input type="date" aria-label="下次跟进日期" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></Field><Button disabled={busy||!text.trim()} onClick={comment}><Plus/>添加跟进</Button></div></div>}
 <h3 className="section-title mt-7">附件</h3>{data.attachments.filter((f:any)=>f.lineId===o.id).map((f:any)=><div className="source-line" key={f.id}><a className="text-link flex gap-2 items-center" href={'/api/workspace/file?id='+f.id}><Paperclip size={15}/>{f.filename}</a><span className="muted">{f.actor} · {dateTime(f.createdAt)}</span></div>)}{permitted.length>0&&<Input className="mt-3" type="file" aria-label="添加订单附件" accept=".pdf,.xlsx,.xls,.csv,.png,.jpg,.jpeg,.webp,.docx" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.set('file',file);form.set('lineId',o.id);try{await act('attachment',form);e.target.value='';}catch(err){setError((err as Error).message);}}}/>}</TabsContent>
 <TabsContent value="production"><p className="note mt-4">包装良品数只读。错误请在“MES 核对”提交更正申请。包装足量仍须验收，不自动代表入仓或出货。</p><Grid headers={['报工时间','工单号','良品数','审批状态','来源']} rows={reports.map((r:any)=>[r.reportedAt,r.workOrder,r.quantity,<span className="pill">{r.approval}</span>,r.source])}/></TabsContent>
 <TabsContent value="history"><p className="note mt-4">最近 250 条可见变更中的本明细记录。原始版本保存在后台，导入文件可从导入记录下载。</p>{audits.map((a:any)=><div className="history-item" key={a.id}><div><b>{a.action}</b> · {a.actor} <span className="muted">{dateTime(a.createdAt)}</span></div><p className="muted wrap">{a.source}</p>{a.before?.ledger&&a.after?.ledger&&Object.keys(colLabels).filter(k=>a.before.ledger.columns[k]!==a.after.ledger.columns[k]).map(k=><div className="wrap" key={k}>{colLabels[k]}：{a.before.ledger.columns[k]||'空'} → {a.after.ledger.columns[k]||'空'}</div>)}{a.before?.kind==='order'&&a.after?.kind==='order'&&fields.filter(([k])=>a.before[k]!==a.after[k]).map(([k,l])=><div key={k} className="wrap">{l}：<del>{String(a.before[k]||'空')}</del> → {String(a.after[k]||'空')}</div>)}</div>)}</TabsContent>
 <TabsContent value="extra"><Grid headers={['原表字段','内容']} rows={Object.entries(o.extra||{}).map(([k,v])=>[k,<span className="wrap">{String(v)}</span>])}/><p className="note mt-4">原表内容与导入时的计算缓存保留供追溯；当前工序和重算欠数以“部门工序”页为准。</p></TabsContent></Tabs></>;
}
