'use client';
import {useEffect,useMemo,useState} from 'react';
import {Download,FileImage,Languages,Save,Send} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input,Empty,type Act} from './ui';
import type {Data} from './workspace';
import {productTypeOf,type Order} from '@/lib/domain';
type FactoryOrder={id:string;lineId:string;version:number;status:string;sourceEnglish:string;chineseProcess:string;materialSpec:string;platingSpec:string;lensSpec:string;materialImageConfirmed:boolean;createdAt:string};
const blank={sourceEnglish:'',chineseProcess:'',materialSpec:'',platingSpec:'',lensSpec:'',materialImageConfirmed:false};
export function FactoryOrderPanel({data,act,busy}:{data:Data;act:Act;busy:boolean}){
 const [items,setItems]=useState<FactoryOrder[]>([]),[selected,setSelected]=useState<Order|null>(null),[draft,setDraft]=useState<any>(blank),[q,setQ]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/workspace/factory-orders').then(r=>r.json()).then(v=>setItems((v as {items?:FactoryOrder[]}).items||[])).catch(()=>setError('内部订单版本加载失败。'));},[]);
 const latest=useMemo(()=>{const m=new Map<string,FactoryOrder>();for(const x of items)if(!m.has(x.lineId)||m.get(x.lineId)!.version<x.version)m.set(x.lineId,x);return m;},[items]),rows=data.orders.filter(o=>!q||[o.orderNo,o.customer,o.customerPO,o.drawing,o.color,productTypeOf(o)].join(' ').toLowerCase().includes(q.toLowerCase()));
 const open=(o:Order)=>{setSelected(o);const v=latest.get(o.id);setDraft(v?{sourceEnglish:v.sourceEnglish,chineseProcess:v.chineseProcess,materialSpec:v.materialSpec,platingSpec:v.platingSpec,lensSpec:v.lensSpec,materialImageConfirmed:v.materialImageConfirmed}:{...blank,sourceEnglish:o.extra?.['客户英文描述']||o.specialRequirements||'',lensSpec:o.lens||''});setNotice('');setError('');};
 const save=async(action:string)=>{if(!selected)return;setError('');try{const r=await act('factory-order-save',{lineId:selected.id,...draft,action});setItems(v=>[...v,r.item]);setNotice(action==='release'?'已生成工厂下发版本。':'内部订单版本已保存。');}catch(e){setError((e as Error).message);}};
 const current=selected?latest.get(selected.id):undefined,attachments=selected?data.attachments.filter((f:any)=>f.lineId===selected.id):[];
 return <div className="collab-workspace"><section className="collab-hero service"><div><span className="section-kicker">BILINGUAL FACTORY ORDER</span><h2>中英对照内部订单</h2><p>保留客户原文，客服确认中文工艺，PMC 补齐板料和生产图片后下发工厂。</p></div><Languages size={52}/></section>{notice&&<div className="success mt-4">{notice}</div>}{error&&<div className="error mt-4">{error}</div>}
 <section className="panel"><div className="panel-tools"><b>待转换订单 <span className="muted">{rows.length} 条</span></b><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索订单、客户、PO、产品类型、图号或色号"/></div><div className="order-table"><table><thead><tr><th>订单 / 客户</th><th>产品类型</th><th>图号·客色</th><th>数量</th><th>内部订单状态</th><th>操作</th></tr></thead><tbody>{rows.length?rows.slice(0,100).map(o=>{const v=latest.get(o.id);return <tr key={o.id}><td><b>{o.orderNo}</b><span className="subline">{o.customer} · {o.customerPO||'无 PO'}</span></td><td><b>{productTypeOf(o)||'未填写'}</b></td><td>{o.drawing}<span className="subline">{o.color}</span></td><td>{o.quantity.toLocaleString()}</td><td><span className={'pill '+(v?.status.includes('已下发')?'green':v?'amber':'')}>{v?`${v.status} · R${v.version}`:'未建内部订单'}</span></td><td><Button size="sm" variant="outline" onClick={()=>open(o)}>编辑转换</Button></td></tr>}):<tr><td colSpan={6}><Empty title="没有可转换的订单" detail="请先上传客户原始订单。"/></td></tr>}</tbody></table></div></section>
 {selected&&<section className="panel section-pad mt-5"><div className="panel-title"><div><h3>{selected.orderNo} · {selected.drawing} · {selected.color}</h3><p className="subtitle">{selected.customer} · {selected.customerPO||'无 PO'} · {selected.quantity} 副{current?` · 当前 R${current.version}`:''}</p></div>{current&&<Button variant="outline" asChild><a href={'/api/workspace/factory-order-export?id='+current.id}><Download/>导出内部订单</a></Button>}</div>
 <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-5"><label><b>客户英文原文</b><textarea className="w-full min-h-48 mt-2" value={draft.sourceEnglish} onChange={e=>setDraft({...draft,sourceEnglish:e.target.value})} placeholder="保留客户原文，不覆盖、不机器直译"/></label><label><b>工厂中文工艺</b><textarea className="w-full min-h-48 mt-2" value={draft.chineseProcess} onChange={e=>setDraft({...draft,chineseProcess:e.target.value})} placeholder="按圈、脾、烟斗、叶子、螺丝、角花、庄头等逐项确认"/></label></div>
 <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4"><Input value={draft.materialSpec} onChange={e=>setDraft({...draft,materialSpec:e.target.value})} placeholder="板料编码 / 板料色"/><Input value={draft.platingSpec} onChange={e=>setDraft({...draft,platingSpec:e.target.value})} placeholder="电镀颜色 / 工艺"/><Input value={draft.lensSpec} onChange={e=>setDraft({...draft,lensSpec:e.target.value})} placeholder="镜片规格"/></div>
 <div className="mt-5"><b>生产资料与图片</b>{attachments.map((f:any)=><div className="source-line" key={f.id}><a className="text-link" href={'/api/workspace/file?id='+f.id}>{f.filename}</a><span className="muted">{f.actor}</span></div>)}<Input className="mt-3" type="file" accept=".png,.jpg,.jpeg,.webp,.pdf,.xlsx,.docx" onChange={async e=>{const f=e.target.files?.[0];if(!f||!selected)return;const form=new FormData();form.set('file',f);form.set('lineId',selected.id);try{await act('attachment',form);setNotice('生产资料已上传，刷新页面后可查看。');e.target.value='';}catch(err){setError((err as Error).message);}}}/><label className="flex items-center gap-3 mt-3"><input type="checkbox" checked={!!draft.materialImageConfirmed} onChange={e=>setDraft({...draft,materialImageConfirmed:e.target.checked})}/><span>PMC 已核对板料图片 / 生产参考图</span></label></div>
 <div className="row-actions mt-5"><Button variant="outline" disabled={busy} onClick={()=>save('draft')}><Save/>保存草稿</Button><Button variant="outline" disabled={busy} onClick={()=>save('service-confirm')}><Languages/>客服确认双语</Button><Button variant="outline" disabled={busy} onClick={()=>save('pmc-confirm')}><FileImage/>PMC确认补图</Button><Button disabled={busy} onClick={()=>save('release')}><Send/>下发工厂</Button></div></section>}</div>;
}
