'use client';
import {useState} from 'react';
import {UploadCloud,FileSpreadsheet,Check,ArrowRight,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Textarea} from '@/components/ui/textarea';
import {Input,Field,Choice,Grid,request,dateTime,type Act} from './ui';
import type {Data} from './workspace';
import {fields,fieldLabels,type PreviewRow} from '@/lib/domain';
const labels={new:'新增',update:'可合并',conflict:'需核对',skip:'无变化',error:'不能导入'};
export function ImportPanel({data,act,busy}:{data:Data;act:Act;busy:boolean}){
 const [type,setType]=useState('orders'),[file,setFile]=useState<File|null>(null),[sheet,setSheet]=useState(''),[header,setHeader]=useState('1'),[info,setInfo]=useState<any>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[lensMapping,setLensMapping]=useState<Record<string,string>>({}),[job,setJob]=useState<any>(null),[selected,setSelected]=useState<number[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const canOrders=['admin','pmc','clerk'].includes(data.me.role),canMES=['admin','pmc'].includes(data.me.role);
 function form(f=file,sh=sheet,hr=header){const form=new FormData();if(f)form.set('file',f);form.set('sheet',sh);form.set('header',hr);form.set('type',type);form.set('mapping',JSON.stringify(mapping));form.set('lensMapping',JSON.stringify(lensMapping));return form;}
 async function inspect(f=file,sh=sheet,hr=header){if(!f)return;setLoading(true);setError('');setJob(null);setInfo(null);setFile(f);try{const result=await request('inspect',form(f,sh,hr));setInfo(result);setSheet(result.sheet);setMapping(result.mapping);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function preview(){if(!file)return;setError('');try{const result=await act('preview',form());setJob(result);setSelected(result.rows.filter((r:PreviewRow)=>['new','update'].includes(r.status)).map((r:PreviewRow)=>r.index));}catch(e){setError((e as Error).message);}}
 async function submit(){try{const result=await act('commit-import',{id:job.id,selected,reason});setJob({...job,status:'已提交',applied:result.count});}catch(e){setError((e as Error).message);}}
 async function loadJob(id:string){try{const result=await request('job?id='+encodeURIComponent(id));setJob(result);setSelected(result.rows.filter((r:PreviewRow)=>['new','update'].includes(r.status)).map((r:PreviewRow)=>r.index));setType(result.importType);setError('');}catch(e){setError((e as Error).message);}}
 return <div className="space-y-5"><section className="panel section-pad"><div className="flex items-start justify-between gap-5 flex-wrap"><div><h2 className="section-title">将工作表更新到总表</h2><p className="subtitle">选择工作表 → 对应字段 → 核对差异 → 确认合并</p></div><Tabs value={type} onValueChange={v=>{setType(v);setJob(null);setFile(null);setInfo(null);}}><TabsList><TabsTrigger value="orders">PMC / 文员订单表</TabsTrigger><TabsTrigger value="mes" disabled={!canMES}>MES 包装报工</TabsTrigger></TabsList></Tabs></div>
 {error&&<div className="error mt-5" role="alert">{error}</div>}
 {!canOrders?<div className="note mt-5">此账号可查询和导出授权报表。订单导入由 PMC 或负责该订单的文员操作。</div>:<><div className="upload-zone mt-5"><UploadCloud size={31} className="mx-auto mb-3 text-emerald-800"/><b>{file?file.name:'选择需要汇总的工作表'}</b><p className="subtitle">支持 XLSX、XLS、UTF-8 CSV · 每批最多 200 条 · 文件不超过 10 MB</p><Input key={type} type="file" accept=".xlsx,.xls,.csv" aria-label="上传工作表" disabled={busy||loading} onChange={e=>{const f=e.target.files?.[0];if(f){setSheet('');setHeader('1');inspect(f,'','1');}}}/></div>
 <div className="toolbar"><Button variant="outline" asChild><a href={'/api/workspace/template?type='+type}><Download/>下载{type==='mes'?'报工整理':'订单导入'}模板</a></Button><span className="muted">{type==='mes'?'可直接上传 MES 官方包装报工导出；报工原始文件不应包含公式。':'建议先从订单总表导出可回传工作表；空白不清空原值。'}</span></div>
 {loading&&<p role="status">正在识别工作表…</p>}
 {info&&<><div className="form-grid"><Field label="工作表"><Choice label="工作表" value={sheet} onChange={v=>{setSheet(v);inspect(file,v);}} options={info.sheets.map((s:string)=>({value:s,label:s}))}/></Field><Field label="表头所在行"><div className="flex gap-2"><Input type="number" min={1} max={50} aria-label="表头所在行" value={header} onChange={e=>setHeader(e.target.value)}/><Button variant="outline" onClick={()=>inspect()} disabled={loading}>重新识别</Button></div></Field></div><p className="note mt-4">已识别 {info.headers.filter(Boolean).length} 列、{info.rowCount} 条记录。请确认表头行正确；合并表头可指定实际字段名所在行。</p>
 {type==='orders'?<><h3 className="section-title mt-6">字段对应</h3><div className="mapping-grid">{fields.map(([key,label])=><Field key={key} label={label+(['orderNo','drawing','color','lens'].includes(key)?' *':'')}><Choice label={'映射'+label} value={mapping[key]||''} onChange={v=>{setMapping({...mapping,[key]:v});setJob(null);}} options={[{value:'',label:'不导入此字段'},...[...new Set(info.headers.filter(Boolean) as string[])].map(h=>({value:h,label:h}))]}/></Field>)}</div><p className="muted mt-4">其他有名称的列将保留为补充字段，可在详情及“显示列”中查看。未识别的公式、流程和提醒需按完整原表另行核对。</p></>:<><h3 className="section-title mt-6">镜片编码对应</h3><p className="subtitle">仅当已确认实际业务含义时选择。未确认编码保留为未匹配报工，稍后人工关联。</p><div className="form-grid mt-4">{['AC','SUN'].map(code=><Field key={code} label={code+' 对应镜片'}><Choice label={code+' 对应镜片'} value={lensMapping[code]||''} onChange={v=>{setLensMapping({...lensMapping,[code]:v});setJob(null);}} options={[{value:'',label:'尚未确认'},{value:'白片',label:'白片'},{value:'太阳片',label:'太阳片'}]}/></Field>)}</div><p className="note mt-4">只汇总已审批、已关联的包装良品数。未出现在本次文件中的旧报工不会被删除；撤销、反审核或更正请导入包含对应状态的来源记录。</p></>}
 <div className="action-row"><Button onClick={preview} disabled={busy||loading||!file}><ArrowRight/>生成差异预览</Button></div></>}
 </>}
 </section>
 {job&&<section className="panel"><div className="section-pad"><div className="flex justify-between items-center"><div><h2 className="section-title">差异预览 · {job.filename}</h2><p className="subtitle">{job.status==='已提交'?`已提交 ${job.applied||0} 条；重复提交不会再计数。`:'逐行选择要合并的记录。冲突行默认不选中，核对后才能提交。'}</p></div><span className={'pill '+(job.status==='已提交'?'green':'amber')}>{job.status}</span></div><div className="toolbar">{Object.entries(labels).map(([k,label])=><span key={k} className={'pill '+(k==='error'?'red':k==='conflict'?'amber':'')}>{label} {(job.rows as PreviewRow[]).filter(r=>r.status===k).length}</span>)}</div></div>
 <Grid headers={['选择','原表行','结果','明细 / 报工','变更内容与核对事项']} rows={(job.rows as PreviewRow[]).map(r=>[
 <Checkbox aria-label={'选择第'+r.index+'行'} disabled={job.status==='已提交'||['error','skip'].includes(r.status)||busy} checked={selected.includes(r.index)} onCheckedChange={v=>setSelected(v?[...new Set([...selected,r.index])]:selected.filter(i=>i!==r.index))}/>,r.index,<span className={'pill '+(r.status==='error'?'red':r.status==='conflict'?'amber':'green')}>{labels[r.status]}</span>,<div><b>{r.after?.orderNo||'—'}</b><span className="subline">{r.after?.drawing} · {r.after?.color} · {r.after?.lens||'镜片待确认'}</span></div>,<div className="wrap diff-cell">{r.reason&&<p className={r.status==='error'?'text-red-700':'text-amber-800'}>{r.reason}</p>}{r.status!=='error'&&r.changes?.filter(k=>k!=='extra'&&(r.before||r.after?.[k]!=='')).map(k=><div key={k}><span>{fieldLabels[k]||({approval:'审批状态',lineId:'订单关联',reportedAt:'报工时间'} as any)[k]||k}：</span><del>{String(r.before?.[k]??'空')}</del> → <b>{String(r.after?.[k]??'空')}</b></div>)}{r.changes?.includes('extra')&&<p>补充字段将保留。</p>}</div>])}/>
 {job.status!=='已提交'&&<div className="section-pad"><Field label="冲突核对依据（选择冲突行时必填）"><Textarea aria-label="冲突核对依据" value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：已核对金蝶最新订单导出，以本批交期为准。"/></Field><div className="action-row"><Button variant="outline" onClick={()=>setSelected(job.rows.filter((r:PreviewRow)=>['new','update'].includes(r.status)).map((r:PreviewRow)=>r.index))}>仅选择新增与可合并</Button><Button disabled={busy||!selected.length} onClick={submit}><Check/>确认合并 {selected.length} 条</Button></div></div>}</section>}
 <section className="panel"><div className="section-pad"><h2 className="section-title">导入记录</h2><p className="subtitle">原始文件、操作者与每次合并结果均可追溯。</p></div><Grid headers={['来源文件','上传人','时间','状态','操作']} rows={data.imports.map(j=>[<div className="flex gap-2 items-center"><FileSpreadsheet size={18}/>{j.filename}</div>,j.actor,dateTime(j.createdAt),<span className={'pill '+(j.status==='已提交'?'green':'amber')}>{j.status}</span>,<div className="flex gap-3"><Button variant="ghost" size="sm" onClick={()=>loadJob(j.id)}>查看差异</Button><Button variant="ghost" size="sm" asChild><a href={'/api/workspace/file?id='+j.id}>原始文件</a></Button></div>])}/></section></div>;
}
