'use client';
import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {Textarea} from '@/components/ui/textarea';
import {Download,ArrowUpRight,AlertTriangle,Archive,CheckCircle2,UploadCloud,Save} from 'lucide-react';
import {Choice,Field,Grid,Input,Empty,dateTime,request,type Act} from './ui';
import {active,automaticDates,balance,colLabels,currentStage,dateCols,dateValue,days,issues,numeric,outstanding,overdue,ownerLabel,promisedDue,stageDefs,stageNumbers,today,warehouse} from '@/lib/ledger';
import {departmentColumns,departments} from '@/lib/departments';
import {broad,type Order} from '@/lib/domain';
import type {Data} from './workspace';
const fmt=(n:number|null|undefined)=>n===null||n===undefined?'待核对':n.toLocaleString('zh-CN');
type Props={data:Data;act:Act;busy:boolean;openOrder:(o:Order)=>void};
function Export({mode,filters={}}:{mode:string;filters?:Record<string,string>}){return <Button variant="outline" asChild><a href={'/api/workspace/ledger-export?'+new URLSearchParams({mode,...filters})}><Download size={16}/>导出当前明细</a></Button>;}
export function LedgerImport({data,act,busy}:Omit<Props,'openOrder'>){
 const [mode,setMode]=useState('active'),[job,setJob]=useState<any>(null),[running,setRunning]=useState(false),[error,setError]=useState('');
 async function upload(file:File){setRunning(true);setError('');try{const form=new FormData();form.set('file',file);form.set('mode',mode);setJob(await act('ledger-preview',form));}catch(e){setError((e as Error).message);}finally{setRunning(false);}}
 async function run(){setRunning(true);setError('');let j=job;try{while(j.status!=='已完成'){j=await request('ledger-commit',{id:j.id,offset:j.offset});setJob(j);}await act('enroll',{});}catch(e){setError((e as Error).message);}finally{setRunning(false);}}
 return <section className="panel section-pad mb-5"><div className="section-kicker">原表迁移 / 追加订单</div><h2 className="section-title">度昂原版工作簿导入</h2><p className="subtitle">自动读取“动态表”第 3 行表头，保留全部工序、备注和原始行号。计算页由网站实时汇总。</p><div className="toolbar"><Choice label="原表导入用途" value={mode} onChange={v=>{setMode(v);setJob(null);}} disabled={running} options={[{value:'active',label:'在制订单 → 动态总表'},{value:'archived',label:'PMC 已完成订单 → 档案' }]}/><Input type="file" aria-label="上传度昂原版工作簿" accept=".xlsx" disabled={busy||running||!broad(data.me)} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);}}/></div>
 {error&&<p className="error" role="alert">{error}</p>}{job&&<div className="import-review"><h3>{job.filename}</h3><div className="stat-strip"><span>原始明细 <b>{fmt(job.summary.rows)}</b></span><span>订单数量 <b>{fmt(job.summary.quantity)}</b></span><span>待导入 <b>{fmt(job.total)}</b></span><span>保留待核对 <b>{fmt(job.summary.heldRows)}</b></span></div><p className="note">同键多行保留独立明细，不自动合并。与网站已有记录重合的行暂不覆盖，后续修改请用“可回传工作表”或部门录入。归档范围按上传用途确定。</p><Grid headers={['原表行','订单号','款号','数量']} rows={job.sample.map((r:any)=>[r.row,r.orderNo,r.drawing||'缺款号',r.quantity])}/><div className="toolbar"><Button disabled={running||job.status==='已完成'} onClick={run}>{job.status==='已完成'?'已完成导入':running?'正在写入…':job.offset?'继续导入剩余明细':'确认导入此工作簿'}</Button><span>{job.offset} / {job.total} 行 · {job.status}</span></div><Progress value={job.total?job.offset/job.total*100:100}/></div>}
 {(data.ledgerImports||[]).length>0&&<details className="mt-5"><summary>原表导入记录与源文件</summary><Grid headers={['工作簿','用途','已导入','操作']} rows={(data.ledgerImports||[]).map((j:any)=>[j.filename,j.mode==='active'?'在制':'档案',`${j.offset}/${j.total} · ${j.status}`,<div className="flex gap-2"><a className="text-link" href={'/api/workspace/ledger-file?id='+j.id}>下载原文件</a>{j.status!=='已完成'&&<button className="text-link" onClick={()=>setJob(j)}>继续此批次</button>}</div>])}/></details>}</section>;
}
export function Dashboard({data,openOrder}:Props){
 const [customer,setCustomer]=useState(''),[owner,setOwner]=useState(''),[month,setMonth]=useState(''),[exception,setException]=useState('交期逾期'),[page,setPage]=useState(0),[stage,setStage]=useState(''),[capacity,setCapacity]=useState('400');
 const source=data.orders.filter(active),rows=source.filter(o=>(!customer||o.customer===customer)&&(!owner||ownerLabel(o)===owner)&&(!month||promisedDue(o).startsWith(month))),quantity=rows.reduce((n,o)=>n+o.quantity,0),remaining=rows.reduce((n,o)=>n+Math.max(0,outstanding(o)??0),0),over=rows.reduce((n,o)=>n+Math.max(0,-(outstanding(o)??0)),0),late=rows.filter(overdue),selected=stageDefs.find(d=>d.id===stage),bad=rows.filter(o=>selected?(stageNumbers(o,selected).wip||0)>0:!exception||issues(o).includes(exception));
 const summary=stageDefs.map(d=>{const vals=rows.map(o=>stageNumbers(o,d));return {...d,debt:vals.reduce((n,v)=>n+(v.debt||0),0),wip:vals.reduce((n,v)=>n+(v.wip||0),0),invalid:vals.filter(v=>v.invalid).length,late:vals.filter(v=>(v.age||0)>d.limit).length};});
 const grouped=(key:(o:Order)=>string)=>{const map=new Map<string,{name:string;rows:number;quantity:number;remaining:number;late:number}>();for(const o of rows){const name=key(o)||'未填写',v=map.get(name)||{name,rows:0,quantity:0,remaining:0,late:0};v.rows++;v.quantity+=o.quantity;v.remaining+=Math.max(0,outstanding(o)??0);if(overdue(o))v.late++;map.set(name,v);}return [...map.values()].sort((a,b)=>b.remaining-a.remaining);};
 const filters={customer,owner,month,exception,stage};
 return <div className="space-y-5"><div className="dashboard-hero"><div><span className="section-kicker">WIP CONTROL / 实时汇总</span><h2>欠数在制管理</h2><p>从订单发现异常，直接进入明细跟进。</p></div><div className="hero-date"><span>{today()}</span><b>{source.length.toLocaleString()} 条在制明细</b></div></div>
 <div className="filterbar"><Choice label="看板客户" value={customer} onChange={v=>{setCustomer(v);setPage(0);}} options={[{value:'',label:'全部客户'},...[...new Set(source.map(o=>o.customer).filter(Boolean))].sort().map(v=>({value:v,label:v}))]}/><Choice label="看板跟单员" value={owner} onChange={v=>{setOwner(v);setPage(0);}} options={[{value:'',label:'全部跟单员'},...[...new Set(source.map(ownerLabel))].map(v=>({value:v,label:v}))]}/><Input aria-label="交期月份" type="month" value={month} onInput={e=>{setMonth(e.currentTarget.value);setPage(0);}} onChange={e=>setMonth(e.target.value)}/><Button variant="ghost" onClick={()=>{setCustomer('');setOwner('');setMonth('');setPage(0);}}>重置</Button><Export mode="active" filters={{customer,owner,month}}/></div>
 <div className="metrics">{[['订单数量',quantity,'当前筛选的在制订单'],['待完成数量',remaining,'逐行欠数取正值，不抵消超量'],['逾期明细',late.length,'以 PMC 排期优先，缺失用客户交期'],['超量入仓',over,'单独核对，不冲抵其他欠单']].map(([l,n,t])=><div className="metric" key={l}><span>{l}</span><strong>{fmt(Number(n))}<small>{l==='逾期明细'?'行':'副'}</small></strong><p>{t}</p></div>)}</div>
 <div className="dashboard-grid"><section className="panel section-pad"><div className="panel-title"><h3>工序欠数与在制</h3><Field label="参考日产能（副 / 天）"><Input className="capacity-input" aria-label="参考日产能" type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></Field></div><p className="muted">点击工序查看正在加工的订单。周转天数 = 有效 WIP ÷ 参考日产能。</p><Grid headers={['工序','欠数','WIP','周转天数','超周期 / 待核对']} rows={summary.map(d=>[<button className={'text-link '+(stage===d.id?'font-bold':'')} onClick={()=>{setStage(d.id);setException('');setPage(0);}}>{d.name} <ArrowUpRight size={13} className="inline"/></button>,fmt(d.debt),<div className="wip-bar"><b>{fmt(d.wip)}</b><Progress value={Math.min(100,d.wip/Math.max(1,...summary.map(s=>s.wip))*100)}/></div>,Number(capacity)>0?(d.wip/Number(capacity)).toFixed(1):'—',<span><span className={d.late?'text-orange-700':''}>{d.late} 行</span> / {d.invalid} 行</span>])}/></section>
 <section className="panel section-pad"><h3 className="section-title">客户欠数排行</h3><p className="subtitle">点击客户，定位交付风险。</p>{grouped(o=>o.customer).slice(0,8).map(c=><button className="rank-row" key={c.name} onClick={()=>{setCustomer(c.name);setPage(0);}}><div><b>{c.name}</b><span>{c.rows} 条明细 · {c.late} 条逾期</span></div><strong>{fmt(c.remaining)}<small> 副</small></strong><Progress value={remaining?c.remaining/remaining*100:0}/></button>)}<h3 className="section-title mt-6">按客户等级汇总</h3><Grid headers={['等级','订单数','欠数']} rows={grouped(o=>o.ledger?.columns.D||'未填写').map(g=>[g.name,fmt(g.quantity),fmt(g.remaining)])}/><h3 className="section-title mt-6">按跟单员汇总</h3><Grid headers={['跟单员','待完成','逾期']} rows={grouped(ownerLabel).map(g=>[<button className="text-link" onClick={()=>{setOwner(g.name);setPage(0);}}>{g.name}</button>,fmt(g.remaining),g.late])}/></section></div>
 <section className="panel section-pad"><div className="panel-title"><div><h3>异常跟进清单 <span className="muted">{bad.length} 行</span></h3><p className="muted">点击订单进入工序录入、责任跟进与历史记录。</p></div><Export mode="active" filters={filters}/></div><div className="exception-tabs">{['交期逾期','未排交期','原表欠数不一致','原表计算错误','工序数量待核对','同键多行','缺款号','跟单账号未绑定',''].map(e=><button key={e} className={exception===e&&!stage?'selected':''} onClick={()=>{setException(e);setStage('');setPage(0);}}>{e||'全部'} <span>{rows.filter(o=>!e||issues(o).includes(e)).length}</span></button>)}</div>{selected&&<p className="note">当前查看：{selected.name} WIP 大于零的明细 <button className="text-link" onClick={()=>setStage('')}>清除工序筛选</button></p>}
 <Grid headers={['订单 / 款号','跟单员','交期','欠数','异常与跟进','操作']} rows={bad.slice(page*15,page*15+15).map(o=>[<div><b>{o.orderNo}</b><span className="subline">{o.drawing||'缺款号'} · {o.color} · {o.customer}</span></div>,ownerLabel(o),promisedDue(o)||'未排期',fmt(outstanding(o)),<div className="issue-wrap">{issues(o).filter(i=>i!=='跟单账号未绑定').slice(0,3).map(i=><span className="pill red" key={i}>{i}</span>)}<span className="subline wrap">{o.notes||'暂无跟进备注'}</span></div>,<Button size="sm" variant="outline" onClick={()=>openOrder(o)}>跟进</Button>])}/><Pager count={bad.length} page={page} setPage={setPage} size={15}/></section>
 <details className="panel section-pad"><summary>查看计算口径与原表差异</summary><p className="note mt-3">只汇总在制订单，已归档明细不进入本页。出货欠数沿用原表含义：订单数 M − 包装入仓 BF；尚无入仓记录按 0 计算，不等同于实际发货。原表 P 的缓存值保留供核对。未排期、非法数字和公式错误独立标记。</p><p className="note mt-3">工序欠数 = 订单数量减该工序完成量，最低为 0；WIP = 可确认的上道完成量减本工序完成量。空白上道数视为未知，“-”表示不适用，负 WIP 和非法数字不加入有效 WIP。钛架和胶架为并行路径，工序 WIP 不跨路径相加作为工厂总库存。周转天数为参考负荷，不能直接作为客户交期。</p></details></div>;
}
export function Pager({count,page,setPage,size=20}:{count:number;page:number;setPage:(v:number)=>void;size?:number}){return <div className="table-footer"><span>{count} 条 · 第 {page+1} / {Math.max(1,Math.ceil(count/size))} 页</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>上一页</Button><Button size="sm" variant="outline" disabled={(page+1)*size>=count} onClick={()=>setPage(page+1)}>下一页</Button></div></div>;}
export function ArchivePanel({data,openOrder}:Props){
 const [q,setQ]=useState(''),[customer,setCustomer]=useState(''),[month,setMonth]=useState(''),[page,setPage]=useState(0),[onlyIssue,setOnlyIssue]=useState(false);const source=data.orders.filter(o=>o.lifecycle==='archived'),rows=source.filter(o=>(!q||[o.orderNo,o.drawing,o.customer,o.color,ownerLabel(o)].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!customer||o.customer===customer)&&(!month||o.closedDate?.startsWith(month))&&(!onlyIssue||(outstanding(o)??0)>0||!o.closedDate));
 return <div className="space-y-5"><div className="archive-hero"><Archive size={34}/><div><h2>已完成订单放置页</h2><p>从动态表移出的历史订单，集中保存，随时查验。</p></div><Export mode="archived" filters={{q,customer,month,review:onlyIssue?'1':''}}/></div><div className="metrics">{[['归档明细',source.length],['归档订单',new Set(source.map(o=>o.orderNo)).size],['归档订单数量',source.reduce((n,o)=>n+o.quantity,0)],['归档仍有余欠',source.filter(o=>(outstanding(o)??0)>0).length]].map(([l,n])=><div className="metric" key={l}><span>{l}</span><strong>{fmt(Number(n))}</strong></div>)}</div><div className="filterbar"><Input aria-label="查询完成订单" placeholder="订单、客户、款号、色号或跟单员" value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/><Choice label="档案客户" value={customer} onChange={v=>{setCustomer(v);setPage(0);}} options={[{value:'',label:'全部客户'},...[...new Set(source.map(o=>o.customer).filter(Boolean))].sort().map(v=>({value:v,label:v}))]}/><Input type="month" aria-label="结单月份" value={month} onInput={e=>{setMonth(e.currentTarget.value);setPage(0);}} onChange={e=>setMonth(e.target.value)}/><Button variant={onlyIssue?'default':'outline'} onClick={()=>{setOnlyIssue(!onlyIssue);setPage(0);}}>只看归档待核对</Button></div><section className="panel"><Grid headers={['订单号 / 客户','款号 · 色号','跟单员','订单 / 入仓','结单日期','归档核对','操作']} rows={rows.slice(page*20,page*20+20).map(o=>[<div><b>{o.orderNo}</b><span className="subline">{o.customer}</span></div>,`${o.drawing} · ${o.color}`,ownerLabel(o),`${fmt(o.quantity)} / ${fmt(warehouse(o))}`,o.closedDate||'未填写',<span className={'pill '+((outstanding(o)??0)>0?'red':'green')}>{(outstanding(o)??0)>0?'余欠 '+fmt(outstanding(o)):'已归档'}</span>,<Button variant="outline" size="sm" onClick={()=>openOrder(o)}>查验</Button>])}/><Pager count={rows.length} page={page} setPage={setPage}/></section><p className="note">按 PMC 历史文件归档范围完整保留。归档有余欠、缺结单日和超量记录不自动修正；需要继续生产时，由 PMC 填写原因后恢复到动态总表。原始文件可在“上传与更新”下载。</p></div>;
}
export function DepartmentPanel({data,openOrder}:Props){const [dept,setDept]=useState(broad(data.me)?'pmc':data.me.departments?.[0]||''),[q,setQ]=useState(''),[page,setPage]=useState(0);const allowed=departments.filter(d=>broad(data.me)||data.me.departments?.includes(d.id)),def=departments.find(d=>d.id===dept),rows=data.orders.filter(o=>active(o)&&o.ledger&&(!q||[o.orderNo,o.drawing,o.color,o.customer,ownerLabel(o)].join(' ').toLowerCase().includes(q.toLowerCase())));
 return <div className="space-y-5"><section className="panel section-pad"><span className="section-kicker">我的部门工作台</span><h2 className="section-title">总表统一供数，各部门维护自己的工序</h2><p className="subtitle">更新立即归集到同一条订单，所有岗位共用明细编号与修改历史。</p><div className="department-tabs">{allowed.map(d=><Button key={d.id} variant={dept===d.id?'default':'outline'} onClick={()=>{setDept(d.id);setPage(0);}}>{d.name}</Button>)}</div>{def&&<p className="note">{def.name}可填写：{def.cols.map(c=>colLabels[c]).join('、')}。齐套日 AP / BB 自动计算。</p>}{!allowed.length&&<p className="note">账号尚未分配部门，请管理员在“成员与权限”中选择岗位。</p>}</section>{def&&allowed.length>0&&<><div className="filterbar"><Input aria-label="部门订单搜索" placeholder="输入订单号、款号或客户，找到今天要处理的明细" value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/></div><section className="panel"><Grid headers={['订单 / 客户','款号 · 色号','跟单员','当前工序信息','操作']} rows={rows.slice(page*20,page*20+20).map(o=>[<div><b>{o.orderNo}</b><span className="subline">{o.customer} · 订单 {o.quantity} 副</span></div>,`${o.drawing||'缺款号'} · ${o.color}`,ownerLabel(o),<div className="wrap muted">{def.cols.slice(0,4).map(c=>`${colLabels[c]}：${dateCols.includes(c)?dateValue(o.ledger!.columns[c])||o.ledger!.columns[c]||'未录':o.ledger!.columns[c]||'未录'}`).join('；')}</div>,<Button size="sm" onClick={()=>openOrder(o)}>录入本部门</Button>])}/><Pager count={rows.length} page={page} setPage={setPage}/></section></>}</div>;
}
export function LedgerEditor({order:o,data,act,busy,onClose}:{order:Order;data:Data;act:Act;busy:boolean;onClose:()=>void}){
 const allowed=departmentColumns(data.me,o),[values,setValues]=useState({...o.ledger?.columns}),[reason,setReason]=useState(''),[error,setError]=useState(''),[closeDate,setCloseDate]=useState(today());
 async function save(){try{await act('ledger-edit',{id:o.id,version:o.version,patch:Object.fromEntries(allowed.filter(c=>(values[c]||'')!==(o.ledger?.columns[c]||'')).map(c=>[c,values[c]||''])),reason});onClose();}catch(e){setError((e as Error).message);}}
 async function move(){try{await act('ledger-lifecycle',{id:o.id,version:o.version,mode:o.lifecycle==='archived'?'active':'archived',reason,closedDate:closeDate});onClose();}catch(e){setError((e as Error).message);}}
 if(!o.ledger)return <p className="note">此明细为标准格式订单，使用订单跟进与 MES 报工维护。</p>;
 return <div className="space-y-5 mt-4"><div className="note">来源：{o.source} / {o.ledger.sheet} / 第 {o.ledger.sourceRow} 行。<br/>原表欠数 {o.ledger.originalOutstanding||'未填写'}，当前重算欠数 {fmt(outstanding(o))}。包装入仓与 MES 包装报工分别保留。</div>{error&&<p className="error" role="alert">{error}</p>}{departments.filter(d=>d.cols.some(c=>allowed.includes(c))).map(d=><section className="department-form" key={d.id}><h3>{d.name}录入</h3><div className="form-grid">{d.cols.filter(c=>departments.filter(x=>x.cols.some(k=>allowed.includes(k))).find(x=>(x.cols as readonly string[]).includes(c))?.id===d.id).map(c=><Field key={c} label={`${c} · ${colLabels[c]}`}><Input aria-label={`${c} ${colLabels[c]}`} value={dateCols.includes(c)&&values[c]&&values[c]!=='-'?dateValue(values[c])||values[c]:values[c]||''} placeholder={dateCols.includes(c)?'YYYY-MM-DD / -':'未录入；不适用填 -'} onChange={e=>setValues({...values,[c]:e.target.value})}/></Field>)}</div></section>)}
 <div className="stat-strip"><span>钛齐套日（自动）<b>{automaticDates(o.ledger.columns).AP||'条件未齐'}</b></span><span>胶齐套日（自动）<b>{automaticDates(o.ledger.columns).BB||'条件未齐'}</b></span><span>当前阶段<b>{currentStage(o)}</b></span></div>
 {(allowed.length>0||broad(data.me))&&<><Field label="本次修改 / 归档依据"><Textarea aria-label="工序修改依据" value={reason} onChange={e=>setReason(e.target.value)} placeholder="填写送货单号、核对来源或结单依据"/></Field><div className="toolbar">{allowed.length>0&&<Button disabled={busy||reason.trim().length<2} onClick={save}><Save size={16}/>保存本部门字段</Button>}{broad(data.me)&&<><Input type="date" aria-label="实际结单日期" value={closeDate} onInput={e=>setCloseDate(e.currentTarget.value)} onChange={e=>setCloseDate(e.target.value)}/><Button variant="outline" disabled={busy||reason.trim().length<3} onClick={move}><Archive size={16}/>{o.lifecycle==='archived'?'恢复到动态表':'确认结单并归档'}</Button></>}</div>{o.lifecycle!=='archived'&&(outstanding(o)??0)>0&&<p className="note">此单尚有余欠；只有 PMC / 管理员核对后填写结单依据，才可将其归档。归档不会删除历史记录。</p>}</>}
 <details><summary>查看全部原始工序与备注</summary><Grid headers={['字段','内容']} rows={Object.entries(o.ledger.columns).filter(([c])=>colLabels[c]).map(([c,v])=>[`${c} · ${colLabels[c]}`,<span className="wrap">{dateCols.includes(c)?dateValue(v)||v:v}</span>])}/></details></div>;
}
