'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Camera,Plus,Truck,CheckCircle2,FileImage,ArrowRight} from 'lucide-react';
import {Choice,Field,Grid,Input,request,type Act,dateTime} from './ui';
import {mayReceive} from '@/lib/departments';
import {stageDefs,today,active} from '@/lib/ledger';
import {type Order} from '@/lib/domain';
import type {Data} from './workspace';
import {Pager} from './ledger-panels';
type Props={data:Data;act:Act;busy:boolean;openOrder:(o:Order)=>void};
export function ReceivingPanel({data,act,busy,openOrder}:Props){
 const [mode,setMode]=useState('pending'),[modal,setModal]=useState(false),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[error,setError]=useState(''),[photo,setPhoto]=useState<any>(null),[supplier,setSupplier]=useState(''),[deliveryNo,setDeliveryNo]=useState(''),[receivedDate,setReceivedDate]=useState(today()),[note,setNote]=useState(''),[token,setToken]=useState(()=>crypto.randomUUID()),[lines,setLines]=useState([{outsourceId:'',accepted:'',rejected:'0'}]);
 const [draft,setDraft]=useState({lineId:'',supplier:'',process:'plating',quantity:'',sentDate:today(),dueDate:today(),reference:'',token:crypto.randomUUID()});
 const sources=data.outsource||[],receipts=data.receipts||[],pending=sources.filter(x=>x.received<x.quantity),orders=data.orders.filter(active),jobs=pending.filter(x=>{const o=orders.find(o=>o.id===x.lineId);return !!o&&mayReceive(data.me,o,x.process);}),editable=['admin','pmc','clerk'].includes(data.me.role),filter=sources.filter(x=>((mode!=='pending')||x.received<x.quantity)&&(!query||[x.supplier,x.reference,orders.find(o=>o.id===x.lineId)?.orderNo].join(' ').toLowerCase().includes(query.toLowerCase())));
 async function create(){try{await act('outsource-create',{...draft,quantity:Number(draft.quantity)});setModal(false);setDraft({...draft,lineId:'',quantity:'',reference:'',token:crypto.randomUUID()});setError('');}catch(e){setError((e as Error).message);}}
 async function upload(file:File){try{const form=new FormData();form.set('file',file);setPhoto(await act('receipt-photo',form));setMode('receipt');setError('');}catch(e){setError((e as Error).message);}}
 async function confirm(){try{await act('receipt-confirm',{photoId:photo.id,supplier,deliveryNo,receivedDate,note,token,lines:lines.map(l=>({...l,accepted:Number(l.accepted),rejected:Number(l.rejected)}))});setPhoto(null);setDeliveryNo('');setLines([{outsourceId:'',accepted:'',rejected:'0'}]);setToken(crypto.randomUUID());setMode('history');setError('');}catch(e){setError((e as Error).message);}}
 return <div className="space-y-5"><section className="receiving-hero"><div><span className="section-kicker">供应商收货工作台</span><h2>拍照留单，按订单消数</h2><p>外发登记 → 上传送货单 → 核对合格数量 → 更新工序与外发欠数</p></div><div className="flex gap-3"><Button variant="outline" disabled={!editable} onClick={()=>{setModal(true);setError('');}}><Plus size={17}/>登记外发</Button><Button disabled={!editable} onClick={()=>{setMode('receipt');setError('');}}><Camera size={17}/>拍照 / 登记收货</Button></div></section>
 <div className="metrics">{[['待回货外发明细',pending.length,'按外发单 / 订单 / 工序'],['外发未回数量',pending.reduce((n,x)=>n+x.quantity-x.received,0),'只用合格收货消数'],['逾期未回',pending.filter(x=>x.dueDate<today()).length,'按约定回货日期'],['已入账送货单',receipts.filter(r=>r.status==='已入账').length,'照片、明细、经办人可查']].map(([l,n,t])=><div className="metric" key={l}><span>{l}</span><strong>{Number(n).toLocaleString()}</strong><p>{t}</p></div>)}</div>
 <div className="department-tabs">{[['pending','待回货'],['all','全部外发'],['receipt','拍照收货'],['history','送货单档案']].map(([v,l])=><Button key={v} variant={mode===v?'default':'outline'} onClick={()=>{setMode(v);setPage(0);}}>{l}</Button>)}</div>{error&&<p role="alert" className="error">{error}</p>}
 {['pending','all'].includes(mode)&&<><div className="filterbar"><Input aria-label="搜索供应商外发单" placeholder="搜索供应商、外发单号或订单号" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div><section className="panel"><Grid headers={['供应商 / 外发单','订单 / 工序','外发数量','合格回货','剩余欠数','约定回货','操作']} rows={filter.slice(page*20,page*20+20).map(x=>{const o=data.orders.find(o=>o.id===x.lineId);return [<div><b>{x.supplier}</b><span className="subline">{x.reference}</span></div>,<div><button className="text-link" onClick={()=>o&&openOrder(o)}>{o?.orderNo}</button><span className="subline">{o?.drawing} · {o?.color} · {stageDefs.find(d=>d.id===x.process)?.name}</span></div>,x.quantity,x.received,<b className="text-orange-700">{x.quantity-x.received}</b>,x.dueDate,<Button size="sm" variant="outline" disabled={!o||!mayReceive(data.me,o,x.process)||x.received>=x.quantity} onClick={()=>{setSupplier(x.supplier);setLines([{outsourceId:x.id,accepted:'',rejected:'0'}]);setMode('receipt');}}>登记回货</Button>];})}/><Pager count={filter.length} page={page} setPage={setPage}/></section></>}
 {mode==='receipt'&&<div className="receipt-grid"><section className="panel section-pad"><h3 className="section-title">1. 上传送货单照片</h3><p className="subtitle">手机可直接拍照，也可上传已有图片或 PDF。</p><label className="photo-drop"><Camera size={35}/><b>{photo?'重新选择送货单':'拍摄 / 选择送货单'}</b><span>JPG、PNG、WebP、PDF · 最多 10 MB</span><Input type="file" aria-label="上传送货单照片" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" disabled={busy||!editable} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);}}/></label>{photo&&<><p className="subline">{photo.filename} · 已保存原件</p>{photo.contentType.startsWith('image/')?<img className="receipt-photo" alt="待核对的供应商送货单" src={'/api/workspace/ledger-file?id='+photo.id}/>:<a className="text-link" href={'/api/workspace/ledger-file?id='+photo.id} target="_blank" rel="noreferrer">打开 PDF 送货单</a>}</>}<p className="note mt-4">照片用于查验。请对照照片填写单号、订单、工序和实收数量，系统在确认入账后自动消数。</p></section>
 <section className="panel section-pad"><h3 className="section-title">2. 核对订单与本次收货</h3><p className="subtitle">一张送货单可对应多条外发明细；只可选择你负责工序的订单。</p><div className="form-grid mt-5"><Field label="供应商"><Choice label="收货供应商" value={supplier} onChange={v=>{setSupplier(v);setLines([{outsourceId:'',accepted:'',rejected:'0'}]);}} options={[{value:'',label:'选择供应商'},...[...new Set(jobs.map(x=>String(x.supplier)))].map(v=>({value:v,label:v}))]}/></Field><Field label="供应商送货单号"><Input aria-label="供应商送货单号" value={deliveryNo} onChange={e=>setDeliveryNo(e.target.value)}/></Field><Field label="实际收货日期"><Input aria-label="实际收货日期" type="date" value={receivedDate} onInput={e=>setReceivedDate(e.currentTarget.value)} onChange={e=>setReceivedDate(e.target.value)}/></Field></div>
 {lines.map((l,i)=><div className="receipt-line" key={i}><Field label={`第 ${i+1} 条 · 外发明细`}><Choice label={`收货明细 ${i+1}`} value={l.outsourceId} onChange={v=>setLines(lines.map((x,j)=>j===i?{...x,outsourceId:v}:x))} options={[{value:'',label:'选择订单与工序'},...jobs.filter(x=>x.supplier===supplier).map(x=>{const o=orders.find(o=>o.id===x.lineId);return {value:x.id,label:`${x.reference} / ${o?.orderNo} / ${o?.drawing} / ${o?.color} / ${stageDefs.find(d=>d.id===x.process)?.name} / 欠 ${x.quantity-x.received}`};})]}/></Field><div className="form-grid mt-3"><Field label="合格实收数量（消数）"><Input aria-label={`合格收货数量 ${i+1}`} type="number" min="0" value={l.accepted} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,accepted:e.target.value}:x))}/></Field><Field label="不良待处理数量（不消数）"><Input aria-label={`不良数量 ${i+1}`} type="number" min="0" value={l.rejected} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,rejected:e.target.value}:x))}/></Field></div>{l.outsourceId&&<p className="note mt-3">确认后此笔外发余欠：{(jobs.find(x=>x.id===l.outsourceId)?.quantity||0)-(jobs.find(x=>x.id===l.outsourceId)?.received||0)-Number(l.accepted||0)}。合格数同时计入该订单对应工序。</p>}{lines.length>1&&<Button variant="ghost" size="sm" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>移除此行</Button>}</div>)}<Button className="mt-3" variant="outline" disabled={lines.length>=20} onClick={()=>setLines([...lines,{outsourceId:'',accepted:'',rejected:'0'}])}><Plus size={16}/>添加另一条明细</Button><Field label="收货备注"><Input aria-label="收货备注" value={note} onChange={e=>setNote(e.target.value)} placeholder="记录不良、短装或验收说明"/></Field><Button className="mt-5 w-full" disabled={busy||!photo||!supplier||!deliveryNo.trim()||lines.some(l=>!l.outsourceId||l.accepted==='')} onClick={confirm}><CheckCircle2 size={17}/>确认入账并消数</Button><p className="note mt-4">外发余欠与工序数量在同一次提交中更新。重复照片、重复供应商单号和超量收货会被拦截。不会回写 MES。</p></section></div>}
 {mode==='history'&&<section className="panel"><Grid headers={['送货单 / 供应商','收货日期','订单归集','合格 / 不良','经办人','凭证']} rows={[...receipts].reverse().slice(page*20,page*20+20).map(r=>[<div><b>{r.deliveryNo}</b><span className="subline">{r.supplier} · {r.status}</span></div>,r.receivedDate,<div>{r.lines.map((l:any)=><button className="text-link block" key={l.outsourceId} onClick={()=>{const o=data.orders.find(o=>o.id===l.lineId);if(o)openOrder(o);}}>{l.orderNo} / {l.drawing} / {l.color} · {stageDefs.find(d=>d.id===l.process)?.name}</button>)}</div>,`${r.lines.reduce((n:number,l:any)=>n+l.accepted,0)} / ${r.lines.reduce((n:number,l:any)=>n+l.rejected,0)}`,<div>{r.actor}<span className="subline">{dateTime(r.createdAt)}</span></div>,<a className="text-link" href={'/api/workspace/ledger-file?id='+r.photoId} target="_blank" rel="noreferrer">查看送货单</a>])}/><Pager count={receipts.length} page={page} setPage={setPage}/></section>}
 <Dialog open={modal} onOpenChange={setModal}><DialogContent className="dialog-scroll sm:max-w-[750px]"><DialogHeader><DialogTitle>登记供应商外发</DialogTitle><DialogDescription>选择总表明细和具体工序，建立本次外发的应回数量。</DialogDescription></DialogHeader>{error&&<p className="error">{error}</p>}<Input aria-label="查找外发订单" placeholder="先搜索订单号 / 款号 / 客户" value={search} onChange={e=>setSearch(e.target.value)}/><div className="form-grid"><Field label="外发工序"><Choice label="外发工序" value={draft.process} onChange={v=>setDraft({...draft,process:v,lineId:''})} options={stageDefs.filter(d=>!['procurement','packing'].includes(d.id)).map(d=>({value:d.id,label:d.name}))}/></Field><Field label="总表订单明细"><Choice label="外发订单明细" value={draft.lineId} onChange={v=>setDraft({...draft,lineId:v})} options={[{value:'',label:'请选择订单明细'},...orders.filter(o=>mayReceive(data.me,o,draft.process)&&(!search||[o.orderNo,o.drawing,o.customer,o.color].join(' ').toLowerCase().includes(search.toLowerCase()))).slice(0,60).map(o=>({value:o.id,label:`${o.orderNo} / ${o.drawing} / ${o.color} / 源行 ${o.ledger?.sourceRow||'标准单'}`}))]}/></Field>{[['supplier','供应商'],['reference','外发单号'],['quantity','本次外发数量'],['sentDate','外发日期'],['dueDate','约定回货日期']].map(([k,l])=><Field key={k} label={l}><Input aria-label={l} type={k.endsWith('Date')?'date':k==='quantity'?'number':'text'} min={k==='quantity'?1:undefined} value={(draft as any)[k]} onInput={e=>{if(k.endsWith('Date'))setDraft({...draft,[k]:e.currentTarget.value});}} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></Field>)}</div><Button disabled={busy||!draft.lineId||!draft.supplier||!draft.reference||!draft.quantity} onClick={create}>保存外发登记</Button></DialogContent></Dialog>
 </div>;
}
