'use client';
import {useState} from 'react';
import {Plus,CalendarClock,ClipboardList,Truck,ArrowRight,Download,Building2,CheckCircle2,MessageSquare,BadgeDollarSign} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Input,Field,Choice,Grid,Empty,dateTime,type Act} from './ui';
import {AccessNotice} from './access-notice';
import {Pager} from './ledger-panels';
import {ReceivingPanel} from './receiving-panel';
import {active,currentStage,stageDefs,today} from '@/lib/ledger';
import {canCreateOutsource,managesSuppliers,supplierPending,supplierStatus,needsFollowup,arrivalDate,matchesSupplierStatus} from '@/lib/suppliers';
import {mayReceive} from '@/lib/departments';
import {clientId} from '@/lib/client-id';
import {productTypeOf,type Entity,type Order} from '@/lib/domain';
import type {Data} from './workspace';
import {PurchasePanel} from './purchase-panel';
import {SupplierQuotePanel} from './supplier-quote-panel';
type Props={data:Data;act:Act;busy:boolean;openOrder:(o:Order)=>void};
const number=(n:number)=>n.toLocaleString('zh-CN');
const processName=(id:string)=>stageDefs.find(d=>d.id===id)?.name||id;
const tone=(status:string)=>status==='已逾期'?'red':['待供应商复期','交期风险'].includes(status)?'amber':status==='已收齐'?'green':'blue';
const blankSupplier={name:'',contact:'',phone:'',notes:'',active:true};
export function SupplierPanel(props:Props&{onDirtyChange:(v:boolean)=>void}){
 const [view,setView]=useState('purchase'),[dirty,setDirty]=useState(false);
 function dirtyChanged(v:boolean){setDirty(v);props.onDirtyChange(v);}
 return <><div className="supplier-top-tabs"><button className={view==='purchase'?'selected':''} disabled={dirty} onClick={()=>setView('purchase')}>采购部跟单总表 / 已交货档案</button><button className={view==='outsource'?'selected':''} disabled={dirty} onClick={()=>setView('outsource')}>工序外发与送货单</button></div>{view==='purchase'?<PurchasePanel me={props.data.me} onDirtyChange={dirtyChanged}/>:<LegacySupplierPanel {...props}/>}</>;
}
function LegacySupplierPanel({data,act,busy,openOrder}:Props){
 const manage=managesSuppliers(data.me),createAllowed=canCreateOutsource(data.me),orders=data.orders.filter(active),sources=data.outsource||[],suppliers=data.suppliers||[],pending=sources.filter(supplierPending),buyers=data.members.filter(m=>m.active&&['pmc','admin'].includes(m.role));
 const [view,setView]=useState('tracking'),[query,setQuery]=useState(''),[status,setStatus]=useState('pending'),[supplier,setSupplier]=useState(''),[buyer,setBuyer]=useState(''),[page,setPage]=useState(0),[orderQuery,setOrderQuery]=useState(''),[orderPage,setOrderPage]=useState(0),[error,setError]=useState(''),[create,setCreate]=useState<any>(null),[edit,setEdit]=useState<any>(null),[master,setMaster]=useState<any>(null),[cancel,setCancel]=useState(false),[cancelReason,setCancelReason]=useState(''),[receiptId,setReceiptId]=useState('');
 const byId=new Map(data.orders.map(o=>[o.id,o]));
 const rows=sources.filter(x=>(!query||[x.supplier,x.reference,byId.get(x.lineId)?.orderNo,byId.get(x.lineId)?.drawing,byId.get(x.lineId)?productTypeOf(byId.get(x.lineId)!):''].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!supplier||x.supplier===supplier)&&(!buyer||x.buyerEmail===buyer)&&matchesSupplierStatus(x,status)).sort((a,b)=>arrivalDate(a).localeCompare(arrivalDate(b)));
 const candidates=orders.filter(o=>!orderQuery||[o.orderNo,o.drawing,o.customer,o.color,productTypeOf(o),o.ledger?.ownerName].join(' ').toLowerCase().includes(orderQuery.toLowerCase()));
 function tab(v:string){setView(v);setPage(0);setError('');}
 function register(o?:Order){setError('');setCreate({lineId:o?.id||'',supplier:'',process:'plating',quantity:'',sentDate:today(),dueDate:'',reference:'',buyerEmail:buyers.find(b=>b.email===data.me.email)?.email||buyers[0]?.email||'',note:'',token:clientId()});}
 function followup(x:Entity){setError('');setCancel(false);setCancelReason('');setEdit({...x,replyDate:x.replyDate||'',promisedDate:x.promisedDate||'',promisedQuantity:x.promisedQuantity??'',expectedDate:x.expectedDate||'',nextFollowupDate:x.nextFollowupDate||'',delayReason:x.delayReason||'',buyerEmail:x.buyerEmail||buyers.find(b=>b.email===data.me.email)?.email||buyers[0]?.email||'',note:''});}
 async function saveCreate(){try{const result=await act('outsource-create',{...create,quantity:Number(create.quantity)});setCreate(null);tab('tracking');setStatus('pending');setSupplier('');setBuyer('');setQuery('');if(result.item)followup(result.item);}catch(e){setError((e as Error).message);}}
 async function saveEdit(){try{await act('outsource-update',{...edit,quantity:Number(edit.quantity),promisedQuantity:edit.promisedQuantity===''?null:Number(edit.promisedQuantity)});setEdit(null);setError('');}catch(e){setError((e as Error).message);}}
 async function saveMaster(){try{await act('supplier-save',master);setMaster(null);setError('');}catch(e){setError((e as Error).message);}}
 async function cancelOrder(){try{await act('outsource-cancel',{id:edit.id,version:edit.version,reason:cancelReason});setEdit(null);setError('');}catch(e){setError((e as Error).message);}}
 const procurementNames=buyers.filter(b=>b.role==='pmc').map(b=>b.email.split('@')[0]).join(' · ')||'PMC / 采购';
 const candidateTable=(short=false)=><section className="panel"><div className="panel-tools"><b>{short?'从真实总表明细开始':'选择需要外发的订单明细'}</b><span className="muted ml-auto">{number(candidates.length)} 条可查订单 · 登记时填写实际外发数量</span></div><Grid headers={['订单 / 客户','产品类型','款号 / 色号','总表数量','当前工序','已登记外发','操作']} rows={candidates.slice(short?0:orderPage*20,short?5:orderPage*20+20).map(o=>[<button className="text-link" onClick={()=>openOrder(o)}><b>{o.orderNo}</b><span className="subline">{o.customer} · 源行 {o.ledger?.sourceRow||'标准单'}</span></button>,<b>{productTypeOf(o)||'未填写'}</b>,<div>{o.drawing}<span className="subline">{o.color} · {o.lens}</span></div>,number(o.quantity),currentStage(o),sources.filter(x=>x.lineId===o.id&&x.status!=='已取消').length+' 笔',<Button size="sm" variant="outline" disabled={!createAllowed} onClick={()=>register(o)}><Plus size={15}/>登记外发</Button>])}/>{!short&&<Pager count={candidates.length} page={orderPage} setPage={setOrderPage}/>}</section>;
 return <div className="supplier-workspace space-y-5">
  <section className="supplier-hero"><div><span className="section-kicker">采购 / PMC 协同工作台</span><h2>供应商交期与收货</h2><p>从总表关联外发，跟进供应商复期，收货后按订单消数。</p><div className="supplier-hero-meta"><span><CheckCircle2 size={15}/>总表已连接 · {number(orders.length)} 条在制明细</span><span><Building2 size={15}/>{procurementNames} 共同维护</span></div></div><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={()=>tab('orders')}><ClipboardList size={17}/>从总表选单</Button>{createAllowed&&<Button onClick={()=>register()}><Plus size={17}/>登记外发</Button>}</div></section>
  {!manage&&<AccessNotice me={data.me} compact title="交期维护权限 · 仅可查看" detail="供应商资料、外发单和回复交期由 PMC / 采购 Candy、Tina 维护；收货人员可在“送货单与收货”中办理已获授权工序的收货。"/>}
  <div className="supplier-metrics">{[
   ['pending','未收齐外发',pending.length,`未回数量 ${number(pending.reduce((n,x)=>n+x.quantity-x.received,0))}`,'green'],
   ['待供应商复期','待供应商复期',pending.filter(x=>!x.promisedDate).length,'尚未登记承诺交期','violet'],
   ['已逾期','已逾期',pending.filter(x=>supplierStatus(x)==='已逾期').length,'要求交期或预计到货已过','rose'],
   ['交期风险','交期风险',pending.filter(x=>supplierStatus(x)==='交期风险').length,'预计到货晚于要求交期','amber'],
   ['followup','今日待催交',pending.filter(x=>needsFollowup(x)).length,'下次催交日已到','blue']
  ].map(([filter,label,count,detail,color])=><button key={filter} className={'supplier-metric '+color} onClick={()=>{tab('tracking');setStatus(String(filter));setSupplier('');setBuyer('');setQuery('');}}><span>{label}</span><strong>{number(Number(count))}</strong><small>{detail}</small></button>)}</div>
  <div className="supplier-tabs" role="tablist" aria-label="供应商工作区域">{[['tracking','交期与催交',CalendarClock],['quotes','供应商报价库',BadgeDollarSign],['orders','从总表选单',ClipboardList],['directory','供应商资料',Building2],['receiving','送货单与收货',Truck]].map(([id,label,Icon]:any)=><button role="tab" aria-selected={view===id} key={id} className={view===id?'selected':''} onClick={()=>tab(id)}><Icon size={18}/>{label}</button>)}</div>
  {error&&!create&&!edit&&!master&&<p className="error" role="alert">{error}</p>}
  {view==='tracking'&&<>
   {!sources.length?<><section className="supplier-start"><span className="supplier-start-icon"><Truck size={29}/></span><div><h3>总表已就绪，下一步登记实际外发</h3><p>当前还没有供应商外发单和送货单记录。请选择下面的真实订单，填写供应商、工序、外发数量和要求交期，再登记供应商回复的日期。</p><div className="supplier-steps"><span>1 关联总表订单</span><ArrowRight size={16}/><span>2 采购登记与复期</span><ArrowRight size={16}/><span>3 拍单收货消数</span></div><Button variant="outline" onClick={()=>tab('orders')}>查看全部 {number(orders.length)} 条明细 <ArrowRight size={16}/></Button></div></section>{candidateTable(true)}</>:<>
   <div className="filterbar"><Input aria-label="搜索供应商交期" placeholder="供应商 / 外发单号 / 订单号 / 款号" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><Choice label="供应商交期状态" value={status} onChange={v=>{setStatus(v);setPage(0);}} options={[{value:'pending',label:'未收齐外发'},{value:'',label:'全部状态'},...['待供应商复期','交期风险','已逾期','3天内到货','待回货','已收齐','已取消'].map(v=>({value:v,label:v})),{value:'followup',label:'今日待催交'}]}/><Choice label="采购跟进人筛选" value={buyer} onChange={v=>{setBuyer(v);setPage(0);}} options={[{value:'',label:'全部采购跟进人'},...buyers.map(b=>({value:b.email,label:b.email.split('@')[0]+' · '+b.name}))]}/><Choice label="供应商筛选" value={supplier} onChange={v=>{setSupplier(v);setPage(0);}} options={[{value:'',label:'全部供应商'},...[...new Set(sources.map(x=>x.supplier))].map(v=>({value:v,label:v}))]}/><Button variant="outline" asChild><a href={'/api/workspace/supplier-export?'+new URLSearchParams({q:query,status,supplier,buyer})}><Download size={16}/>导出交期表</a></Button></div>
   <section className="panel"><div className="panel-tools"><b>外发与交期跟进 · {rows.length} 笔</b><span className="muted ml-auto">采购复期与仓库收货共享同一条外发记录</span></div>{rows.length?<Grid headers={['供应商 / 外发单','对应订单 / 工序','产品类型','数量 / 未回','要求交期','供应商复期 / 预计到货','采购跟进','状态 / 操作']} rows={rows.slice(page*15,page*15+15).map(x=>{const o=byId.get(x.lineId),state=supplierStatus(x),canApprove=x.approvalStatus==='待主管审批'&&(data.me.role==='admin'||data.me.name===x.approverName);return [<div><b>{x.supplier}</b><span className="subline">{x.reference}</span>{x.approverName&&<span className="subline">审批：{x.approverName}</span>}</div>,<button className="text-link" onClick={()=>o&&openOrder(o)}>{o?.orderNo}<span className="subline">{o?.drawing} · {o?.color}</span><span className="subline">{processName(x.process)} · 源行 {o?.ledger?.sourceRow||'—'}</span></button>,<b>{o?productTypeOf(o):'未填写'}</b>,<div><b>{number(x.quantity)}</b><span className="subline">合格 {number(x.received)} · 未回 {number(x.status==='已取消'?0:Math.max(0,x.quantity-x.received))}</span></div>,<div>{x.dueDate}<span className="subline">原始 {x.originalDueDate||x.dueDate}</span></div>,<div><b>{x.promisedDate||'待供应商复期'}</b><span className="subline">预计 {x.expectedDate||'待确认'}</span>{x.delayReason&&<span className="supplier-delay">{x.delayReason}</span>}</div>,<div>{x.buyerEmail?.split('@')[0]||x.actor}<span className="subline">催交 {x.nextFollowupDate||'未安排'}</span>{needsFollowup(x)&&<span className="pill amber">今日待跟进</span>}</div>,<div className="supplier-row-actions"><span className={'pill '+tone(state)}>{state}</span>{canApprove?<><Button size="sm" onClick={()=>act('outsource-approve',{id:x.id,version:x.version,decision:'approve',note:'手机/中台审批同意'})}>同意</Button><Button size="sm" variant="outline" onClick={()=>act('outsource-approve',{id:x.id,version:x.version,decision:'reject',note:'审批退回修改'})}>退回</Button></>:<Button size="sm" variant="outline" onClick={()=>followup(x)}>{manage&&x.status!=='已取消'?'复期 / 催交':'查看跟进'}</Button>}{o&&x.approvalStatus==='已审批'&&supplierPending(x)&&mayReceive(data.me,o,x.process)&&<button className="text-link" onClick={()=>{setReceiptId(x.id);tab('receiving');}}>登记收货</button>}</div>];})}/>:<Empty title="没有符合筛选的外发单" detail="可以调整状态、采购跟进人或搜索词查看其他记录。"/>}<Pager count={rows.length} page={page} setPage={setPage} size={15}/></section>
   </>}
  </>}
  {view==='orders'&&<><div className="filterbar"><Input aria-label="筛选可外发总表订单" placeholder="搜索订单号、客户、款号、跟单员" value={orderQuery} onChange={e=>{setOrderQuery(e.target.value);setOrderPage(0);}}/><span className="note">以总表明细编号关联，同单多色、同键多行分别登记。</span></div>{candidateTable()}</>}
  {view==='quotes'&&<SupplierQuotePanel data={data} act={act} busy={busy}/>} 
  {view==='directory'&&<section className="panel"><div className="panel-tools"><b>供应商资料 · {suppliers.length} 家</b><span className="muted ml-auto">外发登记也可自动建立供应商名称，联系方式由采购补充。</span>{manage&&<Button onClick={()=>{setError('');setMaster({...blankSupplier});}}><Plus size={16}/>新增供应商</Button>}</div>{suppliers.length?<Grid headers={['供应商','联系人 / 电话','待回货','备注','状态','操作']} rows={suppliers.map(s=>[<b>{s.name}</b>,<div>{s.contact||'待补充'}<span className="subline">{s.phone||'待补充电话'}</span></div>,pending.filter(x=>x.supplier===s.name).length+' 笔',<span className="wrap">{s.notes||'—'}</span>,<span className={'pill '+(s.active?'green':'')}>{s.active?'合作中':'已停用'}</span>,<Button variant="outline" size="sm" onClick={()=>{setError('');setMaster({...blankSupplier,...s});}}>{manage?'编辑资料':'查看资料'}</Button>])}/>:<Empty title="尚未建立供应商资料" detail="Candy、Tina 可新增供应商，或在登记第一笔外发时填写实际供应商名称。"/>}</section>}
  {view==='receiving'&&<ReceivingPanel key={receiptId} data={data} act={act} busy={busy} openOrder={openOrder} embedded initialOutsourceId={receiptId} onRegister={()=>tab('orders')}/>}
  <datalist id="supplier-names">{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.name}/>)}</datalist>
  <Dialog open={!!create} onOpenChange={v=>{if(!v)setCreate(null);}}><DialogContent className="dialog-scroll sm:max-w-[850px]"><DialogHeader><DialogTitle>登记外发与要求交期</DialogTitle><DialogDescription>部门文员创建后进入主管审批；PMC或管理员创建时按成品外发权限直接审批。</DialogDescription></DialogHeader>{create&&<><div className="form-grid"><Field label="查找总表订单"><Input aria-label="查找登记外发订单" value={orderQuery} onChange={e=>setOrderQuery(e.target.value)} placeholder="订单号 / 款号 / 客户"/></Field><Field label="总表订单明细"><Choice label="采购外发订单明细" value={create.lineId} onChange={v=>setCreate({...create,lineId:v})} options={[{value:'',label:'选择具体订单行'},...[...new Map([...candidates.slice(0,80),...(byId.has(create.lineId)?[byId.get(create.lineId)!]:[])].map(o=>[o.id,o])).values()].map(o=>({value:o.id,label:`${o.orderNo} / ${o.drawing} / ${o.color} / 源行 ${o.ledger?.sourceRow||'标准单'}`}))]}/></Field><Field label="供应商"><Input aria-label="外发供应商名称" list="supplier-names" value={create.supplier} onChange={e=>setCreate({...create,supplier:e.target.value})}/></Field><Field label="外发单号"><Input aria-label="采购外发单号" value={create.reference} onChange={e=>setCreate({...create,reference:e.target.value})}/></Field><Field label="外发工序"><Choice label="采购外发工序" value={create.process} onChange={v=>setCreate({...create,process:v})} options={stageDefs.filter(d=>!['procurement','packing'].includes(d.id)).map(d=>({value:d.id,label:d.name}))}/></Field><Field label="实际外发数量"><Input aria-label="采购外发数量" type="number" min="1" value={create.quantity} onChange={e=>setCreate({...create,quantity:e.target.value})}/></Field>{[['sentDate','外发日期'],['dueDate','要求到货日期']].map(([key,label])=><Field label={label} key={key}><Input aria-label={label} type="date" value={create[key]} onChange={e=>setCreate({...create,[key]:e.target.value})}/></Field>)}<Field label="采购跟进人"><Choice label="新外发采购跟进人" value={create.buyerEmail} onChange={v=>setCreate({...create,buyerEmail:v})} options={buyers.map(b=>({value:b.email,label:b.email.split('@')[0]+' · '+b.name}))}/></Field><Field label="登记备注"><Input aria-label="外发登记备注" value={create.note} onChange={e=>setCreate({...create,note:e.target.value})}/></Field></div>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy||!createAllowed||!create.lineId||!create.supplier.trim()||!create.reference.trim()||!create.quantity||!create.dueDate||!create.buyerEmail} onClick={saveCreate}>保存并进入审批</Button></>}</DialogContent></Dialog>
  <Dialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null);}}><DialogContent className="dialog-scroll sm:max-w-[950px]"><DialogHeader><DialogTitle>供应商复期与催交记录</DialogTitle><DialogDescription>{edit?.supplier} · {edit?.reference} · {byId.get(edit?.lineId)?.orderNo} · {processName(edit?.process||'')}</DialogDescription></DialogHeader>{edit&&<>
   <div className="supplier-detail-strip"><span>原始要求交期 <b>{edit.originalDueDate||edit.dueDate}</b></span><span>合格已回 <b>{number(edit.received)}</b></span><span>当前状态 <b>{supplierStatus(edit)}</b></span></div>
   <fieldset disabled={!manage||edit.status==='已取消'||busy} className="space-y-4"><div className="form-grid">{[['supplier','供应商'],['reference','外发单号'],['quantity','外发数量']].map(([key,label])=><Field key={key} label={label}><Input aria-label={'维护'+label} type={key==='quantity'?'number':'text'} list={key==='supplier'?'supplier-names':undefined} min={key==='quantity'?Math.max(1,edit.received):undefined} value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></Field>)}<Field label="采购跟进人"><Choice label="外发采购跟进人" value={edit.buyerEmail} onChange={v=>setEdit({...edit,buyerEmail:v})} options={buyers.map(b=>({value:b.email,label:b.email.split('@')[0]+' · '+b.name}))}/></Field>{[['sentDate','外发日期'],['dueDate','当前要求交期'],['replyDate','供应商回复日期'],['promisedDate','供应商承诺交期'],['expectedDate','预计到货日期'],['nextFollowupDate','下次催交日期']].map(([key,label])=><Field key={key} label={label}><Input aria-label={label} type="date" value={edit[key]||''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></Field>)}<Field label="本次复期数量（选填）"><Input aria-label="本次复期数量" type="number" min="1" value={edit.promisedQuantity} onChange={e=>setEdit({...edit,promisedQuantity:e.target.value})}/></Field><Field label="延期原因（晚于要求交期时必填）"><Input aria-label="供应商延期原因" value={edit.delayReason} onChange={e=>setEdit({...edit,delayReason:e.target.value})}/></Field></div>{manage&&edit.status!=='已取消'&&<Field label="本次跟进说明（必填）"><Textarea aria-label="本次供应商跟进说明" value={edit.note} onChange={e=>setEdit({...edit,note:e.target.value})} placeholder="例如：已电话核对，供应商承诺周五到货，首批 100 副。"/></Field>}</fieldset>
   {error&&<p className="error" role="alert">{error}</p>}{manage&&edit.status!=='已取消'&&<div className="flex gap-3 flex-wrap"><Button disabled={busy||edit.note.trim().length<2} onClick={saveEdit}><CheckCircle2 size={16}/>保存复期与跟进</Button><Button variant="outline" disabled={busy||edit.received>0} onClick={()=>setCancel(!cancel)}>取消此外发</Button><span className="muted">修改留痕；收货数量由送货单累计。</span></div>}{cancel&&<div className="supplier-cancel"><Field label="取消原因"><Input aria-label="取消外发原因" value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/></Field><Button variant="outline" disabled={busy||cancelReason.trim().length<3} onClick={cancelOrder}>确认取消并保留记录</Button></div>}
   <section className="supplier-timeline"><h3><MessageSquare size={17}/>跟进历史</h3><div><b>登记外发</b><span>{dateTime(edit.createdAt)} · {edit.actor}</span><p>要求交期 {edit.originalDueDate||edit.dueDate}</p></div>{(data.supplierFollowups||[]).filter(f=>f.outsourceId===edit.id).slice().reverse().map(f=><div key={f.id}><b>{f.event}</b><span>{dateTime(f.createdAt)} · {f.actor}</span><p>{f.note}</p><small>要求交期 {f.before?.dueDate||'—'} → {f.after?.dueDate||'—'} · 供应商复期 {f.before?.promisedDate||'未回复'} → {f.after?.promisedDate||'未回复'}</small></div>)}</section>
  </>}</DialogContent></Dialog>
  <Dialog open={!!master} onOpenChange={v=>{if(!v)setMaster(null);}}><DialogContent><DialogHeader><DialogTitle>{master?.id?'供应商资料':'新增供应商'}</DialogTitle><DialogDescription>采购维护联系方式和合作状态，供日常催交查阅。</DialogDescription></DialogHeader>{master&&<><fieldset disabled={!manage||busy} className="space-y-4">{[['name','供应商名称'],['contact','供应商联系人'],['phone','供应商电话']].map(([key,label])=><Field key={key} label={label}><Input aria-label={label} value={master[key]} onChange={e=>setMaster({...master,[key]:e.target.value})}/></Field>)}<Field label="供应商备注"><Textarea aria-label="供应商资料备注" value={master.notes} onChange={e=>setMaster({...master,notes:e.target.value})}/></Field><label className="flex items-center gap-2"><Checkbox aria-label="供应商合作中" checked={master.active} onCheckedChange={v=>setMaster({...master,active:!!v})}/>合作中（停用后不可新开外发）</label></fieldset>{error&&<p className="error" role="alert">{error}</p>}{manage&&<Button disabled={busy||!master.name.trim()} onClick={saveMaster}>保存供应商资料</Button>}</>}</DialogContent></Dialog>
 </div>;
}
