'use client';
import {AssignmentPanel} from './assignment-panel';
import {warehouse,balance,currentStage} from '@/lib/ledger';
import {departments} from '@/lib/departments';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {FileBarChart2,Download,Printer,Plus,Factory,Link2,AlertCircle,UserPlus,ShieldCheck} from 'lucide-react';
import {Grid,Field,Input,Choice,dateTime,type Act} from './ui';
import {roleLabels,packed,progress,broad,allowedFields,validApproval,type Order,type Member,type Report} from '@/lib/domain';
import type {Data} from './workspace';
export function MesPanel({data,act,busy,onImport,openOrder}:{data:Data;act:Act;busy:boolean;onImport:()=>void;openOrder:(o:Order)=>void}){
 const [modal,setModal]=useState<{mode:string;item:any}|null>(null),[target,setTarget]=useState(''),[qty,setQty]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState('');
 function open(mode:string,item:any){setModal({mode,item});setReason('');setTarget('');setQty(String(item.quantity??''));setError('');}
 async function submit(){if(!modal)return;try{const r=modal.item;if(modal.mode==='match')await act('match',{reportId:r.id,lineId:target,version:r.version,reason});else if(modal.mode==='correction')await act('correction',{reportId:r.id,quantity:Number(qty),reason});else await act('review',{id:r.id,decision:modal.mode,note:reason});setModal(null);}catch(e){setError((e as Error).message);}}
 const reports=data.reports.filter(r=>!search||[r.orderNo,r.drawing,r.color,r.workOrder].some(v=>v.includes(search))),unmatched=reports.filter(r=>!r.lineId);
 function reportRows(items:Report[]){return items.map(r=>{const o=data.orders.find(o=>o.id===r.lineId);return [<div><b>{r.orderNo}</b><span className="subline">{r.drawing} / {r.color} / {r.lens||'镜片待确认'}</span></div>,r.workOrder||'—',r.reportedAt,<b>{r.quantity}</b>,<span className={'pill '+(validApproval(r)?'green':'amber')}>{r.approval}</span>,o?<button className="text-link" onClick={()=>openOrder(o)}>已关联 {o.batch||'明细'}</button>:<span className="pill amber">未匹配</span>,<div className="flex gap-2">{broad(data.me)&&<Button variant="outline" size="sm" onClick={()=>open('match',r)}><Link2/>{r.lineId?'调整关联':'关联明细'}</Button>}{o&&allowedFields(data.me,o).length>0&&<Button variant="ghost" size="sm" onClick={()=>open('correction',r)}>申请更正</Button>}</div>];});}
 return <div className="space-y-5"><section className="panel section-pad"><div className="flex items-start gap-4"><span className="banner-icon"><Factory/></span><div className="flex-1"><h2 className="section-title">MES 包装报工核对</h2><p className="subtitle">先导入官方报工导出，再处理未匹配与数量差异。</p></div>{broad(data.me)&&<Button onClick={onImport}><Plus/>导入报工</Button>}</div><div className="integration-strip"><div><b>订单来源</b><span>金蝶 → MES；本版由 PMC 上传</span></div><div><b>MES 自动读取</b><span className="pill amber">接口未接通</span></div><div><b>MES 自动回写</b><span className="pill amber">接口未接通</span></div></div><p className="note">更正申请经审核后，由有权限人员在 MES 处理，再重新导入报工核验。平台不会直接改写 MES；每天 09:00 的现有人工确认提醒保持原状。</p></section>
 <section className="panel"><div className="section-pad"><Input value={search} onChange={e=>setSearch(e.target.value)} aria-label="搜索 MES 报工" placeholder="搜索订单、图纸、圈色或工单"/></div><Tabs defaultValue="all"><TabsList className="mx-6 mb-4"><TabsTrigger value="all">全部包装报工 {reports.length}</TabsTrigger><TabsTrigger value="unmatched">未匹配 {unmatched.length}</TabsTrigger><TabsTrigger value="corrections">更正申请 {data.corrections.length}</TabsTrigger></TabsList><TabsContent value="all"><Grid headers={['订单明细','工单号','报工时间','良品数','审批状态','订单对齐','操作']} rows={reportRows(reports)}/></TabsContent><TabsContent value="unmatched"><div className="note mx-6 mb-4">同一订单拆批、镜片编码不明确或找不到明细时进入此处。每笔报工只能关联一条明细，避免重复累计。</div><Grid headers={['订单明细','工单号','报工时间','良品数','审批状态','订单对齐','操作']} rows={reportRows(unmatched)}/></TabsContent><TabsContent value="corrections"><Grid headers={['订单','数量更正','原因','申请人','状态','处理']} rows={data.corrections.map(c=>[data.orders.find(o=>o.id===c.lineId)?.orderNo,<span>{c.before} → <b>{c.proposed}</b></span>,<span className="wrap">{c.reason}</span>,<div>{c.actor}<span className="subline">{dateTime(c.createdAt)}</span></div>,<div><span className={'pill '+(c.status==='导出回读已核验'?'green':'amber')}>{c.status}</span>{c.reviewNote&&<span className="subline wrap">{c.reviewer}：{c.reviewNote}</span>}</div>,broad(data.me)?<div className="flex gap-2">{c.status==='待审核'&&<><Button size="sm" variant="outline" onClick={()=>open('approve',c)}>审核通过</Button><Button size="sm" variant="ghost" onClick={()=>open('reject',c)}>驳回</Button></>}{c.status==='待 MES 人工处理'&&<Button variant="outline" size="sm" onClick={()=>open('verify',c)}>核验新导出</Button>}</div>:'—'])}/></TabsContent></Tabs></section>
 {modal&&<Dialog open onOpenChange={v=>{if(!v)setModal(null);}}><DialogContent><DialogHeader><DialogTitle>{modal.mode==='match'?'关联订单明细':modal.mode==='correction'?'提出 MES 数量更正':modal.mode==='approve'?'审核通过并待 MES 处理':modal.mode==='reject'?'驳回更正申请':'核验重新导入的报工'}</DialogTitle><DialogDescription>{modal.item.orderNo||data.orders.find(o=>o.id===modal.item.lineId)?.orderNo}　所有操作将保留记录。</DialogDescription></DialogHeader>{error&&<div className="error" role="alert">{error}</div>}{modal.mode==='match'&&<Field label="对应订单明细"><Choice label="对应订单明细" value={target} onChange={setTarget} options={[{value:'',label:'请选择核对后的明细'},...data.orders.filter(o=>[o.orderNo,o.drawing,o.color].join('|').toUpperCase()===[modal.item.orderNo,modal.item.drawing,modal.item.color].join('|').toUpperCase()).map(o=>({value:o.id,label:`${o.drawing} / ${o.color} / ${o.lens} / ${o.batch||'未分批'} / ${o.quantity}副`}))]}/></Field>}{modal.mode==='correction'&&<Field label={'建议良品数（原值 '+modal.item.quantity+'）'}><Input aria-label="建议良品数" type="number" min={0} value={qty} onChange={e=>setQty(e.target.value)}/></Field>}<Field label="核对依据 / 原因"><Textarea aria-label="核对依据 / 原因" value={reason} onChange={e=>setReason(e.target.value)} placeholder="至少 3 个字，注明已核对的来源和原因。"/></Field><p className="note">{modal.mode==='verify'?'只有新导入的同笔报工数量与建议值一致且已审批，才允许标记“导出回读已核验”。':'此操作只更新中台记录，不会向 MES 发送写入请求。'}</p><Button disabled={busy||reason.trim().length<3||(modal.mode==='match'&&!target)||(modal.mode==='correction'&&!qty)} onClick={submit}>确认{modal.mode==='match'?'关联':modal.mode==='correction'?'提交申请':'处理'}</Button></DialogContent></Dialog>}
 </div>;
}
const reportChoices=[{id:'customer',title:'客户交期回复表',description:'客户 PO、款色、订购数量与已确认回复交期。'},{id:'completion',title:'包装完工明细',description:'逐笔查看已审批、已关联的包装良品报工。'},{id:'summary',title:'订单进度汇总',description:'对比订单数量、包装完成量和剩余数量。'},{id:'progress',title:'客户订单进度表',description:'按客户汇总包装进度、剩余数与回复交期。'}];
export function ReportsPanel({data,orders,type,setType,exportFile,busy}:{data:Data;orders:Order[];type:string;setType:(v:string)=>void;exportFile:(t:string,f?:Record<string,string>)=>void;busy:boolean}){
 const [from,setFrom]=useState(''),[to,setTo]=useState('');let headers:string[],rows:React.ReactNode[][];const title=reportChoices.find(r=>r.id===type)?.title||'报表';
 if(type==='completion'){headers=['客户 / 订单','图纸 · 圈色 · 镜片','工单号','报工时间','包装良品数','审批状态'];rows=data.reports.filter(r=>orders.some(o=>o.id===r.lineId)&&validApproval(r)&&(!from||r.reportedAt.slice(0,10)>=from)&&(!to||r.reportedAt.slice(0,10)<=to)).map(r=>{const o=orders.find(o=>o.id===r.lineId)!;return [<>{o.customer}<span className="subline">{o.orderNo}</span></>,`${o.drawing} / ${o.color} / ${o.lens}`,r.workOrder,r.reportedAt,r.quantity,r.approval];});}
 else if(type==='summary'){headers=['订单 / 客户','图纸 · 圈色 · 镜片','订单数量','包装入仓','剩余数量','进度'];rows=orders.map(o=>[<>{o.orderNo}<span className="subline">{o.customer}</span></>,`${o.drawing} / ${o.color} / ${o.lens}`,o.quantity,warehouse(o)??'未记录',Math.max(0,balance(o,data.reports)??o.quantity),o.ledger?currentStage(o):progress(o,data.reports)]);}
 else {headers=['客户 / 客户 PO','订单号','图纸 · 圈色 · 镜片','订单 / 已入仓','客户要求交期','已确认回复交期','对客备注 / 分批安排'];rows=orders.map(o=>[<>{o.customer}<span className="subline">{o.customerPO||'—'}</span></>,o.orderNo,`${o.drawing} / ${o.color} / ${o.lens}`,`${o.quantity} / ${warehouse(o)??'未记录'}`,o.requestedDate||'待确认',o.promiseConfirmed?o.promisedDate:<span className="pill amber">待确认</span>,<span className="wrap">{[o.customerNote,o.arrangement].filter(Boolean).join('；')||'—'}</span>]);}
 return <div className="space-y-5"><div className="report-grid no-print">{reportChoices.map(r=><button key={r.id} className={'report-card text-left '+(type===r.id?'selected':'')} onClick={()=>setType(r.id)}><FileBarChart2 size={23}/><h3>{r.title}</h3><p>{r.description}</p></button>)}</div><section className="panel"><div className="section-pad"><div className="flex justify-between flex-wrap gap-4"><div><h2 className="section-title">{title}</h2><p className="subtitle">{rows.length} 条 · 数据截止 {dateTime(data.asOf)}</p></div><div className="flex gap-2 no-print"><Button variant="outline" disabled={!rows.length} onClick={()=>window.print()}><Printer/>打印 / 存为 PDF</Button><Button disabled={busy||!rows.length||(!!from&&!!to&&from>to)} onClick={()=>exportFile(type,{from,to})}><Download/>导出 Excel</Button></div></div>{type==='completion'&&<div className="toolbar no-print"><Field label="报工开始日期"><Input type="date" aria-label="报工开始日期" value={from} onInput={e=>setFrom(e.currentTarget.value)} onChange={e=>setFrom(e.target.value)}/></Field><Field label="报工结束日期"><Input type="date" aria-label="报工结束日期" value={to} onInput={e=>setTo(e.currentTarget.value)} onChange={e=>setTo(e.target.value)}/></Field></div>}{['customer','progress'].includes(type)&&<p className="note mt-4 no-print">对客文件只含允许对外展示的字段。未确认的回复日期显示“待确认”，不带内部备注；导出不自动发送给客户。</p>}</div><Grid headers={headers} rows={rows}/></section><section className="panel no-print"><div className="section-pad"><h2 className="section-title">已生成的报表版本</h2><p className="subtitle">重新下载当时生成的文件，后续数据修改不会改变历史文件。</p></div><Grid headers={['报表文件','生成时间','操作人','条数','下载']} rows={data.exports.map(e=>[e.filename,dateTime(e.createdAt),e.actor,e.count,<Button variant="outline" size="sm" asChild><a href={'/api/workspace/file?id='+e.id}><Download/>下载该版本</a></Button>])}/></section></div>;
}
export function MembersPanel({data,act,busy}:{data:Data;act:Act;busy:boolean}){
 const [editing,setEditing]=useState<any>(null),[error,setError]=useState('');
 async function save(){try{await act('member',{...editing,customers:editing.scope.split(/[,，\n]/).map((s:string)=>s.trim()).filter(Boolean),scope:undefined});setEditing(null);}catch(e){setError((e as Error).message);}}
 return <div className="space-y-5"><section className="panel section-pad"><div className="flex justify-between items-start"><div><h2 className="section-title">成员与数据范围</h2><p className="subtitle">成员使用各自登录账号；权限由服务端执行，查询与导出使用同一范围。</p></div>{data.me.role==='admin'&&<Button onClick={()=>{setEditing({name:'',email:'',role:'clerk',scope:'',departments:[],active:true});setError('');}}><UserPlus/>添加成员</Button>}</div><p className="note mt-5">管理员 / PMC 可查看全部订单；跟单文员默认查看本人负责订单；分配生产部门后可读取原表订单，但只可修改本部门工序；客服 / 销售按授权客户查询。添加邮箱后，还需在站点分享设置中开放给指定成员。当前站点首次发布保持创建者私有。</p></section><section className="panel"><Grid headers={['成员','角色','部门录入权限','授权客户','账号状态','操作']} rows={data.members.map(m=>[<div><b>{m.name}</b><span className="subline">{m.email}</span></div>,roleLabels[m.role],broad(m)?'全部部门':departments.filter(d=>m.departments?.includes(d.id)).map(d=>d.name).join('、')||'未分配',broad(m)?'全部客户':(m.customers||[]).join('、')||'仅本人负责订单',<span className={'pill '+(m.active?'green':'')}>{m.active?m.userId?'已加入':'已启用':'已停用'}</span>,data.me.role==='admin'?<Button variant="outline" size="sm" onClick={()=>{setEditing({...m,scope:(m.customers||[]).join('，')});setError('');}}>编辑权限</Button>:'—'])}/></section><AssignmentPanel data={data} act={act}/><section className="panel section-pad"><h2 className="section-title">数据归档</h2><p className="subtitle">原始上传文件与历史报表可以在对应记录中下载。数据快照包含结构化记录，附件原文件需另行保留。</p>{data.me.role==='admin'&&<Button variant="outline" className="mt-5" asChild><a href="/api/workspace/backup"><Download/>下载数据快照</a></Button>}<p className="note mt-5">正式切换前，需要结合公司数据存放要求配置定期备份，并完成一次恢复演练。当前快照下载不等于已配置自动备份。</p></section>
 {editing&&<Dialog open onOpenChange={v=>{if(!v)setEditing(null);}}><DialogContent><DialogHeader><DialogTitle>{editing.id?'编辑成员权限':'添加成员'}</DialogTitle><DialogDescription>使用成员实际登录邮箱；不需要提供同事密码。</DialogDescription></DialogHeader>{error&&<div className="error" role="alert">{error}</div>}<Field label="姓名"><Input aria-label="成员姓名" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="登录邮箱"><Input type="email" aria-label="成员登录邮箱" value={editing.email} disabled={!!editing.id} onChange={e=>setEditing({...editing,email:e.target.value})}/></Field><Field label="角色"><Choice label="成员角色" value={editing.role} onChange={v=>setEditing({...editing,role:v})} options={Object.entries(roleLabels).map(([value,label])=>({value,label}))}/></Field><Field label="可录入部门（可多选；仅文员角色生效）"><div className="department-checks">{departments.map(d=><label key={d.id}><Checkbox aria-label={'部门权限 '+d.name} checked={(editing.departments||[]).includes(d.id)} disabled={editing.role!=='clerk'} onCheckedChange={v=>setEditing({...editing,departments:v?[...new Set([...(editing.departments||[]),d.id])]:(editing.departments||[]).filter((id:string)=>id!==d.id)})}/>{d.name}</label>)}</div></Field><Field label="可查看的客户（客户号，以逗号分隔）"><Textarea aria-label="授权客户" disabled={['admin','pmc'].includes(editing.role)} value={editing.scope} onChange={e=>setEditing({...editing,scope:e.target.value})}/></Field><label className="flex gap-3 items-center"><Checkbox aria-label="启用成员" checked={editing.active} onCheckedChange={v=>setEditing({...editing,active:!!v})}/>启用此成员</label><Button disabled={busy||!editing.email||!editing.name} onClick={save}><ShieldCheck/>保存成员权限</Button></DialogContent></Dialog>}
 </div>;
}
