'use client';
import {useMemo,useState} from 'react';
import {Download,FileText,Plus,UploadCloud} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Choice,Empty,Field,Grid,Input,type Act} from './ui';
import {canSeeSupplierPrice} from '@/lib/suppliers';
import type {Data} from './workspace';

const categories=['原材料','配件','半成品','加工工序','成品外发','模具治具','包装及服务'];
const blank={supplier:'',category:'加工工序',itemCode:'',itemName:'',specification:'',unit:'副',qtyFrom:'0',qtyTo:'',priceExTax:'0',priceIncTax:'0',taxRate:'13',currency:'CNY',moq:'0',minimumCharge:'0',sampleFee:'0',mouldFee:'0',lossRate:'0',sampleLeadDays:'0',massLeadDays:'0',validFrom:'',validTo:'',notes:'',fileId:'',filename:''};
const money=(n:unknown,c='CNY')=>`${c} ${Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4})}`;
export function SupplierQuotePanel({data,act,busy}:{data:Data;act:Act;busy:boolean}){
 const allowed=canSeeSupplierPrice(data.me),quotes=data.supplierQuotes||[],suppliers=data.suppliers||[];
 const [q,setQ]=useState(''),[edit,setEdit]=useState<any>(null),[error,setError]=useState(''),[uploading,setUploading]=useState(false);
 const latest=useMemo(()=>{const by=new Map<string,any>();for(const x of quotes){const old=by.get(x.quoteGroupId);if(!old||x.version>old.version)by.set(x.quoteGroupId,x);}return [...by.values()].filter(x=>!q||[x.supplier,x.category,x.itemCode,x.itemName,x.specification].join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));},[quotes,q]);
 async function upload(file:File){setUploading(true);setError('');try{const form=new FormData();form.set('file',file);const item=await act('supplier-quote-file',form);setEdit((v:any)=>({...v,fileId:item.id,filename:item.filename}));}catch(e){setError((e as Error).message);}finally{setUploading(false);}}
 async function save(){setError('');try{const num=(k:string)=>Number(edit[k]||0),nullable=(k:string)=>edit[k]===''?null:Number(edit[k]);await act('supplier-quote-save',{...edit,qtyFrom:num('qtyFrom'),qtyTo:nullable('qtyTo'),priceExTax:num('priceExTax'),priceIncTax:num('priceIncTax'),taxRate:num('taxRate'),moq:num('moq'),minimumCharge:num('minimumCharge'),sampleFee:num('sampleFee'),mouldFee:num('mouldFee'),lossRate:num('lossRate'),sampleLeadDays:num('sampleLeadDays'),massLeadDays:num('massLeadDays')});setEdit(null);}catch(e){setError((e as Error).message);}}
 if(!allowed)return <section className="panel"><Empty title="采购价格受限" detail="供应商报价仅向采购/PMC、财务、业务、客服、杨德周、曲艳红及管理员开放。"/></section>;
 return <><section className="panel section-pad"><div className="panel-tools"><div><h3 className="section-title">供应商报价档案</h3><p className="subtitle">按配件、材料和加工工序保存结构化价格；每次修改产生新版本，原始报价单永久留档。</p></div><Button variant="outline" asChild><a href="/api/workspace/supplier-quote-template"><Download size={16}/>标准报价模板</a></Button><Button variant="outline" asChild><a href="/api/workspace/supplier-quote-export"><Download size={16}/>导出报价档案</a></Button><Button onClick={()=>{setError('');setEdit({...blank});}}><Plus size={16}/>录入报价</Button></div><div className="filterbar"><Input aria-label="搜索供应商报价" placeholder="供应商 / 配件 / 工序 / 编码 / 规格" value={q} onChange={e=>setQ(e.target.value)}/></div>{latest.length?<Grid headers={['供应商 / 类别','配件或工序','规格 / 计价','价格','有效期 / 版本','原始报价单','操作']} rows={latest.map(x=>[<div><b>{x.supplier}</b><span className="subline">{x.category}</span></div>,<div><b>{x.itemName}</b><span className="subline">{x.itemCode||'未设编码'}</span></div>,<div>{x.specification||'—'}<span className="subline">{x.qtyFrom}{x.qtyTo?`–${x.qtyTo}`:'+'} {x.unit}</span></div>,<div><b>{money(x.priceIncTax,x.currency)}</b><span className="subline">未税 {money(x.priceExTax,x.currency)} · 税率 {x.taxRate}%</span></div>,<div>{x.validFrom||'—'} 至 {x.validTo||'长期'}<span className="subline">V{x.version} · {x.createdBy}</span></div>,x.fileId?<a className="text-link" href={'/api/workspace/supplier-quote-file?id='+x.fileId}><FileText size={15}/> 下载</a>:'未上传',<Button size="sm" variant="outline" onClick={()=>{setError('');setEdit({...x,quoteGroupId:x.quoteGroupId,qtyTo:x.qtyTo??'',filename:''});}}>新建版本</Button>])}/>:<Empty title="还没有供应商报价" detail="可下载标准模板发给供应商，也可把微信或邮件收到的报价单上传并录入价格。"/>}</section>
 <Dialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null);}}><DialogContent className="dialog-scroll sm:max-w-[980px]"><DialogHeader><DialogTitle>{edit?.quoteGroupId?'新建报价版本':'录入供应商报价'}</DialogTitle><DialogDescription>结构化价格用于后续匹配采购与外发订单；上传的原始报价单作为依据留档。</DialogDescription></DialogHeader>{edit&&<><div className="form-grid"><Field label="供应商"><Input list="supplier-names" value={edit.supplier} onChange={e=>setEdit({...edit,supplier:e.target.value})}/></Field><Field label="报价类别"><Choice label="报价类别" value={edit.category} onChange={v=>setEdit({...edit,category:v})} options={categories.map(v=>({value:v,label:v}))}/></Field>{[['itemCode','配件/工序编码'],['itemName','配件名称/加工工序'],['specification','规格/材料/颜色'],['unit','计价单位'],['qtyFrom','数量下限'],['qtyTo','数量上限（空为不限）'],['priceExTax','未税单价'],['priceIncTax','含税单价'],['taxRate','税率(%)'],['currency','币种'],['moq','最小起订量'],['minimumCharge','最低加工费'],['sampleFee','打样费'],['mouldFee','模具费'],['lossRate','损耗比例(%)'],['sampleLeadDays','样品交期(天)'],['massLeadDays','量产交期(天)'],['validFrom','报价有效期起'],['validTo','报价有效期止']].map(([k,l])=><Field key={k} label={l}><Input aria-label={l} type={k.startsWith('valid')?'date':['itemCode','itemName','specification','unit','currency'].includes(k)?'text':'number'} min={!['itemCode','itemName','specification','unit','currency'].includes(k)?0:undefined} step={['priceExTax','priceIncTax','taxRate','lossRate'].includes(k)?'0.0001':undefined} value={edit[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></Field>)}</div><Field label="报价备注" wide><Textarea value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></Field><Field label="原始报价单" wide><label className="photo-drop"><UploadCloud size={28}/><b>{edit.filename||edit.fileId?'已关联报价单':'上传供应商原始报价单'}</b><span>XLSX、XLS、PDF、JPG、PNG、WebP · 最多 10 MB</span><Input type="file" accept=".xlsx,.xls,.pdf,.jpg,.jpeg,.png,.webp" disabled={uploading||busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file);}}/></label></Field>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy||uploading||!edit.supplier.trim()||!edit.itemName.trim()||!edit.unit.trim()} onClick={save}>保存为新版本</Button></>}</DialogContent></Dialog>
 <datalist id="supplier-names">{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.name}/>)}</datalist></>;
}
