'use client';
import {AccessNotice,PanelBoundary} from './access-notice';
import {MetricCards,MetricDetails} from './metric-details';
import type {MetricKey} from '@/lib/metric-details';
import {readsAllOrders} from '@/lib/domain';
import {useState,useMemo,useEffect,useRef} from 'react';
import {QueryClient,QueryClientProvider,useQuery,useQueryClient} from '@tanstack/react-query';
import {useReactTable,getCoreRowModel,getSortedRowModel,getPaginationRowModel,flexRender,type ColumnDef,type SortingState,type VisibilityState} from '@tanstack/react-table';
import {LayoutGrid,ClipboardList,UploadCloud,Factory,FileBarChart2,Users,Search,Plus,ArrowUpRight,RefreshCw,ChevronRight,Download,ShieldCheck,SlidersHorizontal,ArrowDownUp,X,BriefcaseBusiness,Headphones,ContactRound,Languages,FileText} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {CompanyLogo} from '@/components/company-logo';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {SidebarProvider,Sidebar,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {DropdownMenu,DropdownMenuContent,DropdownMenuCheckboxItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {Progress} from '@/components/ui/progress';
import {Input,Choice,Empty,request,type Act} from './ui';
import {Dashboard,ArchivePanel,DepartmentPanel,LedgerImport} from './ledger-panels';
import {SupplierPanel as ReceivingPanel} from './supplier-panel';
import {active,warehouse,outstanding,currentStage,issues,ownerLabel,balance} from '@/lib/ledger';
import {ImportsPanel} from './import-panel';
import {LossPanel} from './loss-panel';
import {PmcPanel} from './pmc-panel';
import {FinishedSupplierPanel} from './finished-supplier-panel';
import {CollaborationPanel,CustomerMasterPanel} from './collaboration-panel';
import {ServiceWorkspacePanel} from './service-workspace-panel';
import {FactoryOrderPanel} from './factory-order-panel';
import {CustomerQuotePanel} from './customer-quote-panel';
import {CustomerPriceArchivePanel} from './customer-price-archive-panel';
import {lossBalance,type LossRecord} from '@/lib/losses';
import {DetailPanel} from './detail-panel';
import {MesPanel,MembersPanel,ReportsPanel} from './support-panels';
import {packed,productTypeOf,progress,roleLabels,now,type Member,type Order,type Report,type Entity,type CustomerAccount} from '@/lib/domain';
export type Data={collaborationAssignments?:Array<{customerId:string;orderKeys:string[];sales:boolean;service:boolean;pmc:boolean}>;customerQuoteAccess?:boolean;quoteAuthorizedCustomerIds?:string[];customerAccounts?:CustomerAccount[];collaborationTemplates?:Entity[];losses?:LossRecord[];suppliers?:Entity[];supplierQuotes?:Entity[];supplierFollowups?:Entity[];me:Member;orders:Order[];reports:Report[];members:Member[];comments:Entity[];corrections:Entity[];attachments:Entity[];imports:Entity[];audits:Entity[];exports:Entity[];ledgerImports:Entity[];outsource:Entity[];receipts:Entity[];revision:number;asOf:string};
type Props={identity:{id:string;name:string;email:string}|null;signInUrl:string;initialView?:string;accountControls?:React.ReactNode;AccountPanel?:React.ComponentType<{data:Data;act:Act;busy:boolean}>;MaintenancePanel?:React.ComponentType<{data:Data}>};
const navigation=[['sales','业务工作台',BriefcaseBusiness],['customer-quotes','客户报价',FileBarChart2],['customer-price-archive','历史报价档案',FileText],['service','客服工作台',Headphones],['factory-orders','中英内部订单',Languages],['customers','客户责任清单',ContactRound],['pmc-handoff','PMC 交接工作台',Users],['pmc','PMC 排期总表',ClipboardList],['finished-outsourcing','成品外发跟进总表',Factory],['orders','动态订单总表',LayoutGrid],['dashboard','欠数与异常看板',FileBarChart2],['department','部门录入工作台',Factory],['losses','部门损耗月报',FileBarChart2],['receiving','供应商收货',UploadCloud],['completed','已完成订单档案',ClipboardList],['mine','我的订单',ClipboardList],['imports','上传与更新',UploadCloud],['mes','MES 核对',Factory],['reports','报表中心',FileBarChart2],['members','成员与权限',Users],['maintenance','系统维护',SlidersHorizontal]] as const;
export default function Workspace(props:Props){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:true},mutations:{retry:false}}}));return <QueryClientProvider client={client}><Surface {...props}/></QueryClientProvider>;}
function Surface({identity,signInUrl,initialView='orders',accountControls,AccountPanel,MaintenancePanel}:Props){
 const [metric,setMetric]=useState<MetricKey|null>(null);
 const cache=useQueryClient(),[view,changeView]=useState(initialView),[q,setQ]=useState(''),[customer,setCustomer]=useState(''),[owner,setOwner]=useState(''),[status,setStatus]=useState(''),[notice,setNotice]=useState<{text:string;error:boolean}|null>(null),[selected,setSelected]=useState<Order|null>(null),[sorting,setSorting]=useState<SortingState>([]),[visibility,setVisibility]=useState<VisibilityState>({}),[busy,setBusy]=useState(false),[reportType,setReportType]=useState('customer');
 const [pmcDirty,setPmcDirty]=useState(false),pmcDirtyRef=useRef(false),landingApplied=useRef(false),currentViewRef=useRef(view);pmcDirtyRef.current=pmcDirty;currentViewRef.current=view;
 useEffect(()=>{if(!pmcDirty)setNotice(n=>n?.text.startsWith('当前页面还有')?null:n);},[pmcDirty]);
 const setView=(v:string)=>{if(pmcDirtyRef.current&&v!==view){setNotice({text:'当前页面还有未保存内容，请先保存或处理冲突，再离开。',error:true});return;}changeView(v);history.pushState({},'',v==='orders'?'/':'/'+v);};
 useEffect(()=>{const pop=()=>{if(pmcDirtyRef.current){history.pushState({},'','/'+currentViewRef.current);setNotice({text:'当前页面还有未保存内容，请先处理后再离开。',error:true});return;}changeView(location.pathname.slice(1)||'orders');};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop);},[]);
 const query=useQuery<Data>({queryKey:['workspace'],enabled:!!identity,queryFn:async()=>{await request('enroll',{});return request('data');},refetchInterval:30000});
 const data=query.data,orders=useMemo(()=>(data?.orders||[]).filter(active),[data?.orders]),reports=data?.reports||[],me=data?.me;
 useEffect(()=>{if(!me||landingApplied.current)return;landingApplied.current=true;if(me.role==='pmc'&&initialView==='orders'&&(location.pathname==='/'||location.pathname==='/login')){changeView('pmc');history.replaceState({},'','/pmc');}},[me,initialView]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view]);
 const action:Act=async(name,body)=>{setBusy(true);try{const result=await request(name,body);await cache.invalidateQueries({queryKey:['workspace']});setNotice({text:name==='commit-import'?`已合并 ${result.count||0} 条记录。`:name==='preview'?'差异预览已生成，请核对后提交。':'已保存。',error:false});return result;}catch(e){setNotice({text:(e as Error).message,error:true});throw e;}finally{setBusy(false);}};
 const filters={q,customer,owner,status,mine:view==='mine'?'1':''};
 const filtered=useMemo(()=>orders.filter(o=>(view!=='mine'||o.ownerEmail===me?.email)&&(!q||[o.orderNo,o.customer,o.customerPO,o.drawing,o.color,o.lens,ownerLabel(o)].some(v=>v.toLowerCase().includes(q.toLowerCase())))&&(!customer||o.customer===customer)&&(!owner||(o.ownerEmail===owner||ownerLabel(o)===owner))&&(!status||(status==='unfinished'?(balance(o,reports)??o.quantity)>0:status==='packed'?(balance(o,reports)??o.quantity)<=0:!!o.requestedDate&&o.requestedDate<new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})&&(balance(o,reports)??o.quantity)>0))),[orders,reports,me,view,q,customer,owner,status]);
 const names=(mail:string)=>data?.members.find(m=>m.email===mail)?.name||mail||'待分配';
 const extraKeys=useMemo(()=>[...new Set(orders.flatMap(o=>Object.keys(o.extra||{})))],[orders]);
 useEffect(()=>{setVisibility(old=>({...Object.fromEntries(extraKeys.map(k=>['extra:'+k,false])),...old}));},[extraKeys.join('|')]);
 const columns=useMemo<ColumnDef<Order>[]>(()=>[
  {accessorKey:'orderNo',header:'订单 / 客户',size:205,cell:({row})=><button className="text-link" onClick={()=>setSelected(row.original)}><span className="order-id">{row.original.orderNo}</span><span className="subline">{row.original.customer}{row.original.customerPO?' · '+row.original.customerPO:''}</span></button>},
  {accessorKey:'drawing',header:'图纸编号',size:140,cell:({row})=><><b>{row.original.drawing}</b><span className="subline">{row.original.batch||'未分批'}</span></>},
  {id:'productType',header:'产品类型',size:125,accessorFn:o=>productTypeOf(o)||'未填写',cell:({getValue})=><b>{String(getValue())}</b>},
  {id:'colorLens',header:'色号 · 镜片',size:158,accessorFn:o=>o.color+' · '+o.lens},
  {id:'owner',header:'负责人',size:145,accessorFn:o=>o.ownerEmail?names(o.ownerEmail):ownerLabel(o)},
  {accessorKey:'quantity',header:'订单数量',size:110,cell:({getValue})=><b>{Number(getValue()).toLocaleString()}</b>},
  {id:'packed',header:'包装入仓',size:143,accessorFn:o=>warehouse(o)??packed(o,reports),cell:({row})=><div><b>{(warehouse(row.original)??packed(row.original,reports)).toLocaleString()}</b><span className="muted"> / {row.original.quantity.toLocaleString()}</span><Progress className="h-1.5 mt-2 w-24" value={row.original.quantity?Math.min(100,100*(warehouse(row.original)??packed(row.original,reports))/row.original.quantity):0}/></div>},
  {id:'balance',header:'出货欠数',size:110,accessorFn:o=>balance(o,reports),cell:({row})=><b className={(balance(row.original,reports)??0)>0?'text-orange-700':''}>{balance(row.original,reports)?.toLocaleString()??'待核对'}</b>},
  {id:'loss',header:'确认损耗（工序合计）',size:175,accessorFn:o=>lossBalance(data?.losses||[],o.id),cell:({row})=><span>{data?.losses?.some(r=>r.lineId===row.original.id)?<b className="text-orange-700">{lossBalance(data.losses,row.original.id).toLocaleString()}</b>:'未确认'}</span>},
  {accessorKey:'plannedDate',header:'PMC 排期',size:130},
  {accessorKey:'notes',header:'状态备注 / 跟进',size:230,cell:({getValue})=><span className="wrap">{String(getValue()||'—')}</span>},
  {accessorKey:'requestedDate',header:'客户要求交期',size:140,cell:({getValue})=>String(getValue()||'待确认')},
  {id:'promise',header:'回复交期',size:140,accessorFn:o=>o.promiseConfirmed?o.promisedDate:'待确认'},
  {id:'progress',header:'当前进度',size:180,accessorFn:o=>o.ledger?currentStage(o):progress(o,reports),cell:({row})=><span className={'pill '+((warehouse(row.original)??packed(row.original,reports))>row.original.quantity?'red':(warehouse(row.original)??packed(row.original,reports))>0?'green':'blue')}>{row.original.ledger?currentStage(row.original):progress(row.original,reports)}</span>},
  ...extraKeys.map(k=>({id:'extra:'+k,header:k,accessorFn:(o:Order)=>o.extra[k]||'',size:170})),
 ],[reports,data?.members,data?.losses,extraKeys]);
 const table=useReactTable({data:filtered,columns,state:{sorting,columnVisibility:visibility},onSortingChange:setSorting,onColumnVisibilityChange:setVisibility,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),columnResizeMode:'onChange',initialState:{pagination:{pageSize:20}}});
 async function exportFile(type:string,additional:Record<string,string>={}){setBusy(true);try{const res=await fetch('/api/workspace/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,filters:{...filters,...additional}})});if(!res.ok)throw new Error(((await res.json()) as any).error);const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=decodeURIComponent(res.headers.get('Content-Disposition')?.split("UTF-8''")[1]||'订单报表.xlsx');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await cache.invalidateQueries({queryKey:['workspace']});setNotice({text:'报表已生成，已发起下载。也可在报表中心下载该版本。',error:false});}catch(e){setNotice({text:(e as Error).message,error:true});}finally{setBusy(false);}}
 const toolsRef=useRef({data,filtered,setView,setQ,view});toolsRef.current={data,filtered,setView,setQ,view};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_visible_orders',title:'读取当前筛选订单',description:'读取当前页面授权且筛选后的订单；不修改数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('不接受参数');if(!['orders','mine','reports'].includes(toolsRef.current.view))throw new Error('请先打开动态订单总表或我的订单，再读取当前筛选明细。');return {orders:toolsRef.current.filtered.map(o=>({id:o.id,orderNo:o.orderNo,customer:o.customer,drawing:o.drawing,quantity:o.quantity})),count:toolsRef.current.filtered.length};}},{name:'filter_order_workspace',title:'筛选订单工作空间',description:'打开订单总表并设置搜索词，仅改变可见筛选，不写入业务数据。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>100||Object.keys(input).some(k=>k!=='query'))throw new Error('query 必须是最多 100 字的字符串');toolsRef.current.setQ(input.query);toolsRef.current.setView('orders');await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {view:'orders',query:input.query};}}];for(const tool of tools)Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const title=navigation.find(n=>n[0]===view)?.[1],exceptions=orders.filter(o=>issues(o).length>0).length+reports.filter(r=>!r.lineId).length+(data?.corrections.filter(c=>!['已驳回','导出回读已核验'].includes(c.status)).length||0),pending=data?.comments.filter(c=>c.dueDate&&!c.done&&orders.find(o=>o.id===c.lineId)?.ownerEmail===me?.email)||[];
 return <SidebarProvider className="workspace"><Sidebar collapsible="none" className="rail"><div className="brand"><div className="brand-logo"><CompanyLogo/></div><span>订单协作中台</span></div><div className="rail-caption">工作空间</div><nav><SidebarMenu>{navigation.filter(([id])=>(!['customer-quotes','customer-price-archive'].includes(id)||data?.customerQuoteAccess===true)&&(id!=='maintenance'||(MaintenancePanel&&me&&['admin','programmer'].includes(me.role)))).map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton className={'nav-item '+(view===id?'active':'')} onClick={()=>setView(id)}><Icon size={19}/><span>{label}</span>{id==='orders'&&<span className="nav-count">{orders.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav><div className="rail-bottom"><div className="source-card"><Factory size={19}/><div><b>业务 → 客服 → PMC</b><span>同一订单上下游协作</span></div></div><div className="account"><span className="avatar">{me?.name.slice(0,1)||'访'}</span><div><b title={identity?.email}>{me?.name||identity?.name||'尚未登录'}</b><span>{me?roleLabels[me.role]:'登录后协作'}</span></div></div></div></Sidebar><div className="main"><header className="topbar"><div>度昂眼镜 <ChevronRight size={14}/> 订单协作 <ChevronRight size={14}/><b>{title}</b></div><span className="top-note"><ShieldCheck size={16}/> 共享数据 · 修改留痕</span></header><main className="content"><div className="heading"><div><p className="eyebrow">ORDER WORKSPACE</p><h1>{title}</h1><p className="subtitle">{view==='customer-quotes'?'客户报价共享存档，中英文逐项核对，确认后再对客。':view==='mine'?'我负责的明细与待办，直接更新到总表。':'订单、生产进度和客户交期，在同一处跟进。'}</p></div><div className="actions"><Button variant="outline" disabled={busy} onClick={()=>['mine','orders'].includes(view)?void exportFile(me&&['viewer','finance','programmer'].includes(me.role)?'summary':'working'):setView('reports')}><Download/>导出报表</Button>{me&&['admin','pmc','clerk','sales'].includes(me.role)&&<Button onClick={()=>setView('imports')}><Plus/>上传订单表</Button>}</div></div>
 {notice&&<div role={notice.error?'alert':'status'} className={notice.error?'error notice':'success notice'}><span>{notice.text}</span><Button variant="ghost" size="icon" aria-label="关闭提示" onClick={()=>setNotice(null)}><X/></Button></div>}
 {!identity?<section className="panel"><Empty title="登录你的协作工作空间" detail="订单仅向获授权成员开放。"><Button asChild><a href={signInUrl} target="_top">登录并进入</a></Button></Empty></section>:query.isError?<section className="panel"><Empty title="暂时无法加载工作空间" detail={(query.error as Error).message}><Button onClick={()=>query.refetch()}>重新加载</Button></Empty></section>:!data?<section className="panel"><Empty title="正在读取共享订单…" detail="首次进入会初始化你的工作空间。"/></section>:<PanelBoundary key={view} onBack={()=>setView('orders')}>
 {['orders','mine','reports'].includes(view)&&<MetricCards data={data} onOpen={setMetric}/>}
 {(view==='orders'||view==='mine')&&<><div className="intake-banner"><span className="banner-icon"><UploadCloud/></span><div><b>{orders.length?'多人跟进同一份订单':'查看共享订单'}</b><p>{orders.length?'自动刷新间隔 30 秒。包装入仓按原表工序维护；各部门只录入自己负责的字段。':'资料统一保存在公司主机；如没有可见订单，请检查账号的查看范围。'}</p></div><Button variant="ghost" onClick={()=>setView('imports')}>上传与更新 <ArrowUpRight/></Button></div>{view==='mine'&&pending.length>0&&<section className="panel section-pad mb-5"><h2 className="section-title">待跟进 · {pending.length} 项</h2>{pending.map(c=><div className="source-line" key={c.id}><button className="text-link" onClick={()=>setSelected(orders.find(o=>o.id===c.lineId)||null)}>{c.text}</button><span>{c.dueDate}</span></div>)}</section>}</>}
 {['orders','mine','reports'].includes(view)&&<div className="filterbar no-print"><div className="search"><Search size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索订单、客户、图纸编号" aria-label="搜索订单"/></div><Choice label="客户筛选" value={customer} onChange={setCustomer} options={[{value:'',label:'全部客户'},...[...new Set(orders.map(o=>o.customer))].map(v=>({value:v,label:v}))]}/><Choice label="负责人筛选" value={owner} onChange={setOwner} options={[{value:'',label:'全部负责人'},...[...new Set(orders.map(ownerLabel))].map(v=>({value:v,label:v}))]}/><Choice label="进度筛选" value={status} onChange={setStatus} options={[{value:'',label:'全部进度'},{value:'unfinished',label:'包装未足量'},{value:'packed',label:'包装已足量'},{value:'late',label:'交期已逾期'}]}/><Button variant="ghost" onClick={()=>{setQ('');setCustomer('');setOwner('');setStatus('');}}>重置</Button></div>}
 {['orders','mine'].includes(view)&&<section className="panel"><div className="panel-tools"><b>{view==='mine'?'我负责的订单':'订单明细'} <span className="muted">{filtered.length} 条</span></b><span className="muted ml-auto">点击订单查看详情 · 拖动表头边缘调整列宽</span><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline"><SlidersHorizontal size={16}/>显示列</Button></DropdownMenuTrigger><DropdownMenuContent className="max-h-80 overflow-y-auto">{table.getAllLeafColumns().filter(c=>c.id!=='orderNo').map(c=><DropdownMenuCheckboxItem key={c.id} checked={c.getIsVisible()} onCheckedChange={v=>c.toggleVisibility(!!v)}>{String(c.columnDef.header)}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu><Button variant="outline" size="icon" title="刷新订单" aria-label="刷新订单" onClick={()=>query.refetch()}><RefreshCw className={query.isFetching?'animate-spin':''}/></Button></div><div className="order-table"><Table style={{width:table.getTotalSize()}}><TableHeader>{table.getHeaderGroups().map(hg=><TableRow key={hg.id}>{hg.headers.map(h=><TableHead key={h.id} style={{width:h.getSize(),position:'relative'}}><Button variant="ghost" size="sm" onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}{h.column.getIsSorted()?h.column.getIsSorted()==='asc'?' ↑':' ↓':<ArrowDownUp size={12}/>}</Button><div onMouseDown={h.getResizeHandler()} onTouchStart={h.getResizeHandler()} className="resizer" aria-hidden="true"/></TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.length?table.getRowModel().rows.map(row=><TableRow key={row.id}>{row.getVisibleCells().map(cell=><TableCell key={cell.id} style={{width:cell.column.getSize()}}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={table.getVisibleLeafColumns().length}><Empty title={orders.length?'没有符合筛选的订单':'暂无可查看的在制订单'} detail={orders.length?'调整客户、负责人或进度筛选后再试。':readsAllOrders(data.me)?'如总表尚未建立，请由 PMC 导入原始工作簿；已完成订单可在档案页查询。':'当前账号按客户或负责人限制查看。请联系管理员分配客户、负责人或总表查看范围，无需重复上传。'}/></TableCell></TableRow>}</TableBody></Table></div><div className="table-footer"><span>共 {filtered.length} 条明细 · 第 {table.getState().pagination.pageIndex+1} / {Math.max(1,table.getPageCount())} 页</span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>exportFile('working')} disabled={busy||!filtered.length||me?.role==='viewer'||me?.role==='finance'||me?.role==='programmer'}><Download/>导出可回传工作表</Button><Button variant="outline" size="sm" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}>上一页</Button><Button variant="outline" size="sm" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}>下一页</Button></div></div></section>}
 {view==='dashboard'&&<Dashboard data={data} act={action} busy={busy} openOrder={setSelected}/>}
 {view==='sales'&&<CollaborationPanel side="sales" data={data} act={action} busy={busy} openOrder={setSelected}/>}
 {view==='customer-quotes'&&<CustomerQuotePanel data={data} onDirtyChange={setPmcDirty}/>}
 {view==='customer-price-archive'&&<CustomerPriceArchivePanel data={data}/>}
 {view==='service'&&<ServiceWorkspacePanel data={data} openOrder={setSelected} onDirtyChange={setPmcDirty}><CollaborationPanel side="service" data={data} act={action} busy={busy} openOrder={setSelected}/></ServiceWorkspacePanel>}
 {view==='factory-orders'&&<FactoryOrderPanel data={data} act={action} busy={busy}/>}
 {view==='customers'&&<CustomerMasterPanel data={data} act={action} busy={busy}/>}
 {view==='pmc-handoff'&&<CollaborationPanel side="pmc" data={data} act={action} busy={busy} openOrder={setSelected}/>}
 {view==='finished-outsourcing'&&<div className="space-y-6"><FinishedSupplierPanel data={data}/><PmcPanel productionScope="external" data={data} openOrder={setSelected} onDirtyChange={setPmcDirty}/></div>}
 {view==='pmc'&&<PmcPanel data={data} openOrder={setSelected} onDirtyChange={setPmcDirty}/>}
 {view==='completed'&&<ArchivePanel data={data} act={action} busy={busy} openOrder={setSelected}/>}
 {view==='department'&&<DepartmentPanel data={data} act={action} busy={busy} openOrder={setSelected}/>}
 {view==='losses'&&<LossPanel data={data} openOrder={setSelected}/>}
 {view==='receiving'&&<ReceivingPanel data={data} act={action} busy={busy} openOrder={setSelected} onDirtyChange={setPmcDirty}/>}
 {view==='imports'&&<ImportsPanel data={data} act={action} busy={busy}/>}
 {view==='mes'&&<MesPanel data={data} act={action} busy={busy} onImport={()=>setView('imports')} openOrder={setSelected}/>}
 {view==='reports'&&<><section className="panel section-pad mb-5"><h2 className="section-title">部门损耗月报</h2><p className="subtitle">按确认月份查看各部门损耗新增、冲减与逐笔凭证，导出月度汇总及明细。</p><Button variant="outline" className="mt-4" onClick={()=>setView('losses')}><Download size={16}/>选择月份并导出损耗报表</Button></section><ReportsPanel data={data} orders={filtered} type={reportType} setType={setReportType} exportFile={exportFile} busy={busy}/></>}
 {view==='maintenance'&&(MaintenancePanel&&['admin','programmer'].includes(data.me.role)?<MaintenancePanel data={data}/>:<AccessNotice me={data.me} detail="系统维护仅供管理员和程序员使用。" onBack={()=>setView('orders')}/>)}
 {accountControls}
 {view==='members'&&(AccountPanel?<AccountPanel data={data} act={action} busy={busy}/>:<MembersPanel data={data} act={action} busy={busy}/>)}
 </PanelBoundary>}
 <footer className="page-footer"><span>度昂订单协作 · 总表 / 部门 / 在制 / 归档</span><span>{data?`共享数据版本 ${data.revision} · 刷新于 ${new Date(data.asOf).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}`:'实际进度以已核验来源为准'}</span></footer>
 </main></div>{metric&&data&&<MetricDetails key={metric} kind={metric} data={data} onClose={()=>setMetric(null)} openOrder={setSelected} openMes={()=>setView('mes')} refresh={()=>query.refetch()}/>} {selected&&data&&<DetailPanel order={selected} data={data} onClose={()=>setSelected(null)} onSelect={setSelected} act={action} busy={busy}/>}</SidebarProvider>;
}
