'use client';
import {useState,useMemo,useEffect,useRef} from 'react';
import {QueryClient,QueryClientProvider,useQuery,useQueryClient} from '@tanstack/react-query';
import {useReactTable,getCoreRowModel,getSortedRowModel,getPaginationRowModel,flexRender,type ColumnDef,type SortingState,type VisibilityState} from '@tanstack/react-table';
import {LayoutGrid,ClipboardList,UploadCloud,Factory,FileBarChart2,Users,Search,Plus,ArrowUpRight,RefreshCw,Glasses,ChevronRight,Download,ShieldCheck,SlidersHorizontal,ArrowDownUp,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {SidebarProvider,Sidebar,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {DropdownMenu,DropdownMenuContent,DropdownMenuCheckboxItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {Progress} from '@/components/ui/progress';
import {Input,Choice,Empty,request,type Act} from './ui';
import {ImportPanel} from './import-panel';
import {DetailPanel} from './detail-panel';
import {MesPanel,MembersPanel,ReportsPanel} from './support-panels';
import {packed,progress,roleLabels,now,type Member,type Order,type Report,type Entity} from '@/lib/domain';
export type Data={me:Member;orders:Order[];reports:Report[];members:Member[];comments:Entity[];corrections:Entity[];attachments:Entity[];imports:Entity[];audits:Entity[];exports:Entity[];revision:number;asOf:string};
type Props={identity:{id:string;name:string;email:string}|null;signInUrl:string};
const navigation=[['orders','订单总表',LayoutGrid],['mine','我的订单',ClipboardList],['imports','上传与更新',UploadCloud],['mes','MES 核对',Factory],['reports','报表中心',FileBarChart2],['members','成员与权限',Users]] as const;
export default function Workspace(props:Props){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:true},mutations:{retry:false}}}));return <QueryClientProvider client={client}><Surface {...props}/></QueryClientProvider>;}
function Surface({identity,signInUrl}:Props){
 const cache=useQueryClient(),[view,setView]=useState('orders'),[q,setQ]=useState(''),[customer,setCustomer]=useState(''),[owner,setOwner]=useState(''),[status,setStatus]=useState(''),[notice,setNotice]=useState<{text:string;error:boolean}|null>(null),[selected,setSelected]=useState<Order|null>(null),[sorting,setSorting]=useState<SortingState>([]),[visibility,setVisibility]=useState<VisibilityState>({}),[busy,setBusy]=useState(false),[reportType,setReportType]=useState('customer');
 const query=useQuery<Data>({queryKey:['workspace'],enabled:!!identity,queryFn:async()=>{await request('enroll',{});return request('data');},refetchInterval:30000});
 const data=query.data,orders=data?.orders||[],reports=data?.reports||[],me=data?.me;
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view]);
 const action:Act=async(name,body)=>{setBusy(true);try{const result=await request(name,body);await cache.invalidateQueries({queryKey:['workspace']});setNotice({text:name==='commit-import'?`已合并 ${result.count||0} 条记录。`:name==='preview'?'差异预览已生成，请核对后提交。':'已保存。',error:false});return result;}catch(e){setNotice({text:(e as Error).message,error:true});throw e;}finally{setBusy(false);}};
 const filters={q,customer,owner,status,mine:view==='mine'?'1':''};
 const filtered=useMemo(()=>orders.filter(o=>(view!=='mine'||o.ownerEmail===me?.email)&&(!q||[o.orderNo,o.customer,o.customerPO,o.drawing,o.color,o.lens].some(v=>v.toLowerCase().includes(q.toLowerCase())))&&(!customer||o.customer===customer)&&(!owner||o.ownerEmail===owner)&&(!status||(status==='unfinished'?packed(o,reports)<o.quantity:status==='packed'?packed(o,reports)>=o.quantity:!!o.requestedDate&&o.requestedDate<new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})&&packed(o,reports)<o.quantity))),[orders,reports,me,view,q,customer,owner,status]);
 const names=(mail:string)=>data?.members.find(m=>m.email===mail)?.name||mail||'待分配';
 const extraKeys=useMemo(()=>[...new Set(orders.flatMap(o=>Object.keys(o.extra||{})))],[orders]);
 useEffect(()=>{setVisibility(old=>({...Object.fromEntries(extraKeys.map(k=>['extra:'+k,false])),...old}));},[extraKeys.join('|')]);
 const columns=useMemo<ColumnDef<Order>[]>(()=>[
  {accessorKey:'orderNo',header:'订单 / 客户',size:205,cell:({row})=><button className="text-link" onClick={()=>setSelected(row.original)}><span className="order-id">{row.original.orderNo}</span><span className="subline">{row.original.customer}{row.original.customerPO?' · '+row.original.customerPO:''}</span></button>},
  {accessorKey:'drawing',header:'图纸编号',size:140,cell:({row})=><><b>{row.original.drawing}</b><span className="subline">{row.original.batch||'未分批'}</span></>},
  {id:'colorLens',header:'圈色 · 镜片',size:158,accessorFn:o=>o.color+' · '+o.lens},
  {id:'owner',header:'负责人',size:145,accessorFn:o=>names(o.ownerEmail)},
  {accessorKey:'quantity',header:'订单数量',size:110,cell:({getValue})=><b>{Number(getValue()).toLocaleString()}</b>},
  {id:'packed',header:'包装完成',size:143,accessorFn:o=>packed(o,reports),cell:({row})=><div><b>{packed(row.original,reports).toLocaleString()}</b><span className="muted"> / {row.original.quantity.toLocaleString()}</span><Progress className="h-1.5 mt-2 w-24" value={row.original.quantity?Math.min(100,100*packed(row.original,reports)/row.original.quantity):0}/></div>},
  {accessorKey:'requestedDate',header:'客户要求交期',size:140,cell:({getValue})=>String(getValue()||'待确认')},
  {id:'promise',header:'回复交期',size:140,accessorFn:o=>o.promiseConfirmed?o.promisedDate:'待确认'},
  {id:'progress',header:'当前进度',size:180,accessorFn:o=>progress(o,reports),cell:({row})=><span className={'pill '+(packed(row.original,reports)>row.original.quantity?'red':packed(row.original,reports)>0?'green':'blue')}>{progress(row.original,reports)}</span>},
  ...extraKeys.map(k=>({id:'extra:'+k,header:k,accessorFn:(o:Order)=>o.extra[k]||'',size:170})),
 ],[reports,data?.members,extraKeys]);
 const table=useReactTable({data:filtered,columns,state:{sorting,columnVisibility:visibility},onSortingChange:setSorting,onColumnVisibilityChange:setVisibility,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),columnResizeMode:'onChange',initialState:{pagination:{pageSize:20}}});
 async function exportFile(type:string,additional:Record<string,string>={}){setBusy(true);try{const res=await fetch('/api/workspace/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,filters:{...filters,...additional}})});if(!res.ok)throw new Error(((await res.json()) as any).error);const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=decodeURIComponent(res.headers.get('Content-Disposition')?.split("UTF-8''")[1]||'订单报表.xlsx');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await cache.invalidateQueries({queryKey:['workspace']});setNotice({text:'报表已生成，已发起下载。也可在报表中心下载该版本。',error:false});}catch(e){setNotice({text:(e as Error).message,error:true});}finally{setBusy(false);}}
 const toolsRef=useRef({data,filtered,setView,setQ});toolsRef.current={data,filtered,setView,setQ};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_visible_orders',title:'读取当前筛选订单',description:'读取当前页面授权且筛选后的订单；不修改数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('不接受参数');return {orders:toolsRef.current.filtered.map(o=>({id:o.id,orderNo:o.orderNo,customer:o.customer,drawing:o.drawing,quantity:o.quantity})),count:toolsRef.current.filtered.length};}},{name:'filter_order_workspace',title:'筛选订单工作空间',description:'打开订单总表并设置搜索词，仅改变可见筛选，不写入业务数据。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>100||Object.keys(input).some(k=>k!=='query'))throw new Error('query 必须是最多 100 字的字符串');toolsRef.current.setQ(input.query);toolsRef.current.setView('orders');await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {view:'orders',query:input.query};}}];for(const tool of tools)Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const title=navigation.find(n=>n[0]===view)?.[1],exceptions=reports.filter(r=>!r.lineId).length+(data?.corrections.filter(c=>!['已驳回','导出回读已核验'].includes(c.status)).length||0),pending=data?.comments.filter(c=>c.dueDate&&!c.done&&orders.find(o=>o.id===c.lineId)?.ownerEmail===me?.email)||[];
 return <SidebarProvider className="workspace"><Sidebar collapsible="none" className="rail"><div className="brand"><span className="brand-mark"><Glasses size={25}/></span><div><strong>DOON</strong><span>订单协作中台</span></div></div><div className="rail-caption">工作空间</div><nav><SidebarMenu>{navigation.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton className={'nav-item '+(view===id?'active':'')} onClick={()=>setView(id)}><Icon size={19}/><span>{label}</span>{id==='orders'&&<span className="nav-count">{orders.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav><div className="rail-bottom"><div className="source-card"><Factory size={19}/><div><b>金蝶 → MES → 订单</b><span>当前采用文件导入</span></div></div><div className="account"><span className="avatar">{me?.name.slice(0,1)||'访'}</span><div><b title={identity?.email}>{me?.name||identity?.name||'尚未登录'}</b><span>{me?roleLabels[me.role]:'登录后协作'}</span></div></div></div></Sidebar><div className="main"><header className="topbar"><div>度昂眼镜 <ChevronRight size={14}/> 订单协作 <ChevronRight size={14}/><b>{title}</b></div><span className="top-note"><ShieldCheck size={16}/> 共享数据 · 修改留痕</span></header><main className="content"><div className="heading"><div><p className="eyebrow">ORDER WORKSPACE</p><h1>{title}</h1><p className="subtitle">{view==='mine'?'我负责的明细与待办，直接更新到总表。':'订单、生产进度和客户交期，在同一处跟进。'}</p></div><div className="actions"><Button variant="outline" onClick={()=>setView('reports')}><Download/>导出报表</Button>{me&&['admin','pmc','clerk'].includes(me.role)&&<Button onClick={()=>setView('imports')}><Plus/>上传订单表</Button>}</div></div>
 {notice&&<div role={notice.error?'alert':'status'} className={notice.error?'error notice':'success notice'}><span>{notice.text}</span><Button variant="ghost" size="icon" aria-label="关闭提示" onClick={()=>setNotice(null)}><X/></Button></div>}
 {!identity?<section className="panel"><Empty title="登录你的协作工作空间" detail="订单仅向获授权成员开放。"><Button asChild><a href={signInUrl} target="_top">登录并进入</a></Button></Empty></section>:query.isError?<section className="panel"><Empty title="暂时无法加载工作空间" detail={(query.error as Error).message}><Button onClick={()=>query.refetch()}>重新加载</Button></Empty></section>:!data?<section className="panel"><Empty title="正在读取共享订单…" detail="首次进入会初始化你的工作空间。"/></section>:<>
 <div className="metrics">{[['有效订单',new Set(orders.filter(o=>o.sourceStatus!=='已取消').map(o=>o.orderNo)).size,'按订单号去重'],['进行中明细',orders.filter(o=>o.sourceStatus!=='已取消'&&packed(o,reports)<o.quantity).length,'按款式 / 颜色 / 镜片'],['包装已完成',orders.reduce((n,o)=>n+packed(o,reports),0),'已关联 · 已审批良品'],['待处理异常',exceptions,'未匹配报工与更正']].map(([l,n,d])=><div className="metric" key={l}><span>{l}</span><strong>{Number(n).toLocaleString()}<small>{l==='包装已完成'?'副':'项'}</small></strong><p>{d}</p></div>)}</div>
 {(view==='orders'||view==='mine')&&<><div className="intake-banner"><span className="banner-icon"><UploadCloud/></span><div><b>{orders.length?'多人跟进同一份订单':'从第一份订单工作表开始'}</b><p>{orders.length?'自动刷新间隔 30 秒。生产数量以最近导入的有效包装报工为准。':'上传 PMC 表格，核对差异后汇入总表。MES 接口尚未接通。'}</p></div><Button variant="ghost" onClick={()=>setView('imports')}>上传与更新 <ArrowUpRight/></Button></div>{view==='mine'&&pending.length>0&&<section className="panel section-pad mb-5"><h2 className="section-title">待跟进 · {pending.length} 项</h2>{pending.map(c=><div className="source-line" key={c.id}><button className="text-link" onClick={()=>setSelected(orders.find(o=>o.id===c.lineId)||null)}>{c.text}</button><span>{c.dueDate}</span></div>)}</section>}</>}
 {['orders','mine','reports'].includes(view)&&<div className="filterbar no-print"><div className="search"><Search size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索订单、客户、图纸编号" aria-label="搜索订单"/></div><Choice label="客户筛选" value={customer} onChange={setCustomer} options={[{value:'',label:'全部客户'},...[...new Set(orders.map(o=>o.customer))].map(v=>({value:v,label:v}))]}/><Choice label="负责人筛选" value={owner} onChange={setOwner} options={[{value:'',label:'全部负责人'},...[...new Set(orders.map(o=>o.ownerEmail).filter(Boolean))].map(v=>({value:v,label:names(v)}))]}/><Choice label="进度筛选" value={status} onChange={setStatus} options={[{value:'',label:'全部进度'},{value:'unfinished',label:'包装未足量'},{value:'packed',label:'包装已足量'},{value:'late',label:'交期已逾期'}]}/><Button variant="ghost" onClick={()=>{setQ('');setCustomer('');setOwner('');setStatus('');}}>重置</Button></div>}
 {['orders','mine'].includes(view)&&<section className="panel"><div className="panel-tools"><b>{view==='mine'?'我负责的订单':'订单明细'} <span className="muted">{filtered.length} 条</span></b><span className="muted ml-auto">点击订单查看详情 · 拖动表头边缘调整列宽</span><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline"><SlidersHorizontal size={16}/>显示列</Button></DropdownMenuTrigger><DropdownMenuContent className="max-h-80 overflow-y-auto">{table.getAllLeafColumns().filter(c=>c.id!=='orderNo').map(c=><DropdownMenuCheckboxItem key={c.id} checked={c.getIsVisible()} onCheckedChange={v=>c.toggleVisibility(!!v)}>{String(c.columnDef.header)}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu><Button variant="outline" size="icon" title="刷新订单" aria-label="刷新订单" onClick={()=>query.refetch()}><RefreshCw className={query.isFetching?'animate-spin':''}/></Button></div><div className="order-table"><Table style={{width:table.getTotalSize()}}><TableHeader>{table.getHeaderGroups().map(hg=><TableRow key={hg.id}>{hg.headers.map(h=><TableHead key={h.id} style={{width:h.getSize(),position:'relative'}}><Button variant="ghost" size="sm" onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}{h.column.getIsSorted()?h.column.getIsSorted()==='asc'?' ↑':' ↓':<ArrowDownUp size={12}/>}</Button><div onMouseDown={h.getResizeHandler()} onTouchStart={h.getResizeHandler()} className="resizer" aria-hidden="true"/></TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.length?table.getRowModel().rows.map(row=><TableRow key={row.id}>{row.getVisibleCells().map(cell=><TableCell key={cell.id} style={{width:cell.column.getSize()}}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={table.getVisibleLeafColumns().length}><Empty title={orders.length?'没有符合筛选的订单':'还没有导入订单'} detail={orders.length?'调整客户、负责人或进度筛选后再试。':'上传第一份 PMC 订单表，开始协作。'}/></TableCell></TableRow>}</TableBody></Table></div><div className="table-footer"><span>共 {filtered.length} 条明细 · 第 {table.getState().pagination.pageIndex+1} / {Math.max(1,table.getPageCount())} 页</span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>exportFile('working')} disabled={busy||!filtered.length||me?.role==='viewer'}><Download/>导出可回传工作表</Button><Button variant="outline" size="sm" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}>上一页</Button><Button variant="outline" size="sm" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}>下一页</Button></div></div></section>}
 {view==='imports'&&<ImportPanel data={data} act={action} busy={busy}/>}
 {view==='mes'&&<MesPanel data={data} act={action} busy={busy} onImport={()=>setView('imports')} openOrder={setSelected}/>}
 {view==='reports'&&<ReportsPanel data={data} orders={filtered} type={reportType} setType={setReportType} exportFile={exportFile} busy={busy}/>}
 {view==='members'&&<MembersPanel data={data} act={action} busy={busy}/>}
 </>}
 <footer className="page-footer"><span>度昂订单协作 · 文件导入首版</span><span>{data?`共享数据版本 ${data.revision} · 刷新于 ${new Date(data.asOf).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}`:'实际进度以已核验来源为准'}</span></footer>
 </main></div>{selected&&data&&<DetailPanel order={selected} data={data} onClose={()=>setSelected(null)} onSelect={setSelected} act={action} busy={busy}/>}</SidebarProvider>;
}
